### ISSUE TITLE
Define expected behaviour after a change to: market.liquidityProvision.shapes.maxSize

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1027]
In order to have a test to be sure that a change to the `market.liquidityProvision.shapes.maxSize` network parameter has the expected resulting behaviour we need to define:

- Values that the parameter should change from / to
- the expected behaviour when the values are changed

**Comment by Jiajia-Cui** [comment]
close with [https://github.com/vegaprotocol/specs-internal/pull/1042](url)
