### ISSUE TITLE
Define expected behaviour after a change to: reward.staking.delegation.maxPayoutPerEpoch

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1030]
In order to have a test to be sure that a change to the `reward.staking.delegation.maxPayoutPerEpoch` network parameter has the expected resulting behaviour we need to define:

- Values that the parameter should change from / to
- the expected behaviour when the values are changed

**Comment by Jiajia-Cui** [comment]
https://github.com/vegaprotocol/specs-internal/pull/1060

**Comment by Jiajia-Cui** [comment]
close with [https://github.com/vegaprotocol/specs-internal/pull/1060#discussion_r857949724](url)

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/specs-internal/pull/1072
