### ISSUE TITLE
Ghost peg

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1032]
As per slack thread: https://vegaprotocol.slack.com/archives/C016UN77UUX/p1649422203892589

Update the spec to include the ghost peg solution (or one of the other options)

**Comment by davidsiska-vega** [comment]
We should think how we replenish LP order volume if we are introducing ghost pegs.

Maybe we think this is OK; ghost pegs will be short lived, then the market will go into liquidity auction.
