### ISSUE TITLE
expose why a transaction was rejected by a node

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1037]
In order to make the changes required in:
- https://github.com/vegaprotocol/vega/issues/5207

We need to discuss and update any specs/acceptance criteria in line with the [slack thread](https://vegaprotocol.slack.com/archives/CCBC320RM/p1649089257305019) 

We need make sure it is possible to find out why a transaction was rejected by a node (spam protection triggered, etc.).

Currently if a transaction is rejected by checkTX is does not get included in the block (as expected) and the user submitting the transaction is not notified of the rejection. This means a user does not know why the transaction was rejected.

**Comment by barnabee** [comment]
@gordsport I think there are already some relevant ACs, for example:

- [Spam protection (0062-SPAM-013)](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0062-SPAM-spam_protection.md#0062-SPAM-013)
- [data sourcing (0045-DSRC-013)](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0045-DSRC-data_sourcing.md#0045-DSRC-013) (though could clarify that it's an API requirement not internal node logging)

There may be other specs like the [transaction validation](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0049-TVAL-validate_transaction_preconsensus.md) spec that need ACs adding for this too.

**Comment by gordsport** [comment]
Closing as covered already captured in specs and ACs
