### ISSUE TITLE
Feature request: Have Tags on New Asset proposal as per New Market proposal

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/specs#1040]
It may be useful to have tags on Assets so that proposers can help other Vega users.

For example:
`FauctetFucntion:Faucet`
`FaucetURL:https://faucet.vusd.vega.xyz`
`Networkname:Ropsten`
`creator:Vega`

I guess it would result in something like:
```
{
      "ID": "2fdd696ac7787d98afcbc136d4cf17bc595f7c0c6d3bf57c0ceeb5184347b725",
      "name": "Bitcoin",
      "symbol": "BTC",
      "totalSupply": "21000000",
      "decimals": "5",
      "source": {
        "builtinAsset": {
          "name": "Bitcoin",
          "symbol": "BTC",
          "totalSupply": "21000000",
          "decimals": "5",
          "maxFaucetAmountMint": "1000000"
        },
        "metadata": {
            "tags": [
              "faucetFunction:MakeitRain"
            ]
          }
      }
    },
```

This could then be [used in console](https://github.com/vegaprotocol/console/issues/4230) to provide a handy link to faucet. 
<img width="447" alt="Screenshot 2020-11-10 at 15 40 16" src="https://user-images.githubusercontent.com/13255539/98696331-90a2e700-236b-11eb-8611-f711b7a5ad36.png">

**Comment by gordsport** [comment]
Hey @campbellssource 
is this request still open based on the above mentioned closed PRs?

**Comment by davidsiska-vega** [comment]
ERC20 would normally (Ethereum mainnet) not have a "faucet".
