### ISSUE TITLE
Batching transactions

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1122]
Currently a party submitting a transaction can only include one "command" per tendermint transaction. Example is posting one limit order in a tendermint transaction. 

In many cases it would be more efficient if we allowed batches, e.g. up to 100 limit orders per tendermint transaction. Discuss.

**Comment by davidsiska-vega** [comment]
We now have https://github.com/vegaprotocol/specs/blob/master/protocol/0074-BTCH-batch-market-instructions.md
