### ISSUE TITLE
Request: Add 24hour traded volume to market data spec

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/specs#1129]
The [market data spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0021-MDAT-market_data_spec.md) includes some good headline data that a user can use to get a sense of a market. e.g. open interest.
But it doesn't include 24 hour traded volume.
<img width="716" alt="Screenshot 2022-06-23 at 16 08 06" src="https://user-images.githubusercontent.com/13255539/175332676-f40f8f91-f250-4c01-953a-558147dd419d.png">
<img width="870" alt="Screenshot 2022-06-23 at 16 10 39" src="https://user-images.githubusercontent.com/13255539/175332699-7e1b0be5-5c42-44b4-b332-ea8631976969.png">
<img width="270" alt="Screenshot 2022-06-23 at 16 09 48" src="https://user-images.githubusercontent.com/13255539/175332723-fd3cf17e-c11d-4b05-ad97-2ca209e399b0.png">
<img width="1377" alt="Screenshot 2022-06-23 at 11 00 40" src="https://user-images.githubusercontent.com/13255539/175332752-2c9d9c6e-69fa-4462-98f8-21a0f12b1ce1.png">

At the moment the only way to get this is to use the candles API.

Questions:
- What should happen in the first 24hours
- how often does this need to update, does it need to be rolling

**Comment by campbellssource** [comment]
suggestion for the first 24 hours: just sum up what has traded so far. (don't scale it up).
In a UI you'll probably be looking at a page with a chart (🤞 something says when the market started) So I think it'll be clear from context that the volume is only what has been traded. 
I also think
`24hr traded vol` is an accurate description of the "it only included what has happened so far"
it would need to be `24hr traded vol (potentially scaled)

**Comment by davidsiska-vega** [comment]
Candles have volumes, can this be obtained from there?
