### ISSUE TITLE
Add market and Instrument statuses to market framework design file

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#114]
In GitLab by @tamlyn10 on May 29, 2019, 06:48

Translate the below content into the market framework design file.

# Market and instrument statuses

Notes:
* Token holders vote on acceptance of a new Market
* Token holders may vote to close a market.
* Product is code that is instantiated with a market. This code will be reused for every instrument and market that use that product.
* Instrument and Tradeable Instrument are only ever used on one market (for now)

### Product

No statuses needed

### Instrument 
_Product + product-parameters_

- Active
- Expired // expiration will occur due to an event emitted by the product

### Tradeable instrument 
_Product + risk model + risk-parameters_

No statuses needed

### Market 
_Tradeable instrument + MM stake + market-parameters_

- Proposed // period of time while collection of MM stake. During this time token holders can vote, even if it’s an indefinite 
- Rejected //
- (Pending) // we may want a state for the initial opening auction of a new market 
- Open
- Closed { reason: [] } // reason will refer to ‘expiry’, ‘governance-action’ or similar
- Settled
- Suspended

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on May 29, 2019, 06:57

changed title from **Market and Instrument status{-’-}** to **Market and Instrument status{+es+}**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on May 29, 2019, 06:57

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on May 29, 2019, 07:00

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jun 21, 2019, 14:12

changed title from **{-Market and Instrument statuses-}** to **{+Add market and Instrument statuses to market framework design file+}**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jun 21, 2019, 14:12

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jun 21, 2019, 15:23

removed milestone

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jun 21, 2019, 15:23

assigned to @tamlyn10

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:21

removed milestone

**Comment by edd** [comment]
This one eventually got covered by https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0043-market-lifecycle.md
