### ISSUE TITLE
Deal with remaining tests in `qa-scenarios` with a view of removing it

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1144]
For a while feature tests have been part of core. Currently we have some "dregs" in https://github.com/vegaprotocol/specs-internal/tree/master/qa-scenarios . 

We need to review what they do, if they're covered elsewhere they should be removed and eventually the whole `qa-scenarios` folder deleted.

**Comment by Jiajia-Cui** [comment]
close with [PR](https://github.com/vegaprotocol/specs-internal/pull/1151)
