### ISSUE TITLE
Offbook liquidity sources: step 1 towards "passive" liquidity

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1150]
Currently we have liquidity shapes which "dump" pegged order volume on the book. 

This is potentially inefficient. In fact to execute an aggresive trade against any liquidity that's not LOs on the book we just need:
-  the best bid / ask and the volume at best / bid ask 
- volume implied by book liquidity source for magin. 

The trading engine will then maintain a buy side sorted (by price) list (and sell side sorted list) of "liquidity sources" - to execute trades against. The "true" limit order book then just becomes another liquidity source. Examples of other liquidity sources are:
- LP shapes as we have now
- LP dynamically adjusted and generated LP shapes (separate spec / paper / note required)
- Constant-function-market-like liquidity.

**Comment by gordsport** [comment]
closing as now all covered in [Passive Liquidity, maybe with CFM-based AMMs](https://github.com/vegaprotocol/specs/issues/1990)
