### ISSUE TITLE
Write/update the protocol upgrade spec

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1160]
When starting the new protocol upgrade spec we had the following document:
 - https://github.com/vegaprotocol/specs/pull/874
 
 The details in this have now been superseded with the latest design/implementation
 
 This issue is to cover documenting the current process in a spec

**Comment by davidsiska-vega** [comment]
Should also include 
- details about data node upgrade / update.
- ACs ;-)
- risks around ecosystem protocol update
