### ISSUE TITLE
Update field constraints in governance proposals

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1184]
In order to update the field constraints in governance proposals we need to agree on what the changes should be:

- https://github.com/vegaprotocol/vega/issues/5752

We need to understand:

- [x] limitations on storage etc.. on the chain (@ze97286 / @jeremyletang)
- [x] what the FE requirements look like (@campbellssource)
- [ ] What the community / builders club would deem as a good UX experience (@cdm / @daunatv)

**Comment by campbellssource** [comment]
@barnabee also raised the idea that we could add a title field, that would help when listing proposals.
We should decide on if we want that and how long it should be.

**Comment by campbellssource** [comment]
Agreed on Slack to the following updates:

- the spec should be updated to say that the description character limit is 20k
- there should be a new field: title (limited to 100)
- the URL field should be removed
- the has field should be removed

**Comment by campbellssource** [comment]
PR for spec change here: https://github.com/vegaprotocol/specs/pull/1186
