### ISSUE TITLE
Add validation to 0027-ASSP-asset_proposal.md and remove total supply

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1187]
- Remove total supply - this was intended for governance - but governance asset is now bridged differently, so no need for total supply. 
- Spec should mention that 
  1. contract exists at the address
  1. no vega asset is already using this contract address
  1. ABI interface of proposed asset conforms to ERC20
  1. symbol matches
  1. name matches
  1. decimals match
- ACs should be added for the above.

**Comment by davidsiska-vega** [comment]
> -  we have no asset existing with that address -> ok
> - we have an asset existing with this address -> fail
> - we have no asset existing with this address but a proposal for it already ?

My hunch would be that the proposal should be accepted (so two parallel running proposals on the same ERC20 address are ok).
Once the proposal is successful we need another check for "we have no asset existing with that address -> ok / we have an asset existing with this address -> fail".

**Comment by edd** [comment]
I need some answers before I can update this spec:

- [x] Polling ERC20 contracts for details changes is not implemented - **true** (verified by @jeremyletang)
    - > Note: Also most will not change anyway. Some can.
- [x] Can I remove this requirement? Or does it need to be implemented? - **It can be removed** (answered by @jeremyletang & @davidsiska-vega)
    - > Total supply has been removed. Name and symbol will not change. So this is not required.

# Outcome
Removing this:


> Vega nodes will run nodes for all bridged chains. They will either listen to the relevant events or poll the current value of these data reguarly in order to ensure that the asset data on Vega reflects the current value (after the configured number of confirmations).
>
> In the case of Ethereum ERC20 assets, in will be necessary to poll the contract’s “read” functions (name, symbol, totalSupply) as specified in the ERC20 standard, because no events are standardised for changes to these values.
>
> This polling would ideally be done with each new Ethereum block, but if this is too expensive (in computational costs — there is no gas for read functions) then as long as it occurs at least once per epoch this is acceptable.
