### ISSUE TITLE
Data node spec improvements and ACs

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1203]
The spec should clarify:
- how does data node get its data, how it restarts, how it catches up 
- how does it communicate liveness / up-to-dateness / readiness to serve clients to clients
- how does it handle core restarts, core going down, ingesting data slower than core produces them (forever / for a long period of time)

**Comment by gordsport** [comment]
Copied over from duplicate[ issue](https://github.com/vegaprotocol/specs/issues/1220):
Update the data-node spec with ACs around testing, to include (pending review/re-writing) but not exhaustive:

Datanode:
- [ ] APIs
- [ ] datanode snapshots
- [ ] post protocol upgrade 

Data comparison:
- [ ] Diff core snapshots against datanode state
- [ ] Using PG Dump tools to compare data across datanodes on the network

**Comment by gordsport** [comment]
Closing as conversations / reviews to happen against:
https://github.com/vegaprotocol/specs/pull/1239
