### ISSUE TITLE
Determine if we need a position-resolution API?

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#121]
In GitLab by @tamlyn10 on Jul 9, 2019, 17:27
*left issue as template boilerplate*

Updated by @barnabee:
How do we find out each position resolution event, separate them from other events (i.e. querying on order counterparty = network isn't sufficient), and understand what happened as a result?

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 16:40

closed

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:21

reopened

**Comment by barnabee** [comment]
@jeremyletang @pand-dev @edd how would you guys see us determining via an API query when (if ever) position resolution has occurred and what the outcomes (positions closed, at what prices, etc.), liquidity trigger hit and auction started, etc. were?
