### ISSUE TITLE
Protection against order book bullying

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#126]
In GitLab by @tamlyn10 on Aug 27, 2019, 15:49

## The problem
Barney and Tamlyn having conversation about the following scenario: A trader drills the depth (buys up the order book) and they now have a positive mark to market in their account (assuming they fall just short of the price protection level). If this is released to their general account they can use this money on other markets.

## Mitigations

- funds that are released must have been in the margin account for a minimum of n blocks.
- trader must owe the insurance fund what gets utilised due to their losses

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Aug 27, 2019, 15:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:05

assigned to @tamlyn10

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:05

assigned to @davidsiska-vega

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:06

assigned to @barnabee

**Comment by barnabee** [comment]
@tamlyn10 are you keeping a repository of attacks/manipulations for modelling and investigation/mitigation somewhere? I think we discussed this once but unsure if it happened.
