### ISSUE TITLE
Resetting maintenance margin periodically

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#127]
In GitLab by @tamlyn10 on Aug 27, 2019, 16:06

Configure risk model to update risk factors according to time based or data based reasons.

Not penalise for order book depth changes. Should we set market observable once per day (align with RF change).  Could move MO with mark price.

Trading predictability with capital efficiency.

Could optimise by:
- only calculate a subset of traders
- only calculate if order book becomes more risky

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Aug 27, 2019, 16:07

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Aug 27, 2019, 16:24

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 15:09

changed title from **{-Only resetting maintenance margin daily (for example)-}** to **{+Resetting maintenance margin periodically+}**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:05

assigned to @tamlyn10

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 13, 2019, 18:33

changed the description

**Comment by barnabee** [comment]
@tamlyn10 did anything more substantial ever come of the margin volatility thinking? (i.e. is there any more stuff we've done on this?)

**Comment by tamlyn10** [comment]
I think we have a research ticket on this..

**Comment by barnabee** [comment]
Cool if we manage to migrate the research tickets lets link it here and close this.

**Comment by tamlyn10** [comment]
Gitlab link meanwhile: https://gitlab.com/vega-protocol/papers/-/issues/48

**Comment by tamlyn10** [comment]
(i'll make sure this issue is properly represented in the migrated issue then close this)
