### ISSUE TITLE
LNL/ Snapshots ACs to be added

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1275]
**Checkpoint LNL**
Settlement market going to LNL checkpoint  - shouldn’t come up
Define market with termination trigger - post LNL can then terminate
market_details match pre checkpoint. -stretch
Settled market going to LNL checkpoint  - shouldn’t come up

**Comment by davidsiska-vega** [comment]
I've removed "**Snapshots**  Market data after node is joined / LP orders still exist" because that's more of a data node thing or so it seems to me.
