### ISSUE TITLE
Node validator design

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#128]
In GitLab by @tamlyn10 on Sep 9, 2019, 16:44

This ticket covers:

1. Technical requirements to run a node

2. Operational obligations of node runner

For node running reward and penalty structure see linked analysis ticket

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Sep 9, 2019, 16:47

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 15:11

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 15:12

marked this issue as related to #136

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 15:13

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:07

assigned to @barnabee

**Comment by barnabee** [comment]
@tamlyn10 I don't think these two things (technical requirements for a node or operational obligations of running one) belong in here, I also think they'll be covered as we pgoress the Launch Validator Programme.

Not comfortable to close without your agreement though so please close or ask me to if you're OK with that. If not let's discuss how we will cover this here.

**Comment by tamlyn10** [comment]
That's fine with me. Closing now.
