### ISSUE TITLE
Add AC to 0073-LIMN-limited_network_life

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1307]
https://github.com/vegaprotocol/system-tests/issues/811

Long epoch scenario

**Comment by davidsiska-vega** [comment]
@vega-paul I've no idea what is this issue asking to do. What additional ACs would you like to see? Is it something on top of https://github.com/vegaprotocol/specs/pull/1299 ?

**Comment by vega-paul** [comment]
Will add something when we refactor our old suite of LNL tests and enable a few LNL cases.
