### ISSUE TITLE
AC needs a home - at the point of leaving auction to continuous what happens if parties become distressed. Define expected behaviour

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1322]
Find home spec for this..

AC - at the point of leaving auction to continuous what happens if parties become distressed. Define expected behaviour.

**Comment by gordsport** [comment]
@EVODelavega - please can you detail the current functionality so we can check ACs cover this as we would like?

@Jiajia-Cui - do we have an existing FT for this scenario?

**Comment by witgaw** [comment]
I'll verify the current behaviour and record it as AC
