### ISSUE TITLE
Write spec for cancelling orders

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#134]
In GitLab by @tamlyn10 on Sep 16, 2019, 15:25

As per Slack message: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1568643724025700?thread_ts=1568642627.016800&cid=CAHA5EX0F

For OrderCancellation, it should probably be one of order ID, market ID, party ID or potentially always a party ID plus optionally either order ID or market ID, because for cancellation we should support:
1) cancel specific order by ID
2) cancel all orders I have on a market
3) cancel all my orders on the network
I’m not sure if this is what’s implemented atm

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Sep 16, 2019, 15:26

changed title from **{-C-}ancelling orders** to **{+Write spec for c+}ancelling orders**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Sep 16, 2019, 15:26

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Sep 16, 2019, 15:30

marked this issue as related to trading-core#435

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Oct 17, 2019, 12:06

@tamlyn10 why would we want the potentially dangerous cancel all orders feature?

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 18, 2019, 12:08

@cdm can you explain what you mean by dangerous?

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Oct 18, 2019, 12:12

Sure btw indirectly i discussed this with Barney who says it’s very much a
feature

Dangerous if done accidentally :)

But computationally and system design wise this ticket will have big impact

I propose when it’s time to schedule this work (post nicenet) you and I
design it from both Protocol and Impl architecture to make sure the devs
implement it correctly 🚀

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 18, 2019, 12:13

Yes, I was keen to know why you thought it was dangerous. For a trader, having control over their orders is paramount. We would never leave a feature out because that trader might use it accidentally.

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 18, 2019, 12:15

@barnabee will specification of this fall under the matching engine spec?

**Comment by tamlyn10** [comment]
We should make a new spec similar to order amends for order cancellation.
