### ISSUE TITLE
0059-STKG-simple_staking_and_delegating - spec needs updating to align with implementation

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1345]
Specs seems out of date and requires a full review against what has been delivered

Once completed we can review again for missing ACs

**Comment by davidsiska-vega** [comment]
I would argue that this is not a priority of Oregon Trail as this has been running happily in mainnet for ages.

**Comment by vega-paul** [comment]
nothing to do here, ST adjustment

**Comment by vega-paul** [comment]
Agree running well but we still need to write tests against approved specs which may/will
- identify missing functionality
- identify potential regressions within core builds
