### ISSUE TITLE
Re-write 0078-NWLI network limits spec

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1379]
After a review we have decided that we will rework this spec to only include:

- Limit the number of pegged orders Vega wide.
- Add limits of the number/type of transactions that can be added to a block (based on Tendermint gas weighting events). @jeremyletang to add a proposal

We also need to review and update existing network parameters:
- Set the minimum an LP can submit to $10,000 (value TBC)
- Update the LP shapes param to be 5 each side (currently set to 100

The information in this spec will remain in git history should we wish to revisit in the future

**Comment by witgaw** [comment]
My bit done here: https://github.com/vegaprotocol/specs/pull/1390

**Comment by davidsiska-vega** [comment]
Many things are tested in other specs. 

In this one we should specifically have ACs about how many out of whatever total (and with what weight) saw the events on Ethereum before it gets accepted as "vega truth". 

So we still need the spec updated and the AC removed / added to reflect this.

**Comment by gordsport** [comment]
@ze97286 
FYI: If you are looking at the tendermint gas weighting for TXs per block. This is the spec we need to add it into
