### ISSUE TITLE
0044-LIME-lp_mechanics.md adjustments

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1382]
Id like to propose this AC is covered by extending the existing feature test rather than adding to system tests, we simply do not have enough time to deliver this and a feature adjustment would be much quicker/easier.

Check that bond slashing works with non-default asset decimals, market decimals, position decimals. This can be done by following a similar story to [bond slashing feature test](https://github.com/vegaprotocol/vega/blob/develop/core/integration/features/verified/liquidity-provision-bond-account.feature). Should test at least three different combinations, each decimal settings different to each other. ([0044-LIME-009](https://github.com/vegaprotocol/specs/blob/master/protocol/0044-LIME-lp_mechanics.md#0044-LIME-009))

**Comment by Jiajia-Cui** [comment]
@vega-paul Do you mean all the Acs in this spec? there are ACs such as change of network parameters which can not be tested in feature tests. 

I am happy to create feature tests to cover 0044-LIME-007 , 0044-LIME-008 and 0044-LIME-009

**Comment by vega-paul** [comment]
@Jiajia-Cui Can we add more feature tests to extend coverage for different precision.
If we do it in ST then we will have to write the e2e test from scratch.

**Comment by vega-paul** [comment]
Thanks @Jiajia-Cui !

**Comment by Jiajia-Cui** [comment]
> 

no problem :) will cover it in feature test
