### ISSUE TITLE
0044-LIME-lp_mechanics.md - 0044-LIME-002

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1383]
Id like to propose this one is moved to cosmic elevator is a review of the current feature test is acceptable.

The [bond slashing](https://github.com/vegaprotocol/vega/blob/develop/core/integration/features/verified/liquidity-provision-bond-account.feature) works as the feature test claims. ([0044-LIME-002](https://github.com/vegaprotocol/specs/blob/master/protocol/0044-LIME-lp_mechanics.md#0044-LIME-002)).

**Comment by davidsiska-vega** [comment]
I'm happy to have this tested only via a feature test. 

I don't see why I'd move the AC to cosmic elevator. Just consider it covered.
