### ISSUE TITLE
Double entry accounting is maintained at all points. ([0013-ACCT-001]

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1401]
Looking at this spec/AC
https://github.com/vegaprotocol/system-tests/issues/1034
Double entry accounting is maintained at all points. ([0013-ACCT-001](https://github.com/vegaprotocol/specs/blob/master/protocol/0013-ACCT-accounts.md#0013-ACCT-001))
Could we please have the scope of the above ‘points’ defined in the spec and also which account types are covered here?

**Comment by davidsiska-vega** [comment]
@vega-paul If we change the current wording to:

```
Double entry accounting is maintained at all points i.e. every transfer event has a source account and destination account and the balance of the source account before the transfer equals to the balance of source account minus the transfer amount after the transfer and balance of the destination account before the transfer plus the transfer amount equals to the balance of the destination account after the transfer. 
```

would that be sufficient? It's not so much accounts but transfers.

**Comment by vega-paul** [comment]
This works @davidsiska-vega 
I will raise a PR
