### ISSUE TITLE
Mempool priority and pruning based on economic value

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1439]
How does the protocol define what gets into a block and what does not?

- What can be designed ahead of the next Tendermint release (ABCI++)?
- Can anything be implemented before the Tendermnt relaese?

**Comment by gordsport** [comment]
Time based pruning of the mempool is required ASAP, and is covered in 🤠 issues:

- https://github.com/vegaprotocol/specs/issues/1639
- https://github.com/vegaprotocol/vega/issues/7969
