### ISSUE TITLE
0073-LIMN-limited_network_life.md - changes to reflect implementation

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1444]
Re following AC

The LP fees that were not distributed have been transferred to the Vega treasury for the asset. ([0073-LIMN-063](https://github.com/vegaprotocol/specs/blob/master/protocol/0073-LIMN-limited_network_life.md#0073-LIMN-063))

Its been confirmed that the undistributed LP Fees are distributed (into the network treasury) upon market settlement and therefore wont be available post network cp restart.

**Comment by davidsiska-vega** [comment]
The behaviour described in the AC 0073-LIMN-063 is the desirable one. 

See also this AC on LP fees:
```
- [ ] If a market has `market.liquidity.providers.fee.distributionTimeStep` set to more than `0` and such market settles then the fees are distributed as part of the settlement process, see [market lifecycle](./0043-MKTL-market_lifecycle.md). Any settled market has zero balances in all the LP fee accounts. (<a name="0042-LIQF-014" href="#0042-LIQF-014">0042-LIQF-014</a>)
```

**Comment by vega-paul** [comment]
ST Adjustment - nothing to do in specs
