### ISSUE TITLE
Test minimumTransferQuantumMultiple parameter

### ISSUE THREAD

**Issue by Vegaklaus** [vegaprotocol/specs#1451]
We want to set the minimum transfer limit for Vega-internal asset transfers relatively low (i.e., around $50). This means that an attacker with $1.000.000 to spend can create 20.000 Vega accounts with some funding on them and thus some market participation; especially, all these accounts can have positions in a market that cause Vega events when the market is moving, and thus act as a spam amplifier.

We have a number of countermeasures now to limit the effect, but haven't tested how well they work yet, so we should run a test that creates that amount of accounts as well as the corresponding market, and verifies that core and the datanodes can handle the corresponding event stream without breaking down.

**Comment by davidsiska-vega** [comment]
Minimum is set.
