### ISSUE TITLE
0073-LIMN-limited_network_life.md - Test case 5: Delegation (test with N=5, 10, 20000) (0073-LIMN-017)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1465]
This AC is not currently testable and I dont understand what we are trying to prove with this.

Can this test be rewritten with in mind...

System test framework housing the test and existing test setups.
Running test without 5 hours delays between delegations
Without the need to confirm rewards hourly
A simplified version with all the unnecessary setup and steps removed.

**Comment by davidsiska-vega** [comment]
@vega-paul I've had a look; I am not sure why it's untestable. It's testing delegations across LNL restart + validators removing own stake on ethereum side during the time the network is down for LNL restart. 

Feel free to reduce the time intervals to whatever is needed while maintaining the spirit of the AC.
