### ISSUE TITLE
Stranded withdrawal reissuing

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1502]
### Stranded withdrawal reissuing

Notes from the first meeting:

whilst updating the spec for this we need to consider:

- Keeping a list of all withdrawals until they are completed on Ethereum (keep state across snapshots / checkpoints?)
- Review any security issues etc….
 * How does this interact with core?
 * How does this work with the withdrawal delays?
 * Spam protection requirements?

Initial ideas / spec contents is being created in:

https://docs.google.com/document/d/1r-G59LKk1B2_JL-iND7suswLTPFO9cpom-852KPCMAU/edit?usp=sharing

**Comment by C0deMunk33** [comment]
this will be necessary for the migration from V1 to V2 of Multisig Control as well as moving forward on V2 as each time the signer set changes all outstanding withdrawals will be invalidated.

**Comment by gordsport** [comment]
closing as this is to be covered in 
- https://github.com/vegaprotocol/specs/issues/1503

Ive linked this issue in the above so not to lose track of the information
