### ISSUE TITLE
Create built in futures spec file

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#151]
In GitLab by @tamlyn10 on Oct 10, 2019, 11:27

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 11:27

assigned to @barnabee

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 24, 2019, 16:56

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Oct 24, 2019, 17:01

created merge request !28 to address this issue

**Comment by ashleyvega** [comment]
In GitLab by @davidsiska-vega on Oct 24, 2019, 17:01

mentioned in merge request !28

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 25, 2019, 16:54

assigned to @davidsiska-vega

**Comment by tamlyn10** [comment]
Reopening old issue

**Comment by tamlyn10** [comment]
No more progress made this week.

**Comment by candida-d** [comment]
@tamlyn10 @davidsiska-vega - What's the status on this spec? It's come up in a documentation ticket for market proposals. Considering market proposals is already far along, has this information actually been covered somewhere else?

**Comment by tamlyn10** [comment]
This is what will be covered in that outstanding "contract" work I keep talking about... ask me at the end of the week?

**Comment by candida-d** [comment]
Oh! Great, will do. I hadn't realised. :)

**Comment by tamlyn10** [comment]
See Slack post and create meeting to take engineering through this.
