### ISSUE TITLE
Re-work AC 0072-SPPW-011 as user should NOT be banned

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1522]
During QA testing of the spam acceptance criteria the following issue was raised as a bug:

- https://github.com/vegaprotocol/vega/issues/7322

During discussions it is understood that the behaviour of the protocol is how it should be, therefore we need to update the AC according to the discussions in the above core issue - @MuthuVega can then implement the correct test,

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/specs/pull/1521 .
