### ISSUE TITLE
Allow LPs to lock-up their liquidity commitments

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1533]
To be edited with more details:

We need to specify the functionality around the protocol allowing LPs to lock-up their liquidity commitments. Points to clarify:

- Does the locked liquidity lock to a single market, or should their be functionality to shift between markets but remain locked for the period specified?
- How long / what time periods does the locked liquidity remain locked for?

**Comment by davidsiska-vega** [comment]
This should now be  clear in 0044.
