### ISSUE TITLE
LP volume priority

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1551]
@witgaw observes: we always traverse the LP list in the same order. If the reference price doesn’t move that’s fine as whoever traded then gets their orders added to the end of the queue at a given price level, but if the reference moves same LP will always be the one to trade first (among the LPs).
Do we think it’s a problem? That guy likely has the highest virtual stake (relative to commitment) so maybe that’s fine? With great relative virtual stake comes great fill probability and all that.

@davidsiska-vega comment: Interesting. Possibilities:
deterministically randomize or
by submission time, earlier submitted LP orders get placed first, if stake is increased that places you at the end of the queue if stake is decreased you keep your place
sort by virtual stake
I would sort of prefer 1. Why? If we expect LPs to provide most volume through limit orders (where normal LOB queuing applies) then I think the LP deployed volume is something that most LPs don’t want to be hit. So in a deterministic queue they’ll try to get to the back.
Regarding 2. you may wish to put yourself at the back of the queue by increasing your commitment. Seems like a perverse incentive.
Regarding 3. Large virtual stake comes from two parts: large physical stake which is reflected in your volume already and the fact that you were early and “helped build the market volumes”. So I am not sure that there should be additional implicit responsibility of always taking the first hit on any incoming volume.

@witgaw:  it’s more of a fun-fact than big deal. Can also just wait till (if) some LP raises it and deal with it then - should be a 1 line change with minimal test impact.

@barnabee: this can wait, as you say. If an LP raises it we can do a simple randomisation or something, or if not then we can wait for liquidity sourcing and less active liquidity to build something interesting and well thought out and that exposes the right interfaces to let WASM get creative in future.

**Comment by barnabee** [comment]
A fun thing with WASM / liquidity sourcing might be to explore something unusual like placing all LP liquidity at a given price level in a single "virtual" order, always at the back of the time priority queue (one might want to have an "LP order" flag on absolute priced limits in this case, to allow posting orders with normal time priority). Doing this would allow a custom algorthim, for instance pro-rata by commitment size, to allocate the trade volume between LPs at the same price. It also seems neat to allow people who wanted to be hit to go first.

This actually chimes well with an optimisation I had already thought of and discussed with Jeremy as a possible enhancement in future where if there are multiple LP pegs with the same ref+offset you can put them in once virtual order to reduce the number of reprice calcs and order book ops.

**Comment by davidsiska-vega** [comment]
Superseded by SLA; no LP volume that's not a normal volume anymore.
