### ISSUE TITLE
Stabilising the slippage / closeout / liquidity component of the margin

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1567]
At the moment maintenance margin formula is:

```
m = closeout cost due to slippage + RFs times observables x size  
```

## Problem description

The first part is intended to take care of "liquidity risk" while the second is there to cover "market moves risk". The second part (market moves) was always properly supported by theory: RFs (risk factors) are chosen so that the RFs times observables matches the expected shortfall of the position https://vega.xyz/papers/margins-and-credit-risk.pdf . 

The liquidity risk part aka slippage part is more ad hoc. We simply look at current state of the book and see how much would the cost of closeout of the position be. This has at least two good properties:
1. it's connected to reality in the sense that it comes from the order book
1. it is non-linear; a large position may incur significantly more margin than a small position (in a nonlinear way). 

Unfortunately there are also bad properties:
1. it is unstable as the order book composition changes in real time; this is a UX issue making margin requirement hard to predict / reason about. 
1. there is no guarantee that the order book composition will be the same between the time margin is last updated and when we need to close a party out. 

## Possible solutions 

I would suggest that each of these become an option on new market proposals (or market change proposals) so that existing behaviour is kept; it may be the most appropriate in some markets. 

### Static liquidity risk charge based on a parametric formula 

The "liquidity risk" will be added onto the margin via the formula `liquidity_surcharge(pos_size) := A exp(B x pos_size)` where `A>=0` and `B>0` will be constants set during market creation / update. We don't necessarily need to go with an exponential; something like `liquidity_surcharge(pos_size) := A (1 + B x pos_size + B x B x pos_size x pos_size` would do (avoids the exponential). What it should be capturing is that large positions get super-linear penalty. 

### Dynamic liquidity risk charge based on a parametric formula 

As above but we'll run an algorithm which, at set intervals looks at the order book and does a least-squares-regression type update, Robins-Monro style for the position sizes seen on the market updating the parameters so that the  `liquidity_surcharge(pos_size)` approximately matches market conditions. 

### Other 

Feel free to edit or add other in comments 

## Difficulty estimate

It changes market proposals (few more fields), it changes market change proposals. It would slightly modify the margin calculation but if we retain the existing behaviour it isn't a major piece of work.

**Comment by barnabee** [comment]
This reminds me of my original design for how margin would work. The original plan was to do the same calcs (at least on the market risk side) that we do today but using some amount of recent market data, which would result in an ingerently unstable/dynamic margin calc, but to then fix the margin fraction of notional (and therefore notional) for a period of time (by adding appropriate "fat" to the value, prob. by adjusting tau).

The idea for this was that each market would then basically have a _margin/leverage "epoch"_ (probably with per market configurable length to allow markets to trade margin stability and capital efficiency) throughout which these data are known, can be displayed clearly in front ends, reasoned about, etc. At the end of each of these the margin factor (and implied max leverage) would change, but it'd change once per _epoch_ only and it would be possible throughout an epoch to calculate in real time what the next value was likely to be.

Obvoiusly we currently fix the params and don't need this on the market risk side, though it may be useful in the longer future for more sophisticated margining such as to respond to changing volatility better. 

Such a concept may also be useful IF we decide that a static charge is not sufficient.

If we can get away with a static charge for now though, we could perhaps introduce this kind of concept along with more modular (WASMy) risk models in general and have the concept work for both margin components together.

**Comment by witgaw** [comment]
A bit related: I'd propose charging everyone the max slippage on their riskiest long / short (so including orders) during auctions and using the order price as market observable. 

That would mean:
- higher margins on orders in auctions, but
- everyone who places orders in an auction is guaranteed to be able to afford their positions (if they end up trading) once the auction uncrosses and
- there's no need to recalculate the margin for a party after the order is placed.

**Comment by gordsport** [comment]
User research required but we should be aiming to do this in time to go with perps:

- https://github.com/vegaprotocol/specs/issues/868

**Comment by barnabee** [comment]
@davidsiska-vega is this still active or superseded? Is it something for prioritisation post Cosmic Elevator?

**Comment by davidsiska-vega** [comment]
Superseded by other developments.
