### ISSUE TITLE
Implement scenario-runner command line tool

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#157]
In GitLab by @witgaw on Oct 10, 2019, 22:14

`scenario-runner` is a command-line tool used for interacting with the instance of a Vega network. It can submit all the trading and collateral management-related instructions defined in the protocol. It interacts directly with the `trading-core` node running without the consensus layer for maximum performance and throughput.

The main functionality is:

* `SubmitInstructions`: Reads a set of instructions from the `InstructionsFile` and submits them to the `trading-core`.
* `ExtractData`: Extracts the trading data from the node subject to additional, user-defined filtering and outputs it as a `DataFile`.

**Comment by ashleyvega** [comment]
In GitLab by @witgaw on Oct 11, 2019, 12:47

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @witgaw on Oct 14, 2019, 15:52

marked this issue as related to #144

**Comment by ashleyvega** [comment]
In GitLab by @witgaw on Oct 14, 2019, 15:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @witgaw on Oct 14, 2019, 17:27

marked this issue as related to trading-core#485

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Nov 26, 2019, 14:32

changed title from **Implement scenario-runner{--cli-}** to **Implement scenario-runner{+ command line tool+}**

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Nov 26, 2019, 14:32

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Dec 10, 2019, 08:51

@witgaw and @pand-dev are working on improvements, but @witgaw is going to use the original SR to do testing of Nicenet - therefore I'm moving this to review. Please move it back if it is not ready for review, but I believe this is accurate based on the last call we had where we said we'd use it and iterate on any new features.

**Comment by edd** [comment]
See https://github.com/vegaprotocol/scenario-runner
