### ISSUE TITLE
Implement market data spec

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#160]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:32

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:34

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:36

marked this issue as related to #123

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 14, 2019, 10:29

mentioned in merge request !22

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 8, 2019, 14:20

removed milestone

**Comment by ashleyvega** [comment]
In GitLab by @EVODelavega on Nov 26, 2019, 13:27

marked this issue as related to trading-core#537

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Nov 26, 2019, 13:34

@tamlyn10 please can you link to specs and also acceptance criteria scope for nicenet :) thanks!

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Dec 10, 2019, 08:52

I believe that this was implemented by @jeremyletang

**Comment by edd** [comment]
This never got acceptance criteria. See #287 .
