### ISSUE TITLE
Add mark price parameters to market framework.

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#161]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:33

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:33

changed title from **{-Implement addition of-} mark price parameters to market framework.** to **{+Add+} mark price parameters to market framework.**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 11, 2019, 18:33

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 14, 2019, 10:29

mentioned in merge request !22

**Comment by tamlyn10** [comment]
I think this is outdated..
