### ISSUE TITLE
[Liquidation improvements] Completely decouple MTM, margin checks and closeout trades

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1641]
The current design around margins means that:
- closeout trades happen (or are attempted) when a party is in breach of margin requirement and when there is enough volume and when we're not in an auction. 
- we cannot handle (future) frequent batch auctions
- we may reward a party that has a big position (MTM move against them, we want to close out but can't, MTM move for them they're OK again - the network was at risk but party kept profit). 
- the logic in core is tightly coupled in places making moves towards WASM based smart products harder. 

The aim here is:
1. Separate margin checks, mark-to-market and closeout trades into three separate streams that can run at arbitrary frequencies, 
1. Accommodate closeout trades during auctions,
1. Avoid allowing parties with huge position breaching margin level hanging around. 
1. Do this without changing any existing margin calculations. 
1. Do this without changing how loss socialisation works. 

Roughly how: 
- The insurance pool will become "margin account" for a "network party" (think of the network party as a "bad bank"). 
- We will regularly check whether a party is distressed (but doesn't need to be tied to orders / trades etc. only at desired frequency e.g. every block or every 5s). If a party is in breach of margin level their margin is transferred to insurance pool and their position to the "network party". (*)
- We do mark-to-market as usual. If the network party has a position the insurance pool is used for MTM flows. If insurance pool is empty we loss socialise as before. 
- The network party (insurance pool party) will employ a simple heuristic (which later can be WASM but for now we hard code) according to which it will attempt, at a desired intensity, to reduce it's position. 

Insurance party position reduction heuristic:
- if we're in continuous trading place market orders once every desired number of seconds with size the smaller of "half available book volume", "half the position to close out" (unless the position is exactly `1` in which case close out all. 
- if we're in an auction place a limit order - more thinking needed about the size / price; e.g. we don't want to trigger price monitoring or move price too much. 

(*) An added benefit of this is that we may avoid a bunch of close-out trades - imagine network party is long `10` but now it is assigned a position of a party that was short `8`; its new position is `2` ... and a bunch of network trades didn't need to happen.

**Comment by witgaw** [comment]
Looks good to me. Maybe we could use limit orders in continuous trading too? Spread the volume across a few price levels (pegged orders) so that if a big aggressive order comes in the network gets rid of its volume at a relatively better price and earns maker fees, otherwise just keep updating and moving closer to mid, eventually use a market order or even a dedicated auction? I think that'd be obvious to all participants (not just with the detailed knowledge of the system who will know a market order will come at a specific time and may try to develop strategies for trading against it).

**Comment by davidsiska-vega** [comment]
@witgaw 

> Maybe we could use limit orders in continuous trading too? Spread the volume across a few price levels (pegged orders) so that if a big aggressive order comes in the network gets rid of its volume at a relatively better price and earns maker fees, otherwise just keep updating and moving closer to mid, eventually use a market order or even a dedicated auction? I think that'd be obvious to all participants (not just with the detailed knowledge of the system who will know a market order will come at a specific time and may try to develop strategies for trading against it).

Indeed, once we do the rest there may be many strategies for "optimal liquidation"; the hard part, when moving beyond crude heuristics, is to somehow calibrate the market parameters that will allow you to run this. But we can certainly discuss and implement few different liquidation strategies.
