### ISSUE TITLE
Collateral API - transfers and ledger entries

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#165]
In GitLab by @tamlyn10 on Oct 16, 2019, 16:05

This is the start of a discussion on what we might want to be able to expose via an API for the purposes of understanding the flows of collateral in the system. Like a block explorer, traders will want to interrogate the context, sequencing and amounts of transfers both via API and front end.

## Contexts

There are various contexts which prompt the transfer request instructions.  These are:

1. When someone deposits or withdraws from Vega collateral smart contract.
1. When someone places a new order and the system searches for collateral from their general account to cover this (if there is insufficient in their margin account).
1. During mark to market settlement when the system does a **request** from those who owe money into a market settlement account (this may include requesting _coverage_ capital from the insurance pool) and then a **distribute** to traders who are owed money. Sometimes the distributed amount will be less than the trader is owed (if insurance pool couldn't cover any losses).
1. When a trader closes out a position, they will have a mark to market settlement according to the price they exited at.
1. When a market expires and the final settlement occurs (which is just a special case of mark to market settlement)
1. When margin requirements are recalculated by the network and cause a trader's margin accounts to go into a "collateral search zone" or a "collateral release zone". This will potentially prompt transfers between a trader's general account and margin account.
1. During position resolution, there will be:
    - cancelling of orders and a new margin requirement calculation. This may put the trader into a different collateral zone.
    - potentially a close out mark to market settlement arising from the network transacting on the order book (this will be a flow of funds from the insurance pool to the counterparts - see Step 6 (position resolution)[./0012-position-resolution.md]
    - confiscation of all bankrupt trader's collateral into the insurance pool

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 16, 2019, 16:06

assigned to @tamlyn10, @barnabee, and @campbellssource

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 16, 2019, 16:20

changed the description

**Comment by barnabee** [comment]
The above scenarios will need to be reasonably visible to API (and eventually Console) users. 

@edd @jeremyletang @pand-dev can you comment on this in terms of:

1. How much of the above can be catered for now/once we have event bus?
1. How/where the concrete API requirements would be best captured?

**Comment by edd** [comment]
Related: https://github.com/vegaprotocol/vega/issues/2101
