### ISSUE TITLE
Add market initialisation phase to Market Framework

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#166]
In GitLab by @cdm on Oct 17, 2019, 10:42

When the core initialises a new market (market framework), certain dependencies need to be set up:

* The risk engine may need to calculate the initial risk margins
* An oracle may need some warm-up
* The trading core will continue to develop, making it likely we'll add some type of plugin system for optional/market-specific logic
* As yet unknown features might also require bootstrapping later on.

Currently, all markets start up with the same initial risk factors, for example. To address this, we need to agree on a way to declare a market "ready".

**Comment by ashleyvega** [comment]
In GitLab by @EVODelavega on Oct 17, 2019, 10:52

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Oct 17, 2019, 11:32

@tamlyn10 @barnabee this is the product/spec improvement for a Vega market - we need an initialisation phase that could be used for various things like waiting for an async risk model call to get initial factors or call out/wait for an oracle/maybe other uses!

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 6, 2019, 17:18

Thanks @cdm . Do you see this as necessary for Nicenet? In which case I will assign to that milestone and prioritise accordingly.

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Nov 7, 2019, 07:43

I can add this to Market Framework along with the acceptance criteria if needed? It should be quite quick.

**Comment by ashleyvega** [comment]
In GitLab by @jeremyletang on Nov 7, 2019, 07:45

I don't think we need to care about that. that will most likely be required once we are not in charge of deploying the nodes of the network so nodes can synchronize. In the meantime that's not something that is a problem now sow we can probably focus on this later.

**Comment by ashleyvega** [comment]
In GitLab by @cdm on Nov 7, 2019, 07:47

@tamlyn10 this is not necessary for nicenet, we can add it in to the trading-core code incrementally after we've reached nicenet-complete.

@barnabee please add to market framework specs if you'd like (happy to contrib) but it's out of scope for this milestone IMO

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 7, 2019, 13:10

marked this issue as related to #147

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 18, 2019, 12:51

changed title from **Add market initialisation phase** to **Add market initialisation phase{+ to Market Framework+}**

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 18, 2019, 12:51

assigned to @barnabee

**Comment by edd** [comment]
This should now be covered better by #200
