### ISSUE TITLE
RFC: Liquidity mechanism overhaul — replace forced volume with SLA

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#1665]
This is a request for comments, at an early stage, for consideration.

It would make quite a large change to the LP mechanics, but it would significantly simplify some things, namely:

- No more LP shapes, LP orders, or LP pegs
- LP mechanics become just a commit/uncommit transaction, plus liqudity monitoring and calculation of fees and rewards

### The problem:

* LPs aren't used to being forced to quote at all times and don't want to.
* This may lead either to fewer LPs and smalller commitments, or in fact not making commitments at all.
* This threatens the proper functioning of the liquidity incentivisation mechanism, with knock-on potential impacts to credit risk management (margin calcs).
* If the network is forced to operate with target stake multiplier set to zero, then this also opens the liquidity incentives up to a vampire/leech(?) attack by potentially any trader, diverting rewards that ought to be received by a real LP who may spend say >95% of the time providing liqudiity towards far more fickle traders.

### Historical context

The liquidation system, and therefore a significant part of credit risk management (particularly given that in a pseudonymous, decentralised system, the assumed recovery rate if a party owes more in cashflows during MTM or final settlement is zero), relies on there being sufficient liquidity to close out distressed or delinquent positions against other traders. The financial scale of the risk is also dependent on the expected slippage during closeout.

As a result of this, early designs aimed to ensure that a market with non-distressed committed (via on-chain transaction and bond) LPs would always remain operational with a minimum level of liquidity available.

This proved impractical for a number of reasons and was always incompatible with price monitoring ("circuit breakers") so it was never a hard requirement of the overall system design. However, the liquidity mechanism retained features related to this idea, in the form of the forced deployment of LP pegged orders.

On reflection this was a poor design decision, given that markets can be suspended (in auction) for a number of reasons in any case and we are comfortable with this.

This ticket aims to set out a path forward.

### Proposed solution overview

At a high level, the solution to this would be to replace the system that forces LPs to be on the book all the time with one that:
1. Requires LPs to meet an SLA (i.e. % of time spent providing liquidity within some range) to be rewarded, ensuring LP remains a defined and useful role.
2. Rewards LPs more for better performance against the SLA (already done for price, this would add similar for time spent providing liquidity), ensuring there is an incentive to do more than the bare minimum if market conditions allow.
3. Penalises LPs that commit and do not meet the SLA, to reduce the attractiveness of opportunism/leeching style attacks.

A side effect of this change will be to remove the LP "shape" from LP commitments, as LPs will now only place normal orders, pegged or otherwise. In order to allow LPs to remain on the book after trading with greater certainty while limiting the amount that might trade in any one transaction, the forced refresh of the orders implied by the LP "shape" will be replaced by an optional iceberg feature available on all persistent order types, including pegged persistent orders.

Another side effect is that LPs can effectively suspend a market by withdrawing their orders. They can sometimes do this anyway if there are no other priced orders, so I don't see that as a big deal.

### Proposed solution detail

This is a high level summary of a possible approach, primarily intended to be complete enough to generate useful discussion about a quite considerably 

#### SLA

- [x] New market parameter: SLA (decimal) = minimum fraction of time LPs must spend "on the book" providing their committed liquidity.
- [x] New market parameter: SLA evaluation period length = number of past epochs used to identify worst SLA performance. The reason for this is so that payouts can be made regularly and a bad performance concentrated on a single day can be penalised, but so that performance penalties are not so short lived as to be shrugged off. This may be expected to be 7 or even 30 or more epochs.
- [x] New market parameter: SLA  competition factor, determines how much of their accrued rewards an LP only just achieveing the SLA receives. If this is set to 1 there is no penalty for achieving the SLA but being on the book less than other LPs in practive, if this is set to 0 the LP will receive nothing if they only just achieve the SLA.
- [x] The SLA (and therefore payment of LP rewards) are calculated and applied per epoch. Performance for an LP can be counted during an epoch by a counter of nanoseconds spent on the book meeting the SLA for each LP (we'd need to record the Vega time when they start meeting the SLA [again] or nothing if they aren't meeting it, so when they stop meeting it, the counter can be incremented).
- [x] LPs take a haircut on LP rewards/revenue for each epoch equal to the worst of their downtime penalty for the current epoch and their moving average downtime downtime penalty over the last N epochs where N is the "SLA evaluation period length" parameter. 
- [x] The downtime penalty is 100% if they are below the SLA level, or between zero and `1 - market.liqudity.slaCompetitionFactor` if they achieve 100% performance or the minimum required by the SLA, respectively.
- Example superceded by changes, refer to spec. for more detail. ~So if the SLA is 0.8 (80%, 20% downtime is allowed), and the period length is 7 (NB: this SLA is probably much more generous than would be used in reality, where something like 0.98 or higher may be more reasonable):~
    - ~For an LP that quoted 85% of the time (15% downtime) 6 epochs ago, and 98% of the time in all other epochs, their rewards are scaled by `1-(0.15/0.2) = 0.25` (i.e. a quarter).~
    - ~In 2 epochs time, once the 85% falls outside the period length (7 in this case), if the LP has consistently quoted >=98% of the time in the prior 7 epochs, then their rewards would start to be scaled by `1-(0.02/0.2)=0.9`.~
- [x] Once an LP hits or goes below the worst allowable performance under the SLA, they get a 100% penalty on accrued rewards, i.e. no rewards for that epoch and 100% penalty applied to the moving average for that epoch while it remains within the evaluation period.

#### Committing liquidity

- [x] LPs would commit liquidity as they do now, but without providing any LP "shape" / pegged orders.
- [x] LPs can now always cancel their commitment entirely but will lose their entire bond if they do so when then the target stake is not met. If they reduce their commitment when target stake is not met, they lose a pro-rata amount of their bond based on the amount by which they reduced their commitment.
- [x] If an LP's bond goes below the level implied by their committment (this can only happen in a way thay implies the LP has paid a penalty) then the LP's commitment is reduced pro-rata (and their ELS is reduced, as normal).

#### Providing liquiditing

- [x] Remove LP "shape" and automated, forced deployment of LP pegged orders. LPs are no longer forced to automatically quote all the time. 
- [x] LPs now always and only provide liquidity using normal order types available to all traders. They have full access to features like "post only" and can be "off" the book  _at any time_ simply by cancelling all their orders.
- [x] Add an optional `display quantity` to persistent orders (must be <= order quantity/size). If this is smaller than the full order size then the order is an iceberg order and is effectively split into a series of orders of quantity = display quantity, with only . This will be specced fully if the proposal moves forward.
- [x] Rewards are calculated the same way as before, except for the additional application of the SLA derived penalty to the LPs' relative reward shares.

#### Liquidity monitoring

- [x] LM is still triggered when commitment drops below the trigger ratio and exited when target stake is reached or exceeded.
- [x] Auctions are no longer triggered if there are no priced orders on the book.
- [x] Auctions are not triggered if LPs are off the book so there's less liquidity than committed or less liquidity than required by target stake or the triggering ratio.
- [x] Low supplied liqudiity situations (i.e. 2, 3 above) are assumed not to need to directly trigger an auction because if the lack of liquidity is an issue it should trigger a price monitoring auction on a well configured market.

### Open questions:

- [x] 1. Can we reuse proof-of-stake epochs for this or is there any reason for a separately defined LP epoch? (I can't think of one, I think the same epochs for both is probably fine.) **Yes we can.**
- [x] 2. Should both the SLA and SLA period be market parameters? **Yes.**
- [x] 3. Can we really do without ad-hoc liquidity auctions and rely on price monitoring? **Yes.**
- [x] 5. Is a linear haircut based on time_off_book as a fraction of max allowed time off book under the SLA the right penaltly. This could be non-linear or calculated some other way. **Linear is ok. We have seperated penalty forfeit of rewards and penalty confiscaiton of bond as two distinct concepts in the spec.**
- [x] 7. Is it right to have a max penalty per epoch of the contents of your bond account. **Yes.**
- [x] 8. Is it right to allow LPs to always reduce their commitment? I think maybe this is ok because you lose accured LP share that you've built up by doing so anyway. **Yes this is ok. Key goal is to make sure LPs always have an out with a known max. cost (their bond).**
- [x] 9. Do we still want ghost pegs or similar, or would we just expect LPs to use iceberg non-pegged limits? **We don't need ghost pegs now, yay!**
- [ ] 10. Is there a way to unify some or all of this model with liquidity mechanics for spot. **Yes, this can [mostly?] be the liquidity mechanism for spot.** TODO: make sure it applies fully.
- [ ] 11. Is this even a good way to solve the problem? What alternatives exist? 
- [x] 12. [added 20/04] In response to a good question by @Jiajia-Cui: should we treat an LP failing to meet their SLA either somewhat or even exactly like exiting their commitment for that time? So they could lose all or part of any accrued increase in ELS over the baseline if they had made the same commitment now. **We reduce the LP's commitment if their bond is depleted and not refilled now, and will apply bond penalties in some scenarios, but we wont reduce their commitment just for SLA failure.**

Comments and discussion are welcome, including from the wider community, especially market makers and LPs who have integrated with the protocol to date (we will also happilty accept feedback via private channels if preferred).

**Comment by EVODelavega** [comment]
> LPs can now always cancel their commitment entirely but will lose their entire bond if they do so when then the target stake is not met. If they reduce their commitment when target stake is not met, they lose a pro-rata amount of their bond based on the amount by which they reduced their commitment.

I'm wondering how this will work in practice. Say a party has a commitment of 1k, they also have an open position and have been losing to the point where they're close to the maintenance level. They've essentially been burning through their bond balance to maintain their position. If they reduce their commitment amount, which was 1k, but the actual current balance in their bond account is zero, there isn't anything they can lose. If we were to take the pro-rata amount from their margin balance, they'd end up distressed, the next MTM settlement, it's likely we'd enter loss socialisation - and any penalties that were taken (presumably transferred in to the insurance pool) will be used to make up the losses of other parties in the market.

A slightly smarter LP would close their position out first (market order sell/buy). The released margin balance will be used to top up their bond account, but from their initial 1k commitment, the new balance could end being something like 200. If they reduce their commitment by 500, there's insufficient balance to pay the penalty. The bond balance (along with general and margin) will hit zero, at which point the LP should really be cancelled.

A third option for an LP running low on funds, then, could be to place orders - and bond slashing penalties to drain their bond account to meet the margin requirements, cancel their LP entirely. We can't confiscate the bond amount, because it's tied up in margin. Once their LP has been cancelled at no cost, they can cancel the orders that locked up the remaining balance in margin, and have it released to their general account.

Another more labour intensive way someone could go about avoiding penalties could be decreasing their commitment amount in small increments (or decrements), perhaps placing an order to dip in to their bond balance, decrease the commitment amount, cancel the order, and use the released funds to trade or commit liquidity on another market. 

These were just a couple of questions I had, and ways I could think of that could be used to effectively avoid being penalised to the full extent based when I read this, which makes me think that there's someone out there who will come up with a way to avoid being penalised all together.

**Comment by barnabee** [comment]
Some good points there, I don't think any catastrophic issues but some important edge cases we'd need to design for:

> I'm wondering how this will work in practice. Say a party has a commitment of 1k, they also have an open position and have been losing to the point where they're close to the maintenance level. They've essentially been burning through their bond balance to maintain their position. If they reduce their commitment amount, which was 1k, but the actual current balance in their bond account is zero, there isn't anything they can lose. If we were to take the pro-rata amount from their margin balance, they'd end up distressed, the next MTM settlement, it's likely we'd enter loss socialisation - and any penalties that were taken (presumably transferred in to the insurance pool) will be used to make up the losses of other parties in the market.

This is just what we have today, no? If you lose all your money you can exit your commitment avoiding some or all penalties. I don't think it allows exfiltrating funds from the market, but perhaps I am missing something?


> A slightly smarter LP would close their position out first (market order sell/buy). The released margin balance will be used to top up their bond account, but from their initial 1k commitment, the new balance could end being something like 200. If they reduce their commitment by 500, there's insufficient balance to pay the penalty. The bond balance (along with general and margin) will hit zero, at which point the LP should really be cancelled.

If they have no money and a commitment of 500 after the reduction then under what I described above they will not hit the SLA, won't hit fees, and will continue being penalised (but losing nothing). Even if they start providing liquidity again they'd get no fees for the SLA evaluation period (so days or weeks) and would probably just decide to start providing liquidity again under a different pubkey unless they had a v. high ELS.

So in some sense I don't think it is a big problem, however:

1. We could, and probably should accrue owed penalties (NB: we can't do this by letting bond account go negative as that would create a loan to other parties within Vega) so someone who wants to keep their earned ELS properly pays the cost of their failures. (NB: open question 10 means we may also decide to eat away at their ELS if they breach SLA, too).
2. It does sort of make sense to me to cancel your commitment if your bond hits zero. It's cleaner. In fact maybe the answer is to always reduce your commitment to the comitment implied by your bond accounts (after it's been topped up from general and general is at zero). So if your commitment implies a 50k bond and you only have 30k left outside margin, so your bond account contains 30k, your commitment could get adjusted down to the commitment implied by 30k bond. The nice thing about this is you lose some of your accrued ELS this way so you'd have an incentive to keep your bond account in good standing.


> A third option for an LP running low on funds, then, could be to place orders - and bond slashing penalties to drain their bond account to meet the margin requirements, cancel their LP entirely. We can't confiscate the bond amount, because it's tied up in margin. Once their LP has been cancelled at no cost, they can cancel the orders that locked up the remaining balance in margin, and have it released to their general account.

This is probably the worst issue because it needs to be impossible to exfiltrate funds to your general account when you owe MTM losses, fees, or penalties. I think that the proposal above to keep a running tab of owed penalties would solved this, on the asumption that funds are never transferred to general or bond when penalties are owed.

**Comment by EVODelavega** [comment]
> This is just what we have today, no? If you lose all your money you can exit your commitment avoiding some or all penalties. I don't think it allows exfiltrating funds from the market, but perhaps I am missing something?

It sort of is, but this proposal would allow you to update (ie decrease or cancel) your commitment even if the provided stake is below the target stake. Currently we don't allow this. This proposal does allow for LP's to reduce their commitment, at the cost of a new penalty. If the LP has an open position, or placed a bunch of orders, though, they could just find themselves in a situation where this new penalty doesn't apply, and they can just reduce/close their commitment, without issues. The only difference between what we currently have, and this proposal (in the first scenario I described) would be that they're able to reduce their commitment even if supplied stake < target stake, without any repercussions.

> So if your commitment implies a 50k bond and you only have 30k left outside margin, so your bond account contains 30k, your commitment could get adjusted down to the commitment implied by 30k bond. The nice thing about this is you lose some of your accrued ELS this way so you'd have an incentive to keep your bond account in good standing.

That makes sense, and at first glance this might be something we could already do with ELS as it stands currently (update the virtual stake any time the bond account balance is updated, rather than when the actual liquidity provision is updated). I'm assuming we'd update the ELS the same way we currently do, but have it depend on the bond balance rather than the commitment amount, so if MTM settlement or fees top up the bond balance, we adjust the ELS accordingly.

> This is probably the worst issue because it needs to be impossible to exfiltrate funds to your general account when you owe MTM losses, fees, or penalties. I think that the proposal above to keep a running tab of owed penalties would solved this, on the asumption that funds are never transferred to general or bond when penalties are owed.

I expected this to be the case - keeping track of penalties/balances owed is possible, but this state would have to be added to checkpoints, which is potentially quite a lot of state. When restoring from a checkpoint, we'd essentially try to settle all the outstanding fees/penalties, before restoring the markets. The question then becomes: what do we do when the market settles, and some parties still owe balance? It'd be rather hard to figure out who owes what to whom, if we include MTM shortfall. This would essentially be the amount owed to the insurance pool by certain parties. In case of the latter, I'm assuming we just close the account?

**Comment by barnabee** [comment]
Another thought/question: should the SLA be set by the market or as part of the commitment. If the latter we'd scale rewards by the level of commitment made (assuming it's met) as well as the actual time spent on the book.

Advantage of this is you don't need to maintain an SLA by governance. Disadvantages are that without competition LPs may set low SLAs (potentially could have a min. SLA network param too) and that it's not clear how relative SLAs chosen by LPs should scale rewards.

**Comment by barnabee** [comment]
> > This is just what we have today, no? If you lose all your money you can exit your commitment avoiding some or all penalties. I don't think it allows exfiltrating funds from the market, but perhaps I am missing something?
> 
> It sort of is, but this proposal would allow you to update (ie decrease or cancel) your commitment even if the provided stake is below the target stake. Currently we don't allow this. This proposal does allow for LP's to reduce their commitment, at the cost of a new penalty. If the LP has an open position, or placed a bunch of orders, though, they could just find themselves in a situation where this new penalty doesn't apply, and they can just reduce/close their commitment, without issues. The only difference between what we currently have, and this proposal (in the first scenario I described) would be that they're able to reduce their commitment even if supplied stake < target stake, without any repercussions.

I think this is solved by the addition since the first iteration of this ticket of the deciisons/clarification that noew if your bond drops below your commitment level (which also means you have already paid a penalty) your commitment and your ELS are reduced, too. 

The repercussions are the penalties that are already applied if you are forcibly reduced because you're out of money, and the penalty described in the ticket if you choose to reduce. I think that covers it all, now?

> > So if your commitment implies a 50k bond and you only have 30k left outside margin, so your bond account contains 30k, your commitment could get adjusted down to the commitment implied by 30k bond. The nice thing about this is you lose some of your accrued ELS this way so you'd have an incentive to keep your bond account in good standing.
> 
> That makes sense, and at first glance this might be something we could already do with ELS as it stands currently (update the virtual stake any time the bond account balance is updated, rather than when the actual liquidity provision is updated). I'm assuming we'd update the ELS the same way we currently do, but have it depend on the bond balance rather than the commitment amount, so if MTM settlement or fees top up the bond balance, we adjust the ELS accordingly.

Yeah. We'd keep the commitment amount and bond account in sync. We are basically doing away with anything that forces someone to remain because it's not popular (understatement!) and doesn't work anyway.

> > This is probably the worst issue because it needs to be impossible to exfiltrate funds to your general account when you owe MTM losses, fees, or penalties. I think that the proposal above to keep a running tab of owed penalties would solved this, on the asumption that funds are never transferred to general or bond when penalties are owed.
> 
> I expected this to be the case - keeping track of penalties/balances owed is possible, but this state would have to be added to checkpoints, which is potentially quite a lot of state. When restoring from a checkpoint, we'd essentially try to settle all the outstanding fees/penalties, before restoring the markets. The question then becomes: what do we do when the market settles, and some parties still owe balance? It'd be rather hard to figure out who owes what to whom, if we include MTM shortfall. This would essentially be the amount owed to the insurance pool by certain parties. In case of the latter, I'm assuming we just close the account?

I think with the above updates, reducing down the commitment with the bond (and that implying penalties paid already) this is no longer an issue?

**Comment by barnabee** [comment]
> Another thought/question: should the SLA be set by the market or as part of the commitment. If the latter we'd scale rewards by the level of commitment made (assuming it's met) as well as the actual time spent on the book.
> 
> Advantage of this is you don't need to maintain an SLA by governance. Disadvantages are that without competition LPs may set low SLAs (potentially could have a min. SLA network param too) and that it's not clear how relative SLAs chosen by LPs should scale rewards.

Nice idea but doesn't add much so we won't do it. Market already sets a minimum time on the book SLA, but the proposed design also rewards doing better than the SLA and is (much) easier to understand.

**Comment by davidsiska-vega** [comment]
Anyone wishing to further comment here: We're now at the stage where the draft PR has almost everything so comments are arguably more welcome there than on the issue here (but of course depends on the nature of comment anyone wishes to make).
