### ISSUE TITLE
stop orders

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1666]
### Issue

We need to introduce stop order types, this issue is to specify update [0014-ORDT-order_types.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0014-ORDT-order_types.md) and other specs? to add the new order type

How do we know when we are done:

 The spec has been updated to indicate the requirements
 The specification contains acceptance criteria with IDs that reflect the scope of the work required
 The engineering team has reviewed the specifications and understand the scope
 The spec is merged into the specs repo before engineering start development/test work

**Comment by barnabee** [comment]
Pedantry for info: likely stops will be a trigger that can be added to any valid order submission, rather than a new order type. We will also be likely to consider trailing stops though they are a little more complex and may not make it into the first iteration of this.
