### ISSUE TITLE
predictive margins

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#169]
In GitLab by @tamlyn10 on Nov 8, 2019, 14:36

**Comment by barnabee** [comment]
@tamlyn10 do you remember the context for this? If so some more detail might be helpful or could close if you can't remember either and don't think it's needed?

**Comment by tamlyn10** [comment]
mmm.. this may have been about sharding or may have been about dampening margin vol. Either way, I'll close this as if it was a good idea it will pop up in the research margin review.

**Comment by barnabee** [comment]
Predictive sounds cool tho

**Comment by tamlyn10** [comment]
so cool.. i think it came from you - during your  "everything should be predicted" phase ;-)

**Comment by barnabee** [comment]
lol everything _should_ be predicted!
