### ISSUE TITLE
Investigate and potentially spec volume-reduction uncrossing periods in Liquidity Auctions

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/specs#1691]
At present, when a market enters a liquidity auction it will remain in said auction until additional stake is committed to bring it back above the target stake. This does however mean that even if some trades could be crossed and result in an overall reduction in open interest on the market they will not be. This problem will be exacerbated by #1685 which allows LPs to withdraw their stake (with a penalty) even if this would bring the committed stake on the market below the target stake, potentially leaving those holding a position on the market unable to close positions. 

To alleviate this, we should investigate the possibility of adding points in time during a liquidity auction where the protocol will attempt to uncross trades which would reduce the overall open interest, whilst remaining in an auction afterwards. This would have the effect of allowing those with positions on the market an opportunity to reduce/exit whilst also making it easier for the market to move back out of auction by reducing the required committed stake.

**Comment by davidsiska-vega** [comment]
Should be considered in view of the other option which is to ditch liquidity auctions completely if we re-work liquidations a bit: https://github.com/vegaprotocol/specs/issues/1641
