### ISSUE TITLE
All things oracles

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#177]
In GitLab by @tamlyn10 on Nov 27, 2019, 17:53

Let's discuss oracle requirements and make any key decisions in this ticket.

Output of this ticket will be another spec-writing-task to write the Oracle spec.

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 27, 2019, 17:53

assigned to @C0deMunk33 and @jeremyletang

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Nov 27, 2019, 17:55

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Nov 27, 2019, 17:57

One meta topic for discussion: I suggest dropping the term oracles in the protocol. It's quite contentious and leads to discussions about the 'oracle problem'. I've been using 'external data sourcing' lately… thoughts?

**Comment by ashleyvega** [comment]
In GitLab by @C0deMunk33 on Nov 27, 2019, 18:02

"external data sourcing" is great for the general discussion because 'oracle' has a specific meaning in the ETH world. From my perspective, the message queue will process the external data and present it to consensus (just like it does for the bridges). 

That being said, what are the categories of external data that consensus cares about?

**Comment by ashleyvega** [comment]
In GitLab by @C0deMunk33 on Dec 4, 2019, 15:52

For event queue and external assets, I've started a smart contract called Vega_Bridge_Oracle_Controlled_Asset which is a simple bridge that implements IVega_Bridge (as defined here: https://gitlab.com/vega-protocol/external_blockchain_manager/blob/master/event_queue/readme.md) that is directly controllable by a traditional oracle. This solves the Deposit/withdraw assets aspect of oracles and defers pricing and settings changes for a separate process, which needs to be defined.

So far, for external data sourcing, we need:
external asset pricing
external settings changes (oracle voting)
?

We need to expand that list to cover all the external data sourcing needs.

**Comment by barnabee** [comment]
> In GitLab by @C0deMunk33 on Nov 27, 2019, 18:02
> 
> "external data sourcing" is great for the general discussion because 'oracle' has a specific meaning in the ETH world. From my perspective, the message queue will process the external data and present it to consensus (just like it does for the bridges).
> 
> That being said, what are the categories of external data that consensus cares about?

We care about:
- external data that may be ingested from time-to-time (for Futures, only at expiry) by products
- external data that may feed into the mark price algorithm (currently not implemented, the only mark price algo. for now is last traded price)
- external data that notifies Vega about a deposit of an asset to a public key (this can come from another chain such as Ethereum locked up in a smart contract OR notify the network about a balance deposit for a "native" Vega asset or 'oracle controlled asset')
- calibration data for risk models

**Comment by barnabee** [comment]
I've added my notes on this here in a new WIP branch: https://github.com/vegaprotocol/product/blob/data-sourcing/specs/0000-data-sourcing.md

**Comment by barnabee** [comment]
Closing as discussion now in PR above ☝️
