### ISSUE TITLE
Auth spec

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#182]
In GitLab by @tamlyn10 on Dec 11, 2019, 17:56

Task to write authentication spec

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Dec 11, 2019, 17:58

marked this issue as related to #124

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Dec 11, 2019, 17:59

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Dec 11, 2019, 18:00

assigned to @jeremyletang

**Comment by ashleyvega** [comment]
In GitLab by @jeremyletang on Dec 12, 2019, 11:54

mentioned in merge request !36

**Comment by edd** [comment]
#111
