### ISSUE TITLE
Add links to wallet implementations for reference into appropriate specs...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#1856]
... so that someone who needs to implement their own signing / pow has somewhere to look

**Comment by gordsport** [comment]
I think the non-protocol spec for CLIE could with a short summary link to the specs in the browser wallet repo too:

- https://github.com/vegaprotocol/vegawallet-browser/tree/main/specs

At this time the [CLI wallet](https://github.com/vegaprotocol/vega/tree/develop/wallet) only has the code and no readme info to link to
