### ISSUE TITLE
0044-LIME-067 formatting

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1919]
Cannot copy paste this text

  - When LP decreases its commitment so that $\text{commitment-variation}_i <= \text{maximum-penalty-free-reduction-amount}_i$, then the entire amount by which they decreased their commitment is transferred to their general account, their ELS got updated as per the [ELS calculation](0042-LIQF-setting_fees_and_rewarding_lps.md)(<a name="0044-LIME-065" href="#0044-LIME-065">0044-LIME-065</a>) for spot (<a name="0044-LIME-066" href="#0044-LIME-066">0044-LIME-066</a>)
  - When LP decreases its commitment so that $\text{commitment-variation}_i > \text{maximum-penalty-free-reduction-amount}_i$ , $(1-\text{market.liquidity.earlyExitPenalty}) \cdot \text{penalty-incurring-reduction-amount}_i$ should be transferred into its general account and $\text{market.liquidity.earlyExitPenalty} \cdot  \text{penalty-incurring-reduction-amount}_i$ should be transferred into market insurance pool (<a name="0044-LIME-067" href="#0044-LIME-067">0044-LIME-067</a>) for spot $\text{market.liquidity.earlyExitPenalty} \cdot  \text{penalty-incurring-reduction-amount}_i$ should be transferred into the network treasury for the asset (<a name="0044-LIME-068" href="#0044-LIME-068">0044-LIME-068</a>)
  -

**Comment by davidsiska-vega** [comment]
I can copy and paste. Text is text. 

```
- When LP decreases its commitment so that $\text{commitment-variation}_i <= \text{maximum-penalty-free-reduction-amount}_i$, then the entire amount by which they decreased their commitment is transferred to their general account, their ELS got updated as per the [ELS calculation](0042-LIQF-setting_fees_and_rewarding_lps.md)(<a name="0044-LIME-065" href="#0044-LIME-065">0044-LIME-065</a>). For spot (<a name="0044-LIME-066" href="#0044-LIME-066">0044-LIME-066</a>)
```
