### ISSUE TITLE
Market Framework spec: Contract Size field mentioned but not implemented

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#192]
In GitLab by @edd on Jan 8, 2020, 13:08

The Market Framework spec mentions Contract Size as a product parameter:
https://gitlab.com/vega-protocol/product/blob/master/specs/0001-market-framework.md#L103

The current implementation of a `Future` in https://gitlab.com/vega-protocol/trading-core/ does not contain a Contract Size field.

https://gitlab.com/vega-protocol/trading-core/blob/develop/proto/markets.proto#L20-26

Please could we use this issue to define how we expect to populate that field, then I will create the appropriate trading core issue and update the spec as required

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 8, 2020, 13:10

I expect this is just a new UINT64 field on the `future` type, but what is an appropriate default for our 3 existing markets?

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 8, 2020, 15:32

created merge request !41 to address this issue

**Comment by ashleyvega** [comment]
In GitLab by @edd on Jan 8, 2020, 15:32

mentioned in merge request !41

**Comment by ashleyvega** [comment]
In GitLab by @campbellssource on Jan 15, 2020, 11:32

I'll hazard a guess that a 'contract size' field tells you how much of the settlement asset(s) a single contract is worth.
So for GBPUSD/DEC20. 'ContractSize = 000001' would mean that a contract is equal to a fraction of a cent '0.00001`

**But how much should a contract be worth?**

In Retail CFD land there is often a Mini and normal contract. a normal contract on the FTSE100 would be worth the equivalent of £10 a point move. mini's (£1) were introduced for smaller traders. Some platforms allow you to input a notional value and the system then converts this into the appropriate number of contracts.

It might be good for us to make a contract worth the smallest unit we deal in of a settlement currency (currently happens to be 5 Decimal Places) as this avoids any question of rounding on settlement. ie. how to turn the fractions of a SyntheticUSD you are margined in into an amount of dollars that can only handle 2 DP.

but I'll leave that to @barnabee @tamlyn10 @davidsiska-vega an co.

- - - 

Edd sent me this as an example, see the contract size: https://www.deribit.com/pages/docs/futures 

And here is how I imagine using it in the UI.

![image](/uploads/303e339afa739ed604ced36aaa5f8640/image.png)

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jan 22, 2020, 16:11

OK, just had a call with @barnabee about it cos my head was getting all weird while thinking about currency conversions.

So firstly, there must already be an assumption in the core of the contract size (or it couldn't do MTM settlement, for example) and those values are for **1 x unit of the base asset**, as far as I know.

ETH/BTC: minimum-contract-size = 1 ETH
ETH/USD: minimum-contract-size = 1 ETH
GBP/USD: minimum-contract-size = 1 GBP

Could we confirm this with core (@cdm)? It would be good to make sure this is explicitly set as per market framework.

Example:

* I enter 1 long contract (size = 1 GBP) of GBPUSDJUN20 at price = 1.30695
* Notional value = 1.30695 USD / 1 GBP
* Margin (assume ~ 10%) = **.130695 USD** / .1 GBP (Note, we are holding .130695 VUSD in the margin account)
* For a 1 pip move (when price increases to 1.30705), my MTM / P&L = (1.30700 -  1.30699) * contract_size = 0.00001
* For a 1 point move (i.e. price moves to 2.30695), my MTM / P&L is = (2.30699 - 1.30699) * contract_size = 1.00000

This is using pips and points terminology from futures markets not CFD markets (IG's point is the 4th decimal place I think). Note, I'm not super familiar with generic currency futures so perhaps they all follow IG's naming convention. 

@barnabee @davidsiska-vega is this correct?


2. Michael in your above screenshot for the notional,  you have put the size in terms of BTC (the quote currency). Of course, the BTC and USD are interchangeable (via the price, which is BTC/USD) and I've seen some platforms offer the user the choice of interchanging.

3. In terms of displaying minimum contract size, we think it makes sense to do that in the market details?

4. @campbellssource I take your point about rounding, however given it's "VUSD" we're working in,  this would only become a problem when in our case that's a problem for whomever would "trade in" the VUSD for fiat? 

Please feel free to challenge on any of these. I'm feeling particularly vague today - jetlag has taken it's toll.

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Jan 22, 2020, 16:45

Important to note that what we have is a *Futures* product not a *CFD* product so concepts like £ per point are not relevant. In general for futures you would be buying some number *n* of "BASE" at a price of price of *p* "QUOTE" per BASE thing, i.e. buying USD 100,000 at a price of GBP 0.87 per USD. There may be a minimum contract size (aka 'lot' size), say USD 50,000 in which case you can only buy in multiples of that size, and it's equally valid to say I'm buying USD 100k or 2 contracts/lots.

In Vega initially, contract size = 1 of the base asset so both are equal and the UI we have seems ok for now. In future we will want to support markts with other lot sizes, both smaller (e.g. 0.1 BTC) or larger (5k USD) and then we might like the deal ticket for futures to have multiple ways to enter size (num contracts or value in base asset, for instance). As Tamlyn says this should be supported in the market framework.

Quite possibly, our second product could be CFDs which are almost exactly the same product from a code/risk perspective but are specified and traded in terms of £ per point. Use of this product type would be a hint to clients as to how to display UIs such as a deal ticket.

Regarding rounding, it definitely would be a poorly specified market that allowed more precision in the contract size than the relevant settlement asset (though the other way around seems like it should be fine as long as the two are divisible), so perhaps we can include validation that an instrument's specification makes sense for the settlement asset...

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Jan 22, 2020, 16:58

This all seems right but my brain is also fried at this point thinking about contracts and notional and [un]realised P&L so :shrug:

**Comment by campbellssource** [comment]
I think this is going to be sorted with https://github.com/vegaprotocol/vega/issues/2372
