### ISSUE TITLE
Should close out market order be FOK or IOC

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#194]
In GitLab by @barnabee on Jan 14, 2020, 11:16

Currently this is FOK and we were not sure whether it should be IOC.

IOC would get more volume, BUT I think FOK is probably the right answer as we would actually want to trigger a low liquidity auction / suspension rather than part filling the closeout, and an FOK would provide this without needing to explicitly detect it in the code.

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jan 19, 2020, 07:39

@barnabee when creating a new ticket please label as "analysis", "spec-writing" or "implement" otherwise I lose it! Just found this again and labelling as "analysis".

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Jan 19, 2020, 21:42

changed the description

**Comment by barnabee** [comment]
I am comfortable that this is FOK and we want to trigger a liquidity auction without closing anyone out if we can't fulfil the full network cloesout order.

@tamlyn10 @davidsiska-vega I am closing this on the basis of the above. Please reopen and comment if you disagree or think we need to continue to track this.
