### ISSUE TITLE
Define Bond Account opening process

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/specs#1952]
This text needs adjusting to reflect when bond accounts are opened, consider different market states.\
hyperlink in text gives a 404

https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0013-ACCT-accounts.md#:~:text=Bond%20accounts-,Bond,-accounts%20are%20opened

```
Bond accounts
Bond accounts are opened when a party opens a [Liquidity Provision order](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0044-LIME-lp_mechanics.mdd). The bond is held by the network to ensure that the Liquidity Provider meets their SLA obligations. [0044-LIME - LP Mechanics](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0044-LIME-lp_mechanics.md) contains more detail on bond management.
```

**Comment by davidsiska-vega** [comment]
What more information do you need @vega-paul? I consider this correct and sufficient.

**Comment by vega-paul** [comment]
@davidsiska-vega do we still have concept of liquidity orders? Could we also explain the account only created outside auction, consider other market states - settlement, termination.

**Comment by davidsiska-vega** [comment]
The statement `Bond accounts are opened when a party opens a [Liquidity Provision order]` covers this; you have a link to the liquidity spec telling you when this can happen. 

It's an order and no order can be placed for a market that's terminated; that's covered in market lifecycle. A settled market it terminated hence the previous applies. 

> the account only created outside auction 

I don't know what you mean by that. If a market is in a monitoring auction (especially a liquidity auction) a new LP can come in, submit liquidity order and the account will be created.
