### ISSUE TITLE
Batch governance proposals

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#1994]
Started in the `palazzo` branch here:

- https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0028-GOVE-governance.md#batch-proposals

We need to check / update for:

- Allow multiple governance proposals in a single txn
- Include all network wide governance inc. network param updates and new markets
- Preferably include market updates too
- Entire proposal succeeds or fails with the "toughest" one
- Entire proposal fails validation if one does

DS comments:
- including market updates is a bit messy because different voting criteria can apply; I think it would not be hard to implement but may be poor UX if a batch proposal is rejected when e.g. the parameter votes pass but market ones fail. So I am not sure the added complexity is worth it. 
- we should defo allow batch market updates (i.e. update many markets).

**Comment by gordsport** [comment]
It has been decided that at a high level the spec should be updated to match the following:

- on the batch closing date the votes are collected. Each entry in the batch is evaluated on its own terms and will either pass or fail. If all the entries pass then the entire batch passes.

**Comment by candida-d** [comment]
Completed in #2045
