### ISSUE TITLE
Market lifecycle and periods

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#200]
In GitLab by @tamlyn10 on Jan 21, 2020, 10:29

Trading modes,
Expiry vs perpetual,
Conditional periods (e.g. auction call)
Suspended
Complex period setups - (e.g. continuous trading 9-5, batch auctions overnight)

Auction type -  price monitoring auction. Need to work out rules for this.

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jan 21, 2020, 10:31

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Jan 21, 2020, 10:38

changed the description

**Comment by edd** [comment]
Ref #288
