### ISSUE TITLE
TBC Improve database indexing for Block Explorer

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#2003]
https://github.com/vegaprotocol/vega/issues/8570

This prevents filtering and going back in Block Explorer history. 

This issue may also become more important as in 0.39 CometBFT look to be removing support for the indexing we currently use.

**Comment by TomMcL** [comment]
@edd Do you think this needs any spec work or is this pure engineering?

**Comment by edd** [comment]
@TomMcL A bit of both. I think we have an existing idea of what we want, but I think *someone* should write a spec/outline of what we're aiming for before we build it. It's probably a job for @vegaprotocol/core to outline what's indexed by TM, what's deficient, and how we're addressing it, and some acceptance criteria.

**Comment by Jiajia-Cui** [comment]
This is not spec work
