### ISSUE TITLE
Transfers from a vested account should

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2032]
Transfers from a vested account to general account of the same key should
- incur no transfer fee
- not be subject to minimum transfer amount if the full amount is transferred

**Comment by cdummett** [comment]
@davidsiska-vega do we need the restriction that the above only applies when transferring to the general of the same key?

Not sure I can see any issues with allowing transfers to any valid key/account combo and it's a bit simpler.
