### ISSUE TITLE
Make market name changeable by governance

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2061]
At the moment we deliberately *disallow* change to market names (worries about tricks whereby a name is changed to trick people to use a different market...). 

However we concluded that expecting the market names to be right the first time round is unrealistic (especially for perps that will be around forever). 

The task: find where in spec we allow the market name change and explicitly say this is allowed, updating relevant ACs.

**Comment by davidsiska-vega** [comment]
@Jiajia-Cui - please also have a look at what other things we disallow changes for and whether that's what we still want (I'm thinking metadata fields etc). Of course the settlement asset still has to stay and ditto for position and market decimals.

**Comment by Jiajia-Cui** [comment]
here is the[ PR ](https://github.com/vegaprotocol/specs/pull/2062/files)

**Comment by gordsport** [comment]
closed in:

- https://github.com/vegaprotocol/specs/pull/2062/files
- https://github.com/vegaprotocol/specs/pull/2064
