### ISSUE TITLE
Update margin spec for estimate margin with the introduction of isolated margin

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#2075]
Now that the isolated margin work has started we need to update margin spec for estimate margin with the introduction of isolated margin:

- [x] update the spec
- [x] Add ACs as required

**Comment by davidsiska-vega** [comment]
Let's spec this (the calculation), so this can be implemented as an API call for the FE to use. There is a separate issue whether FE provides all the inputs or whether some reads from the data node (based on party Id) are permitted. At the moment there are no reads.

**Comment by davidsiska-vega** [comment]
Possibly additional functionality / new API requirement:
- what happens (cashflows) to a party x if they change from isolated to cross or from cross to isolated
- cashflows if a party changes the leverage in isolated margin
- answer the question: what's the lowest leverage a party can ask for for leverage in isolated margin mode (or when switching)
