### ISSUE TITLE
As part of vAMM, remove the part of the margin calculation where we estimate slippage from order book...

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2081]
... and allow lower margin based on that. 

I.e. the margin will be based on `(linear slippage factor + rf) x price x size `

And max leverage is simply `1/ (linear slippage factor + rf) `

**Comment by gordsport** [comment]
@peterbarrow / @wwestgarth  - please can we do some performance review/thinkings and see if this is likely to be required
