### ISSUE TITLE
Enrich position APIs to include total fees paid / received and funding

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2118]
Enrich position APIs to include total fees paid / received and funding

**Comment by JonRay15** [comment]
https://github.com/vegaprotocol/vega/issues/10374

Core issue for this

**Comment by davidsiska-vega** [comment]
Loss socialisation?

**Comment by witgaw** [comment]
Addressed in https://github.com/vegaprotocol/specs/pull/2329
