### ISSUE TITLE
Add a new bridge

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#2143]
**Spec:**

Update the [ethereum_bridge_spec](https://github.com/vegaprotocol/specs/blob/colosseo/protocol/0031-ETHB-ethereum_bridge_spec.md) to describe:

- a change to the multisig contract code to include a chain-id in the signature
- add a new function to the assetpool? so that Axelar can work with it

Assumption is that the existing contract will remain on Ethereum and the new contract (in the same repo) will be deployed to Arbitrum.

**Questions:**

Are there any changes we need to make to the asset pool contract (and associated ACs)

**ACs:**

- Add new AC codes for some of the existing system tests for deposit/withdrawal, but mention pointing at the L2 chain instead
- AC's for key-rotations 
- Any others?

**Other tasks:**

- Investigate the security models of axelar
- Integrate axelar
- consider the heartbeat spec: https://github.com/vegaprotocol/specs/issues/1993
- How does this impact validator rewards?

**Comment by wwestgarth** [comment]
Just dumping a thought for two ACs that I think would be important (I can't find a spec change for this):
Deposit to the asset pool (either bridge). Read the EthereumEvent tx from tendermint and:
1) set the chainID to an empty string, re-sign and resubmit as a validator - check that it doesn't count as a deposit on either bridge
2) set the chainID to the _other_ bridge, re-sign and resubmit as a validator - check it fails to get validated

The system-tests already has the framework to re-sign/re-submit ethereum-event txs, so they should be ok to test.
