### ISSUE TITLE
Spec pegged orders

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#216]
In GitLab by @barnabee on Feb 10, 2020, 15:39

Write a spec pegged orders

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Feb 10, 2020, 15:39

created merge request !47 to address this issue

**Comment by ashleyvega** [comment]
In GitLab by @barnabee on Feb 10, 2020, 15:39

mentioned in merge request !47

**Comment by tamlyn10** [comment]
Pete is making some minor further changes and then will merge.
