### ISSUE TITLE
[SPEC ONLY] Reward analysis

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#2166]
### Rewards — would be good to get thinking about the below:

- Some analysis of the rewards over the past months
  - Who has got them?
  - What did they incentivise?
  - Any thing else about the current rewards thats noteworthy when looking ahead?

- What is possible with new reward types/features for Colosseo:
 - cap a reward at proportion of fees paid
  - cap relative to liquidity provided and/or market volume (i.e. allow LP rewards to not pay out everything if there’s not enough liquidity or spreads are too wide)
  - taker rewards but only where taker reduces reducing one or more LP net positions
  - cap distribution to each market (market anti-whaling)
  - in market scope have an “everything but these” scope
  - allow market scope to use a metadata tag / community tag

- Some thought into how to think about the optimal reward strategy, and how to communicate this to the community to inform their CAF funds usage (see https://discord.com/channels/720571334798737489/1192458594457759834 for the latest on the CAF)

**Comment by barnabee** [comment]
I have pulled this into Colosseo as breaking it down, doing analysis where needed, and writing individual tickets is in scope for Colosseo. The individual changes will most likely not all be.

**Comment by davidsiska-vega** [comment]
Ongoing analysis of rewards.
