### ISSUE TITLE
API to calculate amount of any asset they can transfer for free ... 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2168]
... as a consequence of trading activity. 

The UI should probably show the netparam which shows how much it decays each epoch. 

''''''''''''''''''''
probably ignore what's below. 
'''''''''''''''''''''

What do we need to cover?
- clearly the upper bound on maximum fee per transfer
- I guess the current “trading activity accrued discount”?
- for delayed transfers it should either refuse to answer (because it can’t guarantee value of netparams).
- what about recurring transfers?

From @barnabee: think we can be a bit :face_with_cowboy_hat:
- estimate only the first instance of a recurring transfer (as if it was a single transfer)
- always estimate as if the transfer happened right now
But I think it ideally would take into account the accrued trading fee discount as well as the cap.========

**Comment by witgaw** [comment]
https://github.com/vegaprotocol/specs/pull/2373
