### ISSUE TITLE
Event stream

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#219]
In GitLab by @tamlyn10 on Feb 25, 2020, 14:35

Big note: This is a *Vega implementation* ticket and is not a *Protocol Specification*. We need to figure out how we differentiate between the two within this repository.

**Comment by ashleyvega** [comment]
In GitLab by @edd on Feb 25, 2020, 14:39

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @edd on Feb 25, 2020, 14:54

marked this issue as related to #141

**Comment by edd** [comment]
This has been replaced by a merge request in core: https://github.com/vegaprotocol/vega/issues/1475
