### ISSUE TITLE
Add spec for order transaction ordering within blocks

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/specs#2232]
Add a spec for ordering transactions within a block for a given market such that post-only changes and cancellations come first, allowing market makers to offer tighter prices with less risk from toxic flow.

https://github.com/vegaprotocol/specs/pull/2231

**Comment by davidsiska-vega** [comment]
Make sure we're clear that batches either:
- contain nothing "potentially aggressive" (post only orders, or cancels) in which case the whole batch gets priority and doesn't get delayed. If it has amends it's potentially aggressive. 
- if the batch contains a single aggressive transaction it gets delayed

1, Standalone cancels
2, Batches as a whole
3, Standalone creates

Make sure we mention that delayed orders need to go into snapshots.
