### ISSUE TITLE
Make margin calculation file more explicit about temporary workaround

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#224]
In GitLab by @tamlyn10 on Mar 12, 2020, 14:00

As per Slack thread here:

https://vegaprotocol.slack.com/archives/CAD8F4R2B/p1584007338126400

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 12, 2020, 14:00

assigned to @tamlyn10

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 12, 2020, 14:00

changed the description

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 12, 2020, 14:00

created merge request !51 to address this issue

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Mar 12, 2020, 14:00

mentioned in merge request !51

**Comment by tamlyn10** [comment]
Specifically this line in spec 19 that talks about using mark price when not sufficient liquidity - no surpassed by liquidity monitoring.

https://vegaprotocol.slack.com/archives/CAD8F4R2B/p1584009777135700?thread_ts=1584007338.126400&cid=CAD8F4R2B
