### ISSUE TITLE
Simpler weight function for LP scoring

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2252]
1. Add an option to replace prob-of-trading-based weight with simple piecewise-linear and continuous functions, which are specified by setting a "range", optional to config from best bid / ask vs mid.

2. Add an option to calculate probability of trading weights in the current design from mid as opposed to best bid / ask. 

In market protos this should ideally go with the SLA params.

**Comment by witgaw** [comment]
https://github.com/vegaprotocol/specs/pull/2267
