### ISSUE TITLE
LP protocol reward schemes carry own SLA def

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#2254]
1) More flexible scheme
The LP protocol reward scheme can optionally additionally specify the who "SLA blob" with its own range and time on book etc and the rewards are distributed according to the SLA rules specified here. 

There can be multiple such reward schemes per one market. 

One reward scheme can still have multiple markets in scope.

**Comment by davidsiska-vega** [comment]
On ice till https://github.com/vegaprotocol/specs/pull/2299/ is finished.

**Comment by cdummett** [comment]
Closing as complete as liquidity 3.0 PRs merged into genbu and temporary colosseo / suzuka work de-prioritised.
