### ISSUE TITLE
Add fee components for network value accrual

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#2295]
Add two new fee components (network wide):

1. **Network treasury fee factor:** this fraction of the trade notional would be taken as a fee and transferred to the network treasury.
2. **Buyback fee factor:** this fraction of the trade notional is used to buy VEGA tokens on a spot market, if such a market exists (if not they jus go to the network treasury). 
    - Should the purchase/order placement be real time with each trade (max of one order so amend it if unfilled) or should it happen to accrued tokens every N epochs?
    - Maybe the purchase should always be via an auction, or maybe we can use limit orders and rely on price monitoring for an auction if needed, though concern would be spot auctions aren't really long enough. Perhaps the feature get's a "special" price monitoring bound such that if the last price is stale by some time or the slippage is greater than some threshold there's a price monitoring auction that could be triggered only in this case and could be longer?

NB: if this was to be split for deliverfy I'd suggest adding both components at the same time in the first phase, with the buyback fee going to a new account type and just accruing initially, then add the actual buyback later, as that would allow the community to decide to enable these accruals earlier.

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/specs/pull/2293/
