### ISSUE TITLE
Add dynamic maker fee based on maker's volume 

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#2296]
Dependent on #2295 as the maximum uplift of the maker fee/rebate is the 

Similar to the volume discount scheme, a **new** table of maker fees that maps the volume done by the maker to an extra maker fee factor. Maximum additional fee factor is the total amount allocated to the _network treasury fee factor_ plus the _buyback fee factor_.

This extra amount is added to the maker fee on each trade and is also paid immediately to the price maker.

- [ ] Confirm this should be measuring maker volume only
- [ ] Confirm whether levels are set at a % of the total [maker] volume on that market during the window OR absolute amounts

**Comment by davidsiska-vega** [comment]
Existing maker fee factor stays as is untouched by this (and the LP and infra too).

**Comment by davidsiska-vega** [comment]
Any of these can be zero, (including existing ones).

**Comment by davidsiska-vega** [comment]
https://github.com/vegaprotocol/specs/pull/2293 closes
