### ISSUE TITLE
Reward scaling by notional

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#2318]
Two related problems experienced by reward creators are:
1. the inability to give predictable rewards where the amount of the reward is fixed for a given level of activity; and
2. the need to over fund rewards when volume/activity is low in order that the reward is high enough when the level of activity is higher.

These can both be solved by the addition of reward scaling. Under reward scaling, in addition to specifying the amount of the recurring reward payment, the user can also specify the amount of volume in notional (`target_notional_volume`) at or above which the full amount is available.

The amount transferred would be `(actual_notional_volume / target_notional_volume) * transfer_amount`, meaning that assumingt the target notional is larger than the actual notional, additional acitivty qualifying to be rewarded would not reduce the amount of the reward per unit of activity.

This feature should be optional, and care should be taken in the design regarding how it interacts with #2317.

**Comment by davidsiska-vega** [comment]
- `target_notional_volume` will be in the settlement / quote asset of the markets in scope for reward; an optional parameter with value `0` meaning no reward scaling. 
- not applicable to staking rewards, validator ranking rewards, market creation rewards.

**Comment by cdummett** [comment]
Can the scaling increase the rewards paid out in the case the actual notional is greater than the target notional also or is only supposed to reduce rewards?

i.e. Should the actual amount transferred be capped at the `amount` specified in the transfer like so...
```
actual_transfer_amount = min(actual_notional_volume / target_notional_volume, 1) * transfer_amount
```

@barnabee answer: it's a cap as you say above.

**Comment by davidsiska-vega** [comment]
Do we want to allow scaling by open interest additionally? Enum what the metric is:
- average traded notional 
- average open interest (from time-weighted average positions) 

Using reward / payout window length we should sum (or average) the notional across the reward payout frequency.
