### ISSUE TITLE
Reward eligibility - specific keys

### ISSUE THREAD

**Issue by cdummett** [vegaprotocol/specs#2342]
To reward a set of users based off off-chain logic, add eligibility requirement, `eligibile_keys` - limits scopes of parties to those included in the set.

Doing:
- list of users in the recurring transfer

Not doing:
- maintain "team", whist is a list of users and specify the "team" id - unclear whether reusing team mechanics or new separate entity.

Use cases:

- focus testing on eligibile entities metric
 - pro-rata
 - ranked
 - lottery
- w/ min position req
- w/ min staking req - for "staking rewards"

**Comment by davidsiska-vega** [comment]
For ACs needs to definitely work with:
- eligible entities metric
- eligible entities metric with lottery 
- staking
