### ISSUE TITLE
Mark price: 4 acceptance criteria

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#279]

**Comment by ponthief** [comment]
Does the mark price support < 0 values? Very rare, but happened just recently to Interactive Brokers on Oil Futures: https://www.ft.com/content/01ee0794-158f-40c5-8bb9-82cf5d5f314b

Can algorithms for the mark price calculations be updated during the life of the Market?

Mark price changes in quick successions while the mark-to-settlement is being recalculated - stop mark-to-settlement calculations, as it will be recalculated? Large number of parties need their positions recalculated..potential impact on the trading engine?

Source of the last trade price - core or blockchain?..different Vega nodes might have different last prices (until they sync)...possible that mark-price is not same across all the nodes?

**Comment by barnabee** [comment]
> Source of the last trade price - core or blockchain?..different Vega nodes might have different last prices (until they sync)...possible that mark-price is not same across all the nodes?

They can never have different prices, whatever the source the mark price must be the result of a determnistic transaction on the VEGA blockchain and therefore all nodes at the same blockcheight must have the same mark price.

**Comment by barnabee** [comment]
> Does the mark price support < 0 values? Very rare, but happened just recently to Interactive Brokers on Oil Futures: https://www.ft.com/content/01ee0794-158f-40c5-8bb9-82cf5d5f314b

We currently enforce `price > 0` IIRC cc @edd @jeremyletang ?

In future (perhaps when we look at 'decimal' support we should look at supporting negative prices. This will need some analysis with @tamlyn10 @davidsiska-vega

**Comment by barnabee** [comment]
> Can algorithms for the mark price calculations be updated during the life of the Market?

This should be possible by governance transaction. I think market parameter changes are still not built and we currently only have one mark price calculation methodology anyway so not possible at the moment.

**Comment by barnabee** [comment]
> Mark price changes in quick successions while the mark-to-settlement is being recalculated - stop mark-to-settlement calculations, as it will be recalculated? Large number of parties need their positions recalculated..potential impact on the trading engine?

Mark prices can't change due to the mark to market process itself (close out trades do not update the mark price, see here: https://github.com/vegaprotocol/product/blob/master/specs/0012-position-resoluton.md#acceptance-criteria) and as the procesing of transactions within a market is strictly sequential then any transaction that can change mark price must by definition not be processed during calculation of MTM.

**Comment by ponthief** [comment]
> > Mark price changes in quick successions while the mark-to-settlement is being recalculated - stop mark-to-settlement calculations, as it will be recalculated? Large number of parties need their positions recalculated..potential impact on the trading engine?
> 
> Mark prices can't change due to the mark to market process itself (close out trades do not update the mark price, see here: https://github.com/vegaprotocol/product/blob/master/specs/0012-position-resoluton.md#acceptance-criteria) and as the procesing of transactions within a market is strictly sequential then any transaction that can change mark price must by definition not be processed during calculation of MTM.

Didn't mean the mark-to-settlement will change mark price, but while the calculations is ongoing the mark price gets updated because of new trades or best bids...
e.g mark price changes every 1 sec (market very liquid), it takes 5 secs to recalculate mark-to-settlement - you will be unnecessarily recalculating positions for the 1st mark price as the mark price has changed 4 times before you finished recalculated 1st mark-to-settlement - what do we do in such cases?

**Comment by ponthief** [comment]
> > > Mark price changes in quick successions while the mark-to-settlement is being recalculated - stop mark-to-settlement calculations, as it will be recalculated? Large number of parties need their positions recalculated..potential impact on the trading engine?
> > 
> > 
> > Mark prices can't change due to the mark to market process itself (close out trades do not update the mark price, see here: https://github.com/vegaprotocol/product/blob/master/specs/0012-position-resoluton.md#acceptance-criteria) and as the procesing of transactions within a market is strictly sequential then any transaction that can change mark price must by definition not be processed during calculation of MTM.
> 
> Didn't mean the mark-to-settlement will change mark price, but while the calculations is ongoing the mark price gets updated because of new trades or best bids...
> e.g mark price changes every 1 sec (market very liquid), it takes 5 secs to recalculate mark-to-settlement - you will be unnecessarily recalculating positions for the 1st mark price as the mark price has changed 4 times before you finished recalculated 1st mark-to-settlement - what do we do in such cases?

As explained by Jeremy, due to sequential nature of the mark price determination and  mark to settlement this scenario is not possible.

**Comment by tamlyn10** [comment]
Regarding negative values, I have created a research ticket for this. It will need thorough evaluation and analysis before we're able to integrate that possibility into our protocol.

https://github.com/vegaprotocol/research-internal/issues/146
