### ISSUE TITLE
Market Framework: 0 acceptance criteria

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#287]

**Comment by ponthief** [comment]
**Data**
1. Identifier must be a unique value across Vega Network - uniqueness validation (central repository of all the markets?), what is min/max length of the identifier, what characters are allowed and which are not
2. Continuous Trading mode - tick size/decimal places acceptable values (> 0 < ?), what is the duration (till Market Expiry?), stop/start signals (market status messages) to the market participants?
**Instrument**
1. Acceptable base/quote currencies - validation
2. Futures Contract size - there is none?
**Metadata**
1. initialMarkPrice - who sets it? justification for the price? 
2. tags - what are acceptable values?
**Maturity**
 Expiration date acceptance - format and 'reasonable' expiry date?
Status Change (Active to Mature) - market participants informed?

**Comment by edd** [comment]
@3jtechtest I had missed your comment on this. How should we take this forward? Feels like we need some input from @tamlyn10 or @barnabee or @davidsiska-vega

**Comment by davidsiska-vega** [comment]
I think `initialMarkPrice` should not be a field *at some point in the future* because an opening auction should replace this.

**Comment by jeremyletang** [comment]
1. the identifier needs to be unique but will sequenced from the chain, we won't have a central repository for that.
3. this needs to be assets loaded into the collateral engine (later on accepted through governance).
5. For now it's set through arbitrarly in the market framework yes, but will disapear once we have other way to define it (through auction e.g)

**Comment by tamlyn10** [comment]
4. Is this relevant? https://github.com/vegaprotocol/product/issues/192
