### ISSUE TITLE
Fix governance spec

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#292]
As per Slack discussion here: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1591002479004100

each governance type should reference specific network parameters regarding proposal time and participation.

**Comment by barnabee** [comment]
@edd this shouldn't be a blocker for public Testnet

**Comment by tamlyn10** [comment]
@barnabee can you explain why? Currently, we require people to submit their own proposal time and minimum market participation amounts when they propose a new market... is that OK for public testnet?!

**Comment by barnabee** [comment]
@tamlyn10 this change is to:

1. allow the min/max for participation threshold, proposal duration, time between vote close and enactment to be specified separately for each proposal type
2. to make sure all the above are network parameters that can be changed by a vote

They will always need to specify the values they want in the proposal. For public Testnet it's ok to have one set of min/max values across all proposal types IMO.

**Comment by tamlyn10** [comment]
Mmm.. I guess I'm kinda ok with that, though I had expected the market proposals to just be a single set time and threshold defined by a network parameter. Feels like better UX...

**Comment by barnabee** [comment]
If we want to include a default in the UI and put customising it under an "advanced" tab or something then we can do that but that doesn't need to be a constraint on the protocol. UX should happen at a layer of abstraction or two above this and not generally influence the protocol design.

At a protocol level there are very good reasons the actual values shouldn't be set in stone for every proposal, even of a same type. A standard default is nice for some things (the simple cases) but if you are coordinating the timing (e.g. to launch a series or set of related markets, respond to a real world event with a parameter change, etc.) then it would be a real pain to have every action take effect a set time after the transaction is posted.

Ditto the threshold, as a voter I may only be wiling to approve a change that's got a high level of engagement if it is very fundamental, or any majority may do for something less important that can easily be changed. For example: enabling a fundamental change to MTM calcs might need very high threshold for sign-off, whereas changing the validator fee could be a much lower threshold and duration as it if gets set "wrong" someone can make a new proposal and set it "right" again fairly quickly (potentially even before the first change gets enacted, if one configures the enactment date thay way).

These interact with each other too: high threshold => I may want a long voting period to reach the threshold (often those changes may be big upgrades that can wait months) but low thresholds may be closer to immediate, but require a win % of two thirds so it's a definite and clear majority, etc.

Point is we will want this felxiiblity some times and it'll be too late to build it when we need it.

More discussion on some of these potential scenarios (and I think you asked the same question as above 😼) here in the governance spec workshop: https://us02web.zoom.us/rec/share/9NRfcIH96T1LHa_jsHPFfKgtBIf1X6a803Ieq_QFzk1x0lx0quaoOc7fDuSqRNoy (NB: it starts about 7 mins in)

**Comment by tamlyn10** [comment]
Yeah, the thing that confuses me is that things like this: _enabling a fundamental change to MTM calcs might need very high threshold for sign-off_ should be understood as important by the *network* which should enforce a higher threshold right? So, having a generic _min_ and _max_ for all parameter update proposals seems dangerous to me.

I take it that your perspective is that token holders are meant to do the labour of figuring out whether the threshold proposed is high enough. That's what I mean by UX.. not visual front end stuff - but rather the labour and understanding of the rules....as a market creator and token holder. 

I think the market creation commencement date should be chosen by the proposer (as for the series of markets you recommend), but I think the proposal period should be set by the network. 

Just my opinion.. which is now noted here. If you want to do it your way, I will have to think about the console UX and the way we include in FAQs and talk to the community about it. No big deal, it's just not what I'd expected.

**Comment by barnabee** [comment]
Re: network parameters, the parameter being updated would be part of the udpate type I think so I'd expect some parameters to be harder to update than others.

Re: UX I don't think this needs tons of though (I think the rest of the form is scarier!), but I would expect something like:

```
# When should this market be created / parameter be updated / etc.?

(  ) As soon as possible (market will be created <duration from params> after submission
(  ) After an extended voting period ending at  [______________] (market will be enacted <min enactment time param> after voting closes)
(  ) At a specific date and time:  [______________]

[  ] Use advanced proposal options   <-- when checked, disables above options and shows panel with all the proposal fields (vote close date/time, enactment date/time, threshold, win %)
```

**Comment by barnabee** [comment]
> Re: network parameters, the parameter being updated would be part of the udpate type I think so I'd expect some parameters to be harder to update than others.

It would be good to get the list of all network parameters we are currently maintaining in the system so we can see whether it would make more sense to classift them and set the value by parameter class / type rather than for each.

**Comment by tamlyn10** [comment]
Agree, and it's currently on my list (https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1590474152462200) though will write a spec issue just so it really gets done :-D

**Comment by barnabee** [comment]
Oh, nice, thank you! That is a non-fun job.

**Comment by tamlyn10** [comment]
Check this thread and add update spec accordingly: https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1591682159088800?thread_ts=1591633108.081800&cid=C9E6XA8GK

**Comment by tamlyn10** [comment]
@barnabee I'm making some edits to the governance spec and I see this:

> Proposals are enacted in the order they were created. This means that in the case that two proposals change the same parameter in roughly the same period, the oldest proposal will be applied first and the newest will be applied last. There is no attempt to resolve differences between the two.

How does the "roughly the same period" work? I would have thought that the enactment date-time was pretty exact and for the nodes to all work the same way, it would have to be very clear when 2 proposals are "close enough together" that the core should look for the oldest one first?

**Comment by tamlyn10** [comment]
@edd I see these in the governance acceptance criteria (I think added by you). 

> - [ ] As the vega network, proposals that close less than 2 days from enactment are rejected as invalid
> - [ ] As the vega network, proposals that close moreless than 1 year from enactment are rejected as invalid

Are we planning to have network parameters that control this behaviour? If so, I suggest I add that to the spec body and adjust these to reference those parameters?

**Comment by tamlyn10** [comment]
Adding this Slack discussion for future reference https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1581592133108300

**Comment by edd** [comment]
I think this is a question for @pand-dev as he has been dealing with network parameters in https://github.com/vegaprotocol/vega/pull/1761

**Comment by tamlyn10** [comment]
Yeah, I guess I hadn't considered the network controlling the time between proposals closing and the enactment.

I note, that there is an outstanding spec task cc @barnabee to map out the market lifecycles. But let's discuss here meanwhile.

With market creation (for a continuous trading mode), I see the **enactment datetime** as when we open up the market to its opening auction - it will collect liquidity commitments and trading volume and if it meets some theresholds, it will launch into a continuous trading mode market.

In this case, I don't see a need for any significant time between proposal closing and enactment (because that's kind of built in to the design of the market launching slowly and carefully).

I would probably prefer this be handled by the type of price determination method of the market. But this is stuff we've not really made clear granular decisions on - perhaps @davidsiska-vega @barnabee you guys want to input?

**Comment by barnabee** [comment]
Minimum length for the voting period (i.e. duration from proposal acceptance to vote closing) and minimum time between vote closing and enactment are both network parameters that should exist _per proposal type_ exactly as for the vote thresholds. (The proposal itself will be able to choose when voting actually closes and when enactment happens as long as they meet the minimums, though, as there may be reasons for providing longer to analyse and vote on something that might not otherwise get approved, or to enacting the proposal at a specific time, to coincide with some other event or to provide additional preparation time to deal with the change.)

I expect for new markets:
- Minimum voting period duration will be some number of days (in Mainnet, Testnet could be much less to make testing easier.)
- Min time from vote close to enactment can be 0

For network and market parameter changes these may be different, and the "subcategory" will be important too. Some times of change could impact say every market maker's commitment, or margins on all open positions in a market so I would expect these to have a longer time between vote closing and enactment (again, how much longer may vary by category, too) so that there's advance warning of what's coming.

**Comment by tamlyn10** [comment]
OK, I'll need to update the spec to describe this (though the acceptance criteria includes it).

Are you also able to answer this question? https://github.com/vegaprotocol/product/issues/292#issuecomment-641754176

**Comment by barnabee** [comment]
> @barnabee I'm making some edits to the governance spec and I see this:
> 
> > Proposals are enacted in the order they were created. This means that in the case that two proposals change the same parameter in roughly the same period, the oldest proposal will be applied first and the newest will be applied last. There is no attempt to resolve differences between the two.
> 
> How does the "roughly the same period" work? I would have thought that the enactment date-time was pretty exact and for the nodes to all work the same way, it would have to be very clear when 2 proposals are "close enough together" that the core should look for the oldest one first?

This is due to the fact that time in Vega jumps between discrete times printed on finalised blocks, but I think we should change it to be:

Proposals are enacted in order (1) their enactement timestamp; then (2) when they were proposed. This means that:

- A proposal with a later enactment date can change a value that was recently changed by another proposal
- A proposal created later for the exact same enactment date would overwrite the value changed by an earlier created proposal with the same date.

**Comment by tamlyn10** [comment]
@barnabee claims it took more than 20 minutes to do. Probably more like 3 days of elapsed time. He now claims it's in a state to push changes.

**Comment by barnabee** [comment]
Who said it'd be 20 mins? Not me!

That said it is done or nearly done. Will push today.
