### ISSUE TITLE
Network parameter spec

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#293]
https://github.com/vegaprotocol/product/issues/292#issuecomment-636798841

**Comment by tamlyn10** [comment]
I've made a start on a spreadsheet here: https://docs.google.com/spreadsheets/d/1g49GLT-nXBq9zcn1gyl5PveJtzZoNQbraMx-7SFhaBo/edit#gid=0

**Comment by tamlyn10** [comment]
@barnabee could you please review the above red cells in the spreadsheet?

**Comment by tamlyn10** [comment]
removed weird auction/governance parameters from list as have been removed from core. Tamlyn to progress this, this week - particularly ready for setting the market creation parameters for new release next week.

**Comment by nzbaen** [comment]
@barnabee question about "[Proposal Validation Parameters](https://github.com/vegaprotocol/product/blob/master/specs/0028-governance.md#proposal-validation-parameters)":
what does the "category" parameter specified in this doc refers to? (e.g. `Governance.<ActionType>.<Cateogry>.MinimumProposalPeriod`)

**Comment by tamlyn10** [comment]
This issue is completed when:

- [ ] We have a full list of network parameters in the above spreadsheet
- [ ] We know what the name in the code for each of these parameters is (so we can communicate this to our community)
- [ ] We have a "network parameters" spec that lists all the parameters
- [ ] Every spec has a "network parameters" section that lists out the parameters relevant in that spec.
- [ ] Every network parameter can be easily set by Research when configuring network and sufficient descriptions exist for community.

**Comment by nzbaen** [comment]
@barnabee @jeremyletang 
[0010-margin-orchestration.md](https://github.com/vegaprotocol/product/blob/master/specs/0010-margin-orchestration.md#acceptance-criteria) Acceptance criteria: Point 2 and 3 "threshold".
Are those two points implemented already in the code? Do we currently have a threshold for significant order book changes implemented?

**Comment by barnabee** [comment]
> @barnabee @jeremyletang
> [0010-margin-orchestration.md](https://github.com/vegaprotocol/product/blob/master/specs/0010-margin-orchestration.md#acceptance-criteria) Acceptance criteria: Point 2 and 3 "threshold".
> Are those two points implemented already in the code? Do we currently have a threshold for significant order book changes implemented?

I think we only have implemented point 2, where there’s no threshold being used and all margins are recalculated but @jeremyletang should be able to confirm.

**Comment by nzbaen** [comment]
@barnabee  @tamlyn10 @davidsiska-vega 
Question: [0026-auctions.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0026-auctions.md)
```
## Duration of frequent batch auctions
As part of the market framework, we need to be able to specify the duration of auctions period.we need to be able to specify the duration of auctions period.
```

Is this a network parameter that is on the frequent batch option trading mode?

**Comment by nzbaen** [comment]
@barnabee @tamlyn10 @davidsiska-vega @jeremyletang 
Question: [0028-asset-proposal.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0028-asset-proposal.md#proposing-a-new-asset)

```
## Proposing a new asset

[...]
If the asset is accepted by the node, the node will then send his own vote as a transaction to the chain, so the other validators can keep track of whom is accepting the new asset.
This first phase may be configured through network parameters (e.g: duration of the phase, how much validator needs to succeed to validate the asset).
```

Do we have this part implemented in the Network Parameters? Is still something that is going to be implemented?

**Comment by nzbaen** [comment]
@barnabee @tamlyn10 @davidsiska-vega 
Question: [0030-fees.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0030-fees.md#factors)

```
Factors
infrastructure: staking/governance system/engine (network wide)
maker: market framework / market making (network wide)
liquidity: market making system (per market)

The method of calculation of these values is out of scope for this spec. If the fees MVP is built before the contributing part of the system that would calculate the fee factor, a static (but changeable by governance as normal) network parameter can be substituted for each missing calculation. Realistic values might be: fee_factor[liquidity] = 0.001 = 0.1%, fee_factor[infrastructure] = 0.0005 = 0.05%, fee_factor[maker] = 0.00025 = 0.025%.
```

I've added in the document the 3 possible network parameters, if those are already implemented in Core, can anyone please confirm it and their specific names?

**Comment by nzbaen** [comment]
@barnabee @tamlyn10 @jeremyletang @davidsiska-vega We need the following questions answered and we need to decide if and how we are going to implement the specs, and agree on the naming. Could you please review and answer? Thank you

________
## Question: [0026-auctions.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0026-auctions.md)

```
## Duration of frequent batch auctions
As part of the market framework, we need to be able to specify the duration of auctions period.we need to be able to specify the duration of auctions period.
```

Is this a network parameter that is on the frequent batch option trading mode?
________
## Question: [0028-asset-proposal.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0028-asset-proposal.md#proposing-a-new-asset)

```
## Proposing a new asset

[...]
If the asset is accepted by the node, the node will then send his own vote as a transaction to the chain, so the other validators can keep track of whom is accepting the new asset.
This first phase may be configured through network parameters (e.g: duration of the phase, how much validator needs to succeed to validate the asset).
```
Do we have this part implemented in the Network Parameters? Is still something that is going to be implemented? 
________
## Question: [0030-fees.md](https://github.com/vegaprotocol/product/blob/293-network_parm-full_list/specs/0030-fees.md#factors)

```
Factors
infrastructure: staking/governance system/engine (network wide)
maker: market framework / market making (network wide)
liquidity: market making system (per market)

The method of calculation of these values is out of scope for this spec. If the fees MVP is built before the contributing part of the system that would calculate the fee factor, a static (but changeable by governance as normal) network parameter can be substituted for each missing calculation. Realistic values might be: fee_factor[liquidity] = 0.001 = 0.1%, fee_factor[infrastructure] = 0.0005 = 0.05%, fee_factor[maker] = 0.00025 = 0.025%.
```
I've added in the document the 3 possible network parameters, if those are already implemented in Core, can anyone please confirm it and their specific names?

**Comment by nzbaen** [comment]
@barnabee @tamlyn10 @jeremyletang @davidsiska-vega can we check the above and close this please?

**Comment by edd** [comment]
@tamlyn10 please pick this up

**Comment by nzbaen** [comment]
can anyone pick this up please 

@tamlyn10 @barnabee @davidsiska-vega

**Comment by tamlyn10** [comment]
>  specify the duration of auctions period.

No, this is a market parameter..

**Comment by tamlyn10** [comment]
>  of the phase, how much validator needs to succeed to validate the asse

Tamlyn to follow up this one..

**Comment by tamlyn10** [comment]
@domvega to progress this - update spreadsheet and compare against implemented and liaise with Jeremy.

**Comment by tamlyn10** [comment]
Make sure we include the network parameter that relates to how long we wait for confirmation of deposits on bridge chain.

**Comment by edd** [comment]
https://github.com/vegaprotocol/product/blob/master/specs/0031-ethereum-bridge-spec.md

**Comment by davidsiska-vega** [comment]
@tamlyn10 said @edd  is the blocker as he's got an opinion.

**Comment by davidsiska-vega** [comment]
Next step after naming convention @tamlyn10 finalize the list of network parameters in Excel https://docs.google.com/spreadsheets/d/1g49GLT-nXBq9zcn1gyl5PveJtzZoNQbraMx-7SFhaBo/edit#gid=0

**Comment by davidsiska-vega** [comment]
@edd and @tamlyn10 will pair finish this.

**Comment by tamlyn10** [comment]
@tamlyn10 to update WIP spec as per discussion here. 
https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1618568252281700

**Comment by pennyandrews** [comment]
This ticket relates to #512 and should be considered together.

**Comment by gordsport** [comment]
Tamlyn and Valentin to get together and finish the spec
