### ISSUE TITLE
Add spec for market depth generation and distribution

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/specs#299]
We currently generate market depth data by listening to the orders placed on the orderBuffer and using that information to build up a market depth order book. This fails when we have amends because there is not enough information in the orders to be able to update the book correctly. 

We have discussed a better way to handle this using the new event bus system. This spec will highlight the features of the new system

**Comment by tamlyn10** [comment]
@peterbarrow finalising after resolving cumulative volumes... chase for feedback. Will need a console, engineer and @barnabee review.

**Comment by tamlyn10** [comment]
@edd is going to respond to Pete's question about cumulative volume (UI side or core side)? @barnabee suspects core will need cumulative volume for things like slippage calculation.

**Comment by edd** [comment]
Yes

**Comment by tamlyn10** [comment]
Feedback provided. WIP with @peterbarrow

**Comment by tamlyn10** [comment]
Pete and Elias meeting to discuss event bus and implications for this spec, this week!

**Comment by peterbarrow** [comment]
Updated spec with cumulative volume details and cleaned up event messages.
Ready to merge
