### ISSUE TITLE
Market framework & Proposals: More examples

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/specs#302]
To help understand how the market framework will be used it would be nice to have some more examples. e.g. non-FX futures, Markets that are not quoted in a currency. 

I've started a spreadsheet for populating some examples if useful: https://docs.google.com/spreadsheets/d/1QhOcx4ImbGsCgMemYegJKWWSLdQ8zeB5nWjFRD867L0/edit?usp=sharing

**Comment by witgaw** [comment]
@campbellssource where would you like those examples to go? The spreadsheet that you've created or a document in the `product` repo (or some other place?) ?

**Comment by campbellssource** [comment]
@witgaw I don't really mind. Perhaps there is an exercise of populating a long list to discuss and then separately to put a few more examples in the spec.

**Comment by campbellssource** [comment]
FYI I think this exercise might or could help resolve #192, #295,  #247 and #287. 
This will help us communicate to users how to use the various inputs when proposing markets and check the Market framework and Built in futures spec have everything required to support markets we imagine Vega to support.

**Comment by campbellssource** [comment]
The reason I've linked #192 is because I'm not sure how the value provided by oracle/settlement relates to the contract size field.

**Comment by witgaw** [comment]
Again, sorry for the delay. Added some more examples (option and swaps). Asked @tamlyn10 @davidsiska-vega to review when they have a moment. @campbellssource please let me know if that's not quite what you were after.

**Comment by tamlyn10** [comment]
Witold had added some today. @tamlyn10 and @davidsiska-vega reviewing. Tamlyn to think about the Built In Future spec with respect to this.

**Comment by campbellssource** [comment]
We are now planning on [having place to paste raw json](vegaprotocol/console#4356) instead or as well as a form in Console for proposing markets.

So examples of JSON formatted market proposals would be really good.

There was some suggestion of creating a repo for this.

Examples I'd like to see (including an oracle):
- GBPUSD/OCT20
- ETHBTC/DEC20 (ideally allowing users to deal in less than a whole BTC. So ETH/Satoshi)
- ETHUSD/DEC20
these could then be used in the genesis block to propose the 3 opening markets. Bonus points if you could suggest a default deal size for each market too. 1.0BTC or 10000 Satoshi
I'm curious to see
- An interest rate future (aDAI?)
- A weather future (sunshine hours, oracle might be tricky)
- A hashrate future 
- A gas price future
- btc volatility future

**Comment by ashleyvega** [comment]
This potential new repo, containing market proposal json example, would need to be included in the ongoing release process (continual checks to make sure the json is correct, update if not, and tag releases matching core).

Therefore I suggest that sample json files go into an existing repo, for example [sample-api-scripts](https://github.com/vegaprotocol/sample-api-scripts/).

**Comment by edd** [comment]
@tamlyn10 please pick this up

**Comment by edd** [comment]
@tamlyn10 is closing this as ‘not spec work’, and passing the buck to the community for designing new markets. This will hold up reworking the Propose Market form.
