### ISSUE TITLE
Spec deal ticket cost estimate

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#317]
Currently the users have no way of knowing what placing an order will cost them. There are two components to this: margin requirements and fees. 

This needs to be specd and ticketed.

**Comment by campbellssource** [comment]
I think this might be a duplicate: https://github.com/vegaprotocol/product/issues/311

**Comment by witgaw** [comment]
Thanks @campbellssource, I'll reference #311 in the Fees Part 2 board and close this one.
