### ISSUE TITLE
Add validator spec

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#329]
The Fees spec mentions a validator spec:

https://github.com/vegaprotocol/product/blob/master/specs/0029-fees.md#collecting-and-distributing-fees

> Further distribution of the infrastructure_fee and liquidity_fee are covered in other specs (market making and validator specs).

There is no validator spec, so there is no specified behaviour for how the infrastructure fee is distributed to validator runners. There is also insufficient detail in the white paper to guess at this.

**Comment by tamlyn10** [comment]
This is duplicated.. see https://github.com/vegaprotocol/product/issues/374
