### ISSUE TITLE
Transferring collateral between entities

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#339]
From Jeremy...

> I’ve been thinking, it may not be super useful straight away or anything but I can imagine this being handy maybe at some point, would it be useful for us to build some instruction so we could transfer funds from a party to another tthrough vega?
> I can imagine that being useful for trader having many parties, they could do a deposit of e.g 100 eth to one of their parties, then decide through vega to split this in between 100 different parties.

https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1597245798127400

**Comment by edd** [comment]
#779
