### ISSUE TITLE
Update market making mechanics specs

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#343]
- Update liqudiity demand spec
    - [x] window calc to scale when < period
    - [x] re-write and ensure it agrees with Python model
- [x] Equity-like share spec to match Python model ("Rewariding market makers")

**Comment by barnabee** [comment]
Hi @davidsiska-vega any chance you could pick these up? I need to concentrate on Polychain stuff and don't want to hold up our dev. Should be self explanatory as the code in the sim () is pretty clear and smple IMO.

Sim refs:

* Liquidity provider calcs: https://github.com/vegaprotocol/sim/blob/mlp-modelling/sim/mechanism/liquidity_provider.py#L63-L78 
* Market level calcs: https://github.com/vegaprotocol/sim/blob/mlp-modelling/sim/mechanism/market.py#L38-L66

cc @tamlyn10

**Comment by davidsiska-vega** [comment]
@tamlyn10 @witgaw (and optional @barnabee) I've pushed updates to the specs. Let's set up a Zoom when suitable (Tamlyn, that's mainly up to you) to review this. Also, you'll help me write acceptance criteria ;-).
