### ISSUE TITLE
Futures Maturity date on New Market Proposals

### ISSUE THREAD

**Issue by ponthief** [vegaprotocol/specs#358]
Currently it is possible to specify Maturity date for the new Market that is in the very near future (minutes, hours, days)...
Should there be any validation required to prevent creating Futures Markets that are very short or very long?
i.e Market can be proposed that will expire before Voting on it closes or the Market is Enacted, like below:
Voting closes at 09:46 on Sept. 17, but Market Expired at 09:46, the same day.

Reference Slack thread: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1600332504251100

```
proposal {
  ID: "P0000001404-0000000006"
  reference: "XJJARU34LD24CGE"
  partyID: "1c1d940536a283a050d288e87b6a65fb86f168f10b106667dc68029e5787bf6d"
  state: STATE_OPEN
  timestamp: 1600332308817668891
  terms {
    closingTimestamp: 1600332369
    enactmentTimestamp: 1600332369
    validationTimestamp: 1600332310
    newMarket {
      changes {
        instrument {
          name: "Aug 2020 GBP vs USD future"
          code: "CRYPTO:GBPUSD/AUG20"
          baseName: "GBP"
          quoteName: "USD"
          future {
            maturity: "2020-09-17T09:41:59Z"
```

**Comment by edd** [comment]
See #603
