### ISSUE TITLE
Market Lifecycle: pending market updates

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#368]
> Once creation of a market is approved via a governance proposal, or (in future) when a market is scheduled to be created as part of a series of auto-generated markets, it enters a pending state prior to being created. A Pending market becomes an Active market when both the enactment date is reached and it has met the minimum liquidity commitment requirement. A market will be cancelled before creation if the maximum time allowed (network param) to collect liquidity is excdeed, if the market reaches its expiry date (if applicable) whilst in a pending state, or via a governance vote.

This section is not ready for dev

**Comment by tamlyn10** [comment]
Closing given this has now been changed and merged with market lifecycle spec work.
