### ISSUE TITLE
Validator governance

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#374]
We need to spec out and understand how validator sets can be changed through governance or punishment or whatever.

# Current state
All validators are known at genesis, and never change.

# Problems
- If a validator goes down, we can't replace them with someone else
- If a new validator wants to join, they can't
- If we want to boot out a validator for being terrible, we can't

# Open or semi open questions
- Who pays the gas for all these changes?
- How do they get voted in?
- Is there a max?
- Is there a min?
- 🥩?

**Comment by edd** [comment]
This is
-  *required for mainnet*. 
- *not* required for a 🤠 Wild-west net, assuming *the validator set for that network would be known in advance*.

**Comment by tamlyn10** [comment]
Thanks @edd - we discussed this at our research hour this morning and I have created a research issue here:

https://github.com/vegaprotocol/research-internal/issues/160

**Comment by davidsiska-vega** [comment]
This will be addressed as part of https://github.com/vegaprotocol/research-internal/issues/160 . Closing.
