### ISSUE TITLE
Trusted party oracles

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#382]
We have https://github.com/vegaprotocol/product/pull/289 which is lovely, but not yet merged. It's great because we understand many extents of data sourcing and what we want to build towards.

But we need simple oracles so that we can settle markets, and we'll need that when people are proposing markets, which is soon.

This will also entail changes to:
- Redefine the oracle structure in Market Framework: https://github.com/vegaprotocol/product/blob/master/specs/0001-market-framework.md
- Which will change the API for Market governance a bit: https://github.com/vegaprotocol/product/blob/master/specs/0028-governance.md
- And of course the oracle spec
- And https://github.com/vegaprotocol/product/blob/master/specs/0004-settlement-at-instrument-expiry.md

**Comment by tamlyn10** [comment]
Need to add in the **Built in Future** spec

**Comment by barnabee** [comment]
```javascript
Future {
    ... 
    settlementPriceSource:  { 
        signedMessage: {
	    sourcePubkeys: ["YOUR_PUBKEY_HERE"],
	    field: "price",
	    dataType: "decimal",
	    filters: [ 
	        { "field": "feed_id", "equals": "BTCUSD/EOD" },
	        { "field": "mark_time", "equals": "31/12/20" }
	    ]
        }
    } 
}


SubmitOracleData {
    key1: value1
    key2: value2
    ...
    feed_id: ZZZZ
    mark_time: 31/12/2020 23:59:59
    price: 100.2
    volume: 100,000
}
```

**Comment by tamlyn10** [comment]
Extra notes for myself:
- Build this for the happy case.. timeout?
- Close the market spec may be reusable for how we unwind a market if oracle price doesn't arrive
- Spec ability to propose a change of oracle

**Comment by barnabee** [comment]
> * Spec ability to propose a change of oracle

NB: ability to propose change of oracle should be a normal market change proposal as the oracle definition is just a product parameter, which is part of the market framework. We'll need to make sure we look at the various threshold categories for various types of parameter change so it's appropriately difficult to change an oracle (may also be differentiation here between what sorts of parameters are set by liquidity providers and which are set by / also require token holders).

**Comment by C0deMunk33** [comment]
According to @candida-d, TPO stands for "Tamlyn, potentially others”

It needs to be here.

**Comment by barnabee** [comment]
FYI: updated example above to be more JSONy like our example transactions
