### ISSUE TITLE
Opening Auction - Distressed traders closeout 

### ISSUE THREAD

**Issue by ponthief** [vegaprotocol/specs#402]
Specify the correct behaviour for the traders positions that would have been closed out during the Uncrossing.
Current implementation closes out the traders on Uncrossing.

**Comment by tamlyn10** [comment]
We need to investigate this but should not block going live.

**Comment by davidsiska-vega** [comment]
Orders get accepted into an auction with margin based on the indicative uncrossing price. It is possible that once auction uncrosses parties end up with under-collateralised positions. These then get immediately closed out. This is expected / correct behaviour (we don't have a better solution).
