### ISSUE TITLE
Should a non allowlisted asset be able to be traded?

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#405]
https://github.com/vegaprotocol/product/blob/master/specs/0031-ethereum-bridge-spec.md#blacklisting

We don’t have an explicit deny list, but we have an allow list. Assets on the allow list can be deposited. Assets that are not on that list cannot be deposited, but can be withdrawn.

This means that if an asset is allowed, and then later it is removed from the allow list, people can withdraw it. But what can they do with their existing balance in the meantime?

- Can a new market using that asset be proposed?
- Can an existing, active market using that asset continue trading?
- Can proposed but not yet enacted markets be enacted?
- Can I place an order in that asset?
- Can margin still be taken in that asset / from the general account in that asset?

The answer to all these at the moment is *yes*, the allowlist only controls the bridge part of an asset. Is that correct?

**Comment by barnabee** [comment]
I am assuming the allowlist is 100% Ethereum side for now, in it's first implementation (i.e. if a user has a balance of it, it works on Vega as normal), is that correct? If so I am comfortable with that being the case and no further requirements.

cc @tamlyn10 @davidsiska-vega do you agree?
