### ISSUE TITLE
Include price constraints in liquidity obligations

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#412]
As per Slack discussion here.. https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1605106283478800?thread_ts=1605103710.470400&cid=CAHA5EX0F

```
if (order.isPegged && order.isFromLiquidityCommitment) {
    order.price = best_price_of(order.price, worst_non_pm_triggering_price)
}
```

**Comment by tamlyn10** [comment]
@davidsiska-vega is this completed now?

**Comment by witgaw** [comment]
It's not, my PR with spec change is still open:
https://github.com/vegaprotocol/product/pull/422
