### ISSUE TITLE
Questions: wash trades either side of the mid

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/specs#418]
In the following scenario ...

| Side | Price | Size | Trader |
|------|-------|------|--------|
| Sell | 10    | 5   | B      |
| Sell | 6     | 5   | A      |
| Buy  | 4     | 5   | A      |

what should happen when trader A places a Buy limit for 5 at the price of 10?

In the same starting scenario what should happen if Trader C places a buy order for 5 at the price 10?

**Comment by peterbarrow** [comment]
Scenario 1: Trader A places a BUY for 5@10 which will first match against the SELL of 5@6 which is a wash trade and will be rejected with nothing being filled.

Scenario 2: Trader C matches against the Sell of 5@6 and is fully filled.

**Comment by campbellssource** [comment]
@peterbarrow 
Scenario 1: What happens to trader A's order @ 6? is it canceled or still on the book?

**Comment by peterbarrow** [comment]
Still on the book.

**Comment by campbellssource** [comment]
okay simple.
I suspected that #vegaprotocol/Vega#2587 was to do with wash trades but perhaps not.
