### ISSUE TITLE
What is a party

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#424]
Make a spec

**Comment by davidsiska-vega** [comment]
“Party” is any entity participating on Vega blockchain with one-to-one mapping between a Vega wallet public key and “party”. 

Also known as user / trader / participant / voter.

A non-exhaustive list of what is kept on Vega blockchain on per-public-key basis:
- accounts and balances
- orders per market 
- positions per market 
- governance proposals
- liquidity provider commitments per market



@barnabee / @tamlyn10  I can make a 10 line spec file saying the above.

**Comment by edd** [comment]
@davidsiska-vega I wrote https://github.com/vegaprotocol/product/pull/425/files as a start. Feel free to use that, or close the PR and write your own

**Comment by davidsiska-vega** [comment]
@edd 👍 .
