### ISSUE TITLE
change governance spec to use network parameter for minimum proposer balances

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#428]
We currently just say the proposer needs to have greater than zero of the governance token... but have decided that it should be controllable to help with anti proposal spam.

**Comment by tamlyn10** [comment]
@jeremyletang let's cover this off when we do the network parameters spec work

**Comment by davidsiska-vega** [comment]
Spec merged, already implemented. Proposer has more tokens than 
![image](https://user-images.githubusercontent.com/62546419/113166728-f8829d00-923a-11eb-80fa-ab658f65ccad.png)
