### ISSUE TITLE
Price monitoring: let's imply bounds from the "monitoring price"

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#434]
@witgaw following a discussion with @tamlyn10 and @barnabee we are thinking that always implying the bounds from the monitoring price is probably the more intuitive thing to do. We should also do volume weighted averages as you mentioned. 

This shouldn't hold up the release so you can update the spec and then create a core ticket and update the implementation... 

The other thing is, as you mentioned, to use a multiplicative scaling factor for deriving the bounds instead of an additive delta.

**Comment by witgaw** [comment]
Ok, so we'd still use the periodic update from the risk model, but we'd imply the (multiplicative) moves from the historical price and not the latest one, right?

**Comment by davidsiska-vega** [comment]
Yes, update from the historical price. 

The advantage of using multiplicative moves from historical price is that these scaling factors don't change unless risk or price monitoring parameters change. So we can keep a periodic update but it doesn't have to be frequent. I've added a tab to the Excel spreadsheet to show the calculation: https://drive.google.com/file/d/11AGvFkzpoSqJJ2vczdRMvd4blGkTFsdX/view?usp=sharing (best in Excel probably). 

On the quant risk model end no change should be needed because the multiplicative factors are what it returns for price of *one* (I think).

**Comment by witgaw** [comment]
PR with spec change: https://github.com/vegaprotocol/product/pull/435.
PR with code change: https://github.com/vegaprotocol/vega/pull/2715.
