### ISSUE TITLE
Snapshots / fast syncing

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#451]
Need to evaluate speed of sync vs network lifespan

(note, this was a post WWN task that was surfaced in the Mainnet 2 spreadsheet)

**Comment by edd** [comment]
CCing @peterbarrow, @jeremyletang  & @gchaincl who have all been interested in this in the past

**Comment by jeremyletang** [comment]
> (note, this was a post WWN task that was surfaced in the Mainnet 2 spreadsheet)

what does that mean? Is it still post mainnet? I’m slightly confused with naming.

**Comment by edd** [comment]
@jeremyletang https://github.com/orgs/vegaprotocol/projects/12#card-48325998

WWN is ‘real money, but not much of it’

**Comment by qustavo** [comment]
Related to https://github.com/vegaprotocol/VIPs/pull/1
