### ISSUE TITLE
Specify Block Explorer

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#453]
This is a web application for inspecting transactions on Vega.

Current implementation
https://explorer.vega.trading/blocks/3192797

- [ ] Output is a spec that includes functionality and acceptance criteria

**Comment by tamlyn10** [comment]
@tamlyn10 to organise a community call to collect requirements.

**Comment by tamlyn10** [comment]
@tamlyn10 make a start, or set up a call.. @lewisb11 to help, too!

**Comment by davidsiska-vega** [comment]
☝️  Tamlyn will set up a meeting... Friday 19th with a bit of luck.

**Comment by gordsport** [comment]
Jeremy to review this spec

**Comment by gordsport** [comment]
The current direction of this is that the current block explorer will be fixed and have some minor improvements made. Once this is done we will be in a better place to:
- decide of this is sufficient for Oregon Trail (trading on)
- make informed decisions on what we really want from a Vega block explorer

Once this is done this ticket to write a spec can be prioritised

**Comment by edd** [comment]
This is blocked by https://github.com/vegaprotocol/explorer/issues/18

**Comment by davidsiska-vega** [comment]
We have a block explorer without a spec. That's cool. 

https://explorer.fairground.wtf/
