### ISSUE TITLE
Real world data sources

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#462]
Analysis to provide useful input into the business decision around how we implement the data sourcing framework.

- [ ] form a view of potential markets and oracle data sources / landscape in the next 6 months
- [ ] evaluate oracle data sources that have been implemented in the ecosystem (technical side of things)
- [ ] enegineering to review specs and form more deatiled view on implementation.

**Comment by edd** [comment]
Ticket superseded by #450
