### ISSUE TITLE
Fractional orders

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#469]
**Fractional order and position sizes (Needs a spec)**
  - Orders and positions can be fractional with a configurable by market number of decimal places
  - Validate order sizes are a non-zero multiple of the smallest increment (i.e. for a 4 decimal place market, a multiple of 0.0001)
  - Positions and margin work correctly with fractional orders
  - For engineeering: can be implemented with a decimal data type or uint[256?] same as for amounts

**Comment by barnabee** [comment]
Need to decide if we want API where we have "stringed-numbers" to include decimal points for order sizes? i.e. on a 4 d.p. market is an order to buy 0.25:

1. `"2500"` (the default)
2. `"0.25"`
3. Some way that allows both i.e. via different field names

NB: this is also an option for prices and amounts we we could consider, separately.

**Comment by edd** [comment]
I duped this ticket by mistake. https://github.com/vegaprotocol/vega/issues/3005 is relevant.

**Comment by davidsiska-vega** [comment]
@barnabee says he'll finish spec today.

**Comment by barnabee** [comment]
For review: https://github.com/vegaprotocol/specs/pull/514
