### ISSUE TITLE
Limited network life spec

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#470]
A spec for limited life networks.
- How to finally settle/unwind/do withdrawals after the end
- Migrating balances between network runs

We should consider whether this is a protocol spec or non-protocol spec (or bit of both), and how an emergency shutdown could utilise the mechanims.

**Comment by barnabee** [comment]
Old / other issue https://github.com/vegaprotocol/research-internal/issues/190

**Comment by tamlyn10** [comment]
@tamlyn10 to make a start...

**Comment by edd** [comment]
@barnabee will take a look at this today perhaps (hamburger dependent)

**Comment by davidsiska-vega** [comment]
@barnabee to merge bullet-pointed start into spec repo, ping @davidsiska-vega, who will do another iteration.

**Comment by barnabee** [comment]
Over to you @davidsiska-vega 

 https://github.com/vegaprotocol/specs/pull/515

**Comment by davidsiska-vega** [comment]
@davidsiska-vega to organise a meeting with @jeremyletang to progress this.

**Comment by davidsiska-vega** [comment]
@jeremyletang we will meet in London to finish this.
