### ISSUE TITLE
Identify which spec files to release to LPs and how 

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#474]
As part of our MLP programme, to aid with integration of their systems with Vega, we want to improve our docs. Part of this (to avoid the docs needing to become overly complicated and replicating specs) we think that giving MLP members access to some of our spec files will be useful and this can be seen as a first step towards open-sourcing the product repo. 

Which specs - open to discussion - how about as a minimum:
- 0044-lp-mechanics.md
- 0029-fees.md
- 0038-liquidity-provision-order-type.md 
- 0041-target-stake.md
- 0042-setting-fees-and-rewarding-lps.md 
- 0034-prob-weighted-liquidity-measure.ipynb 

The fewer we choose the quicker can we re-read and polish. 

Another question is how? Should we 
a) set-up a public spec repo, explain that we will be moving the specs to public domain as we tidy them up and start with the above? This creates a bit of confusion about where to look for spec files... and may break some links across specs (we should *not* keep a public and private copy of the same spec IMO). 
b) simply take a snapshot, zip it up and email them? If there is a material update we will send them an updated bundle? 

@barnabee @edd @tamlyn10 @witgaw

**Comment by davidsiska-vega** [comment]
@candida-d kindly offered to proof-read - but let's decide the scope first.

**Comment by edd** [comment]
It’s all mirrored now
