### ISSUE TITLE
Full Set of Validator and Staking Specs

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/specs#475]
Brainstorming board: https://github.com/orgs/vegaprotocol/projects/65?fullscreen=true

| **Feature** | **Spec ticket**|**Board ticket**| **Status** |
|---------|:-------------:|:--------------:|--------|
|  Epochs |  [#485](https://github.com/vegaprotocol/specs/issues/485)            | [1.](https://github.com/orgs/vegaprotocol/projects/65#card-54637947)             |  Ticketed     |
|  Vega <> Tendermint interface |  [#485](https://github.com/vegaprotocol/specs/issues/485)            | [1.](https://github.com/orgs/vegaprotocol/projects/65#card-54637947)             |   Ticketed |
| Simple performance metrics hooks        |   [#491](https://github.com/vegaprotocol/specs/issues/491)           | [2.](https://github.com/orgs/vegaprotocol/projects/65#card-54637971)             |   Spec draft     |
| Simple staking        |   [#492](https://github.com/vegaprotocol/specs/issues/492)           |     [3.](https://github.com/orgs/vegaprotocol/projects/65#card-54637996)            |  Not started      |
| Simple payouts |   [#493](https://github.com/vegaprotocol/specs/issues/492)           |     [6.](https://github.com/orgs/vegaprotocol/projects/65#card-54638041)            |  Not started      |
# Outline
What @Vegaklaus’ [research paper gives us](https://github.com/vegaprotocol/research-internal/blob/master/validator_rewards/ValPol.pdf) is a guide to where we’re going. What @barnabee’s [scope message](https://github.com/orgs/vegaprotocol/projects/65#card-55923190) gives us is a scope for what is required for [🤠 Wild West Net](https://github.com/orgs/vegaprotocol/projects/58) to go live is _specifications for what we’re actually going to build next release_. The research paper covers a lot of the high level, but doesn’t make enough decisions about the details for it to be ready for ticketing / working on. So this ticket is the starting point for gathering all of that.

**Comment by edd** [comment]
Given the blank starting message, I’m going to start editing in what is required

**Comment by edd** [comment]
<img width="1490" alt="F0046E21-473B-43AE-83C1-6731F885E7B0" src="https://user-images.githubusercontent.com/6678/110986947-460b9880-8366-11eb-81ec-f682f863e8e2.png">

A mind-map representation of https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1613581276303300?thread_ts=1613575969.302500&channel=CAHA5EX0F&message_ts=1613581276.303300

**Comment by gordsport** [comment]
Closing as we will track the individual validator ticket progress
