### ISSUE TITLE
Clarify Market Life Spec vis-a-vis what happens after settlement

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#476]
We need to make sure that after settlement the insurance pool is distributed to other markets on Vega or to holding accounts for the asset... and we need to run the last fee distribution round as per fees spec. LPs bond account amounts should also be transferred to their general account (maybe after the last fee distribution run since they determine their equity-like-share).

**Comment by tamlyn10** [comment]
@tamlyn10 to add to market lifecycle:
- bond amount returning
- commitment no longer exists
- market data structure ceases existing in the core..
- delayed fee payment run.. add test scenario / acceptance criteria to fees post settlement...
