### ISSUE TITLE
Tendermint interface (weighting) Validator CRUD

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#485]
Short version: we need a spec for the blockchain commands required for validators to join and leave the network. @gchaincl's summary is below:

1. **Tendermint Interface (weighting)** 

Needs spec :page_facing_up: 

@gchaincl

* Create tendermint Validator api calls (AddValidator, RemoveValidator, UpdateValidator (changes stake)) (Note: not transactions, this is the linkage between us and tendermint)
* Handle Add New Validator
  * Weigth redistribution
* Handle Remove New Validator
  * Handle no validators left
* Handle Update New Validator
  * Remove + Add ?
* Integrate testing with Tendermint's Validator API

**Comment by gordsport** [comment]
Closing as covered in validator specs
