### ISSUE TITLE
Validators: Simple performance metrics hooks

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#491]
> 2. **Performance measurement hooks
> We need to be able to measure per validator if a validator is useful or not.

# @Vegaklaus’ outline
 My first thought would be
- A function that devies on who contributed to a block derived from chain data (if the signatures certifying a block are in the order of arrival of the corresponding messages, that could be added)
- A validator keeping statistical data on the order and time of tendermint-internal messages arriving and for now logging that data
- point-to-point communication times between validators for reference

# Scope
> Performance measurement to collect data for future phases

See #475. Scope set by @barnabee [here](https://github.com/orgs/vegaprotocol/projects/65#card-55923190)

**Comment by tamlyn10** [comment]
@ashleyvega taking the lead on writing this spec..
