### ISSUE TITLE
Simple staking

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#492]
**3. Implement simple staking**

* You will still own the tokens that you have delegated Delegated tokens are still valid for voting
* This changes over [https://github.com/vegaprotocol/specs/issues/485](epochs) - pre-defined, multi block periods. It is not clear if Tendermint already supports this

**Note** Putting up stake to become a validator is the first transaction in the process of becoming a validator. Stakes will be evaluated at the end of the epoch and the set will change a result.

# Scope
> * Stake + Delegate txns (do not need to affect TM validator weight but are used for [reward calcs](#493))
> * Lock staked/delegated tokens so they can’t be withdrawn, transferred, or used as margin (i.e. put them in a staked/delegated funds account) until unstaked/undelegated (by staking or delegating zero)
> * Lock staked/delegated tokens can be used for governance voting
> * Calculation and distribution of validator rewards based on staked plus delegated  (#493)
> * NB: much of the rules around when/how you can stake/delegate, max amounts, etc. could be deferred to a future phase I think as they only effect rewards at this point

See #475. Scope set by @barnabee [here](https://github.com/orgs/vegaprotocol/projects/65#card-55923190)

**Comment by tamlyn10** [comment]
@jeremyletang to start this spec.
