### ISSUE TITLE
Simple rewards payout (for validators & delegators)

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#493]
**3. Payout for validators & delegators**

> This is based on the amount of stake that the validators have

# Scope
> * Calculation and distribution of validator rewards based on staked plus delegated (could be a simpler tactical calc than the final curve if needed or it’s not defined)

See #475. Scope set by @barnabee [here](https://github.com/orgs/vegaprotocol/projects/65#card-55923190)

**Comment by edd** [comment]
# Open questions
- The original ticket mentions payouts for stalkers and for validators. Are both of these going to be implemented in the version version @barnabee 
- What account type are validator fees paid too? @barnabee 
- What is the simple calculation we can do? @barnabee or should we do the whole thing as set out in the research paper? @Vegaklaus 

Note that: Payouts are done at the end of the epoch, which is not yet decided on: #485. Obviously this also depends on staking, #492.

**Comment by tamlyn10** [comment]
@barnabee @Vegaklaus to answer @edd 's  questions.

@jeremyletang will progress this spec.

**Comment by davidsiska-vega** [comment]
@jeremyletang will look when "Flamenco Tavern stuff is done".
