### ISSUE TITLE
Governance proposals modifying more than one parameter

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#512]
We have acceptance criteria in 
https://github.com/vegaprotocol/specs/blob/master/protocol/0028-governance.md#market-change-proposals 

that says 
```
Market change proposals can only propose a change to a single parameter
```

To me that seems impractical as e.g. meaningful changes to the risk model might change more than one parameter at a time (and changing single parameter would be wrong). @barnabee care to comment? Is this something we wanted at some point and I forgot why?

**Comment by barnabee** [comment]
I think the preference was to be able to change any subset of params for a market (at least within the same category), not just one. I think @edd may have added this acceptance criteria and I have a vague memory that engineering perhaps desire to initially build this as being only able to change one thing at a time cc @jeremyletang. 

I'm also not entirely sure whether risk model params would be considered one market parameter containing all the values or several, one for each value, but I suspect _possibly_ the former, which would make this a bit less of an issue. Though honestly still not great to be unable to batch market updates together in a governance proposal. (Less of a problem that network params have to be changed individually, though.)

**Comment by edd** [comment]
> I think @edd may have added this acceptance criteria

I added it really as an afterthought - it was something I *thought* was implemented already, so really I was standardising ticking off acceptance criteria that was in there. I may have assumed too much.

**Comment by barnabee** [comment]
Sounds like we should firm up the spec here to be explicit, and set acceptance criteria. We might not get to it right now if there's a gap to current implementation but probably worth having no room for ambiguiity.

**Comment by davidsiska-vega** [comment]
In that case I'd like to make it specifically that a proposal may change any number of parameters in one go.

**Comment by pennyandrews** [comment]
This ticket relates to #293 and should be considered together.

**Comment by davidsiska-vega** [comment]
1) The way the market parameters updates are spec'd already (not implemented yet) should allow multiple parameter update. 

2) For any network parameters that we think should be updated together: treat them as a single parameter that's e.g. a list of key-value pairs e.g. 
```
{
TargetStakeTriggerRatio : 0.7
StakeToCCYSiskas : 0.2
ProbabilityOfTradingTauScaling : 10
BondPenaltyParameter : 0.0001
}
```  
This will be done as part of https://github.com/vegaprotocol/specs/issues/293. 

Btw. I think the only ones at the moment that should be a struct are those related to LP provision. @barnabee @tamlyn10 @edd
