### ISSUE TITLE
Spec Coinbase oracle service

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#541]
https://github.com/vegaprotocol/vega/issues/2864 was written with the expectation that this could be a really dumb service. Given the discussion in the comments and on Slack (ref: https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1621594032027500) this isn’t ready to be built yet. Let’s decide what we want first, and then build it.

# Tasks
- [ ] A non-core spec that specifies how we should be fetching https://docs.pro.coinbase.com/#oracle, and how it should do that based on the market specs rather than just blindly posting data

**Comment by barnabee** [comment]
### Pre-spec

Coinbase oracle service must:

- Either:
    - Have definable "well known" time intervals (i.e. every minute on the minute, rather than 60 seconds from when the last update process completed, which is an arbitrary time) so that market creators know what end times they can use on markets and rely on this service; or
    - Extract the timestamps of interest from filters defined on active data sources on the network via the data source APIs, and use these
- Query the [Coinbase] API to retrieve oracle data payloads for the exact intervals/timestamps that are defined. 
- If it's possible there's no oracle data for a timestamp, then when and if it has confirmed that there won't be (e.g. seen later data, perhaps), it should take two such payloads, the last one before the timestamp and the first one after the timestamp.
- Submit the payload(s) to the Vega blockchain immediately

**Comment by tamlyn10** [comment]
@barnabee thanks, that's helped me understand this service better. WRT your first point - the either / or, IMO from a market creation usability perspective, the definable "well-known" time intervals makes a lot of sense to me in terms of satisfying 99.9% of the market creation use cases on Coinbase data (so long as high enough resolution such as every minute). That way we can create a really nice guide on what's available for market creators via this service. Very cool.

**Comment by gordsport** [comment]
closing as covered in datasourcing
