### ISSUE TITLE
Open sourcing specs

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/specs#545]
- links only from discussion, not blogs, not docs (yet).
- add license, README, WARNING: incomplete, some unimplemented, ...
- can we have files public but issues not public
- information source for public of last resource 
- list places where implementation diverges from the spec significantly 
- do we open source the whole repo or move to a new repo? Or use github pages to build content of spec directory?  

@edd reorganized the spec repo... there is an overview in the README.md which is very good.

@edd says we need to improve linking among specs.

Tasks:
- [ ] make a new repo for protocol specs, set to no branches and pull requests. Enable issues
- [ ] periodically mirror current internal spec repo to the external spec repo.  
- [ ] current repo to be renamed to `specs-internal` new spec repo to be called `specs`. 
- [ ] Add a BIG warning saying could be out-of-date, unclear, ask questions, raise issues. 
- [ ] MIT license

**Comment by ashleyvega** [comment]
duplicate of https://github.com/vegaprotocol/devops-infra/issues/539 ?

**Comment by davidsiska-vega** [comment]
I am closing this now: we're mirroring what we want to mirror to an open repo and that's probably as far as we need to go at this stage.
