### ISSUE TITLE
Cash Settled Futures spec improvement: examples of trading_termination_trigger as an external data source

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#557]
[The spec for Cash Settle Futures says](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0016-product-builtin-future.md#1-product-parameters):

> trading_termination_trigger (Data Source): triggers the market to move to trading terminated status ahead of settlement at expiry (required to ensure no trading can occur after the settlement result may be known by participants). (This would usally be a date/time based trigger but may also use an oracle.)

Looking at the [current implementaiton](https://github.com/vegaprotocol/vega/blob/82919bc45e9a99105c1059e6cc360090a1baad5b/proto/markets.proto#L47-L49) it looks like it can *only* be an oracle spec. We need someone in  @vegaprotocol/core to verify if this matches what the spec wants, and how we support it, and then work out what tests we need to add for this. This is part of the work on Settlement at Instrument Expiry.

# Tasks
- [x] Establish if the current implementation can support what the spec outlines
- [ ] Add Feature Tests that walk through both data and oracle based trading termination trigger

**Comment by barnabee** [comment]
Not sure if this is understood or not but in case it isn't clear, the way we've specced the time based trigger is that it's just another type of data source: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0048-data-source-internal.md#12-time-triggered

That is, time based is not a special case of a product/the protocol has no time triggering logic in it. This will be important when we add new built-in products and eventually user defined "smart products".

**Comment by edd** [comment]
@barnabee great - I think it’s just a wording / acceptance criteria / feature tests tidy up task. I’ve ticked the relevant tickboxes

**Comment by witgaw** [comment]
@gordsport it seems that Edd's diagnosis from the issue description still holds - I don't really see an internal oracle implemented. Not sure what next steps should be, probably one for protocol design meeting to discuss.

**Comment by gordsport** [comment]
Closed as this has been implemented
