### ISSUE TITLE
Market data API change: target stake

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#569]
Market data API currently always displays the target stake based on current open interest.

This can lead to markets which are in liquidity monitoring auction, but the market data can display target stake and supplied stake such that `supplied stake` >= `target stake` which may be confusing for users.

I’d like to change it so that whilst in auction `target stake` field contains the theoretical target stake that would be attained if the current indicative volume were to be realised - that way LPs know exactly how much extra stake is needed.

Does that sound sensible?

**Comment by barnabee** [comment]
Yes, good spot! Target stake should be the amount of stake required to not be in a liquidity monitoring auction, so when in an auction of any kind should the target stake assuming the OI that would be realised if the auction were to uncross now.

**Comment by witgaw** [comment]
Perfect, thanks a lot. Will follow-up with a spec change PR shortly.

**Comment by ashleyvega** [comment]
@witgaw It sounds like you're suggesting using the same field (`target_stake`) for different purposes.

Should we have an extra field, perhaps `thoretical_stake` / `indicative_stake` / `realised_stake`, which would be the same as `target_stake` outside auctions and different during auctions?

**Comment by barnabee** [comment]
@ashleyvega no, the above is just the correct definition of the target stake, there is only one target stake and during an auction it needs to apply the indicative uncrossing to OI (by definition target stake defines what's necessary to not be in the auction)

**Comment by barnabee** [comment]
at least that's how it works in my head... I don't think there's any other purpose for target stake so the version not taking into account the auction is not useful for anything... unless anyone has another view?

**Comment by witgaw** [comment]
I'd stay with one field. Target stake is in some sense whatever we say it is: it's a derived quantity which is currently related to the open interest, but it may not be in the future and it's main purpose is triggering the entry/exit of liquidity monitoring auction.
