### ISSUE TITLE
Possible spec bug with prob of trading

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#571]
At the moment in 0034-prob-weighted-liquidity-measure.ipynb we have

![image](https://user-images.githubusercontent.com/62546419/121247794-8eb9eb80-c89a-11eb-8dad-dcbf50f9d1b6.png)

I'll explain the problem on the `x > S` case but the other case is mutatis mutandis the same. If `x_max` is close to `x` then the probability of trading will be artificially low - but that's bonkers. What we need to do is either of:
a) re-weight by the probability contained in the `x_min` to `x_max` integral i.e. divide by `\sum_{x_min \leq x' \leq x_max} f(x')`
b) ignore the x_max in the sum and replace it by infinity.

**Comment by witgaw** [comment]
approach a) looks good to me, it then just becomes a truncated distribution of x on [x_min, x_max] which is what it is really.

**Comment by davidsiska-vega** [comment]
Cool Witold, thanks! Let me do the spec edit and then we coordinate with engineering about how to implement it. 

I think the change is only on the quant side but it may impact their integration and other tests.
