### ISSUE TITLE
Add a CI step for feature tests

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#595]
See: https://github.com/vegaprotocol/vega/issues/3467

**How to run it as a CI step on`vega` repo** (there might be a way to run it without copying across repos, but I don't know what it is (godog is quite picky about how directories are specified from what I remember):
```bash
cd vega
git clone git@github.com:vegaprotocol/specs-internal ../specs-internal
mkdir ./integration/feature_tests/
find ../specs-internal/qa-scenarios -name '*.feature'  -exec cp -prv '{}' './integration/feature_tests/' ';'
go test -v ./integration/... -godog.format=pretty $(pwd)/integration/feature_tests/*.feature
rm -rf ./integration/feature_tests
rm -rf ../specs-internal
```

**How to run it as a CI step on`specs-internal` repo**:
Same above, just clone `vega`, checkout `develop` and run the current version of tests in `specs-internal` repo.

**Comment by fkondej** [comment]
it got closed automatically. I need this one to be reopen until @witgaw gets back and gives his feedback.
