### ISSUE TITLE
Add loss socialisation walkthrough

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#601]
Our settlement spec (https://github.com/vegaprotocol/specs-internal/blob/45409da8afe00240b6e1daf94c1f821af1feb18c/protocol/0002-settlement.md) has a link to a loss socialisation spec that doesn't exist. Clearly the intention was to write up how it works, but we never got there. We should add it. 

I think the Settlement spec is a fine place to have it, so a title works just as well as a new spec. If it becomes massive, it could also split out.

**Comment by edd** [comment]
Here's the relevant whitepaper section:  

# 5.3 Position resolution
When a trader’s liabilities in a market — comprised of any outstanding settlement cashflows plus the required margin for their active orders and open positions — are found to be greater than their available collateral, their position will be called distressed and the position resolution algorithm will be invoked to unwind their obligations.

When a market has one or more distressed positions, it is in a potentially unstable situation in which essentially randomly selected counterparties could experience large losses without warning. We solve this problem by designing Vega such that in reality, all trades are back-to-back trades with the decentralised network itself acting as the intermediary, and the pool of funds available. Given that open markets are pseudonymous and it is not possible for traders to be selective about the identity or creditworthiness of their counterparties. to a market being limited to the total collateral allocated to the risk universe (see Section 3.5) and the market’s insurance pool to protect the network from contagion between markets. The position resolution algorithm defined below attempts to ensure that distressed positions are closed fairly and deterministically, to minimise the risk of excessive impacts on any individual participant from a defaulting trader, and to protect the market as far as possible in volatile and illiquid situations. The algorithm is based on three key principles:
* credit events should impact the whole market, not individual counterparties;
* distressed positions never threaten other markets or an entire Vega network; and
* in the event of uncovered shortfall after exhausting available collateral and the insurance pool (see Section 6.4), contributions by profitable traders will be based linearly on their profitability.

## Position resolution algorithm
When position resolution is required, we must first evaluate all outstanding settlement instructions to ensure that all distressed positions have been identified, after which the following process is executed in order:

1. Open orders are cancelled, oldest first. Participants with remaining distressed positions at this point, after closing all open orders, will lose all of their collateral that is allocated to the risk universe, regardless of any remaining balance after closeout trades.
2. The net closeout volume NCV is calculated as: `NCV = Long Closeout Volume − Short Closeout Volume`, where Long Closeout Volume and Short Closeout Volume are the sum of the volume of distressed long positions and distressed short positions respectively.
3. A market order is placed for the absolute net closeout volume unless NCV = 0; the order is a sell if NCV > 0, otherwise NCV < 0 and a buy order is placed.
4. Any shortfall between the settlement cashflows for the closeout trades and the traders’ available collateral is paid out of the insurance pool, and any remaining collateral after settling the closeout trade is transferred to the insurance pool.
5. In the event that the insurance pool’s (see Section 6.4)collateral is exhausted with unpaid settlement cashflows still outstanding, the final remaining shortfall will be made up through contributions from market participants with profitable open positions. The relative contribution of each trader holding an open position takes into account their relative (unrealised) profitability and size of their open position.

Note that during this process, market protection measures such as those that protect against excessive price moves and low liquidity remain in effect and could result in the market being suspended or entering a price discovery auction before the closeout process completes

**Comment by candida-d** [comment]
I think the merged PR above covers this, but I'm mainly commenting so I get notified, because I'd like to incorporate any subsequent changes to the [protocol docs draft](https://github.com/vegaprotocol/documentation/blob/main/docs/trading-concepts.md#settlement).
