### ISSUE TITLE
Spec bug: Sweetwater assets not in genesis, training wheels prevent asset proposals

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#604]
https://github.com/vegaprotocol/specs-internal/blob/master/non-protocol-specs/0003-limits-aka-training-wheels.md#sweetwater

> 2. Prevent the submission of asset addition proposals until a validator initiated and agreed change (i.e. a genesis/config/code change required rather than a network parameter)

While Limited Network Life (https://github.com/vegaprotocol/specs-internal/pull/590/files#) says:

> The state will be restored in this order: [snip]
>     2. If the asset coming from the restore file is a new asset (asset id not matching any genesis assets) then ignore the restore transaction. 

And in the comments @davidsiska-vega says:
> There will be no genesis markets and no genesis assets except perhaps Vega token for staking.

These can’t all be true. So I propose the fix is in 0003-limits-aka-training-wheels.md, and only submissions for a particular contract address (i.e. VEGA) are allowed. Or I’m wrong and this is not a problem?

**Comment by barnabee** [comment]
So:
1. There will definitely be no genesis markets in any mainnet. Not sure we should support them at all tbh.
2. Vega (and therefore the restore system) does and should support genesis assets. The current intention is to only configure one (the VEGA token in mainnet) but I don't think we should rely on this.

Separately:
* The limited network life spec contained a bug which made it hella confusing. That may have helped precipitate this issue.

I am not sure that any further changes are needed now @davidsiska-vega has fixed the bug?

**Comment by davidsiska-vega** [comment]
Spec bug in limited network life fixed here: https://github.com/vegaprotocol/specs-internal/pull/590/commits/0aa924cb1fd55f3ae5e33641efe175a13a64c198

**Comment by edd** [comment]
I think we're good then!
