### ISSUE TITLE
Will the staking bridge need a different ethereum block confirmation count from the asset bridge?

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#606]
@C0deMunk33 @jeremyletang should tell us whether it's ok to use the same one or we might want to use a different one for some reason (i.e. in case we want extra security on staking or in case we may want to change how we do it for ERC20 bridge, perhaps to choose number of confs dynamically by value)

_Originally posted by @barnabee in https://github.com/vegaprotocol/specs-internal/pull/570#r666078855_

**Comment by edd** [comment]
The current [Ethereum bridge](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0031-ethereum-bridge-spec.md) has a network parameter, `blockchains.ethereumConfig`,  that is a JSON object: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0031-ethereum-bridge-spec.md#network-parameters

e.g.: 

```json
{
  "network_id": "3",
  "chain_id": "3",
  "bridge_address": "0xCcB517899f714BD1B2f32931fF429aDEdDd02A93", 
  "confirmations": 3
}
```

Will the staking bridge need a new network parameter that has its own definition of `confirmations` or will it use this existing one?

**Comment by davidsiska-vega** [comment]
No.
