### ISSUE TITLE
Precisions on the Market suspended state

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/specs#629]
From the specification both a market ina monitoring auction, or a market for which the future product would have receive a settlement price event before a trading terminated event should have a state of SUSPENDED.

Both these situation have a suspended state, but the condition for exit are different, In one case the market would leave the SUSPENDED state by leaving the monitoring auction, in the other case we would expect an action to be done via governance.

Would it make sense use a new state for the market in the second case, and keep suspended only for the market in an auction. In term of implementation these are 2 very different path of execution and the conditions for entry and exit are completely unrelated too.

cc @ze97286

**Comment by barnabee** [comment]
@davidsiska-vega has the [market lifecycle](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0043-MKTL-market_lifecycle.md#trading-terminated) spec been updated to cover this? It doesn't look like it but I may be checking the wrong branch…
