### ISSUE TITLE
Calculation for sweetwater rewards: is it clear enough

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#630]
The rewards spec:
https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0057-reward-functions.md#s1---rewarding-getting-started-with-delegation tells us:

> The reward amounts are calculated using the same formula and code as the staking and delegation reward calculation described in that spec, subject to the application of the max payout amount per participant (public key) if one is specified in the reward parameters (which are controllable by governance)

So we head on over to https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0029-fees.md#collecting-and-distributing-fees, which tells us:

> Infrastructure_fee is transferred to infrastructure fee pool for that asset. Its distribution will be described in simple POS rewards and simple staking and delegation.

The staking and delegation spec doesn’t have any calculations, but the POS rewards spec does (even though the links is broken - **update: fixed**)

https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md#calculation

So is it clear enough how this applies directly to the infrastructure fee? Or do we need anything more?

**Comment by davidsiska-vega** [comment]
My understand is as follows:
1) Fees from trading: collected as per fees spec https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0029-fees.md#collecting-and-distributing-fees into the infrastructure fee bucket. Distributed periodically (are we saying epochs?) according to https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md#calculation . 

2) On chain treasury rewards: deposited into the on chain treasury https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0055-on-chain-treasury.md and periodically allocated to the reward pool for staking. This is a different bucket to the one in 1) above (if nothing else the asset is unlikely to be the same) but it's distributed according to formulae https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md#calculation .

The actual calculation:

> At the end of an epoch, payments are calculated. This is done per active validator:

> First, score_val(stake_val) calculates the relative weight of the validator given the stake it represents.
> For each delegator that delegated to that validator, score_del is computed: score_del(stake_del, stake_val) where stake_del is the stake of that delegator, delegated to the validator, and stake_val is the stake that validator represents.
> The fraction of the total available reward a validator gets is then score_val(stake_val) / total_score where total_score is the sum of all scores achieved by the validators. The fraction a delegator gets is calculated accordingly.
> Finally, the total reward for a validator is computed, and their delegator fee subtracted and divided among the delegators.

The functions are defined further down in https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0058-simple-POS-rewards.md#calculation so I won't copy and paste.

**Comment by edd** [comment]
I agree. @jeremyletang / @barnabee can reopen if it’s not true

**Comment by davidsiska-vega** [comment]
@Vegaklaus I've put my understanding of what the reward distribution spec means into a `go` file: https://github.com/vegaprotocol/specs-internal/blob/ecc60c40e8c1aabdc023d151e2c229ef675d7424/valRewDist.go 

Could you please check whether that's what you meant?

**Comment by davidsiska-vega** [comment]
@Vegaklaus , I am looking at "`stake_val` is the stake that validator represents." Is this number of tokens OR a fraction of the total supply?

**Comment by davidsiska-vega** [comment]
And as a follow-up if it's a fraction, is it a fraction of total supply (ie total number of Vega tokens) OR is the denominator the total staked + delegated tokens?

**Comment by davidsiska-vega** [comment]
So @Vegaklaus I think you want the input to validator score as a fraction of the number of tokens as the output turns negative quickly, certainly for numbers bigger than one:
![image](https://user-images.githubusercontent.com/62546419/126804301-ec1ebd21-b666-4cd7-b3c0-75450ff2bc0b.png)

**Comment by davidsiska-vega** [comment]
You can play with it here (ignoring the approximation part further down): https://github.com/vegaprotocol/specs-internal/blob/a8ec7a80183c8beaa9f72a3eae69ab7ab56046c4/protocol/0058-simple-POS-rewards-approx.ipynb

**Comment by Vegaklaus** [comment]
> @Vegaklaus , I am looking at "`stake_val` is the stake that validator represents." Is this number of tokens OR a fraction of the total sup

It's probably easier to normalise it early, so if it works with rounding let's make it the fraction (and you're right, the formular right now assumes it's normalised)

**Comment by Vegaklaus** [comment]
> And as a follow-up if it's a fraction, is it a fraction of total supply (ie total number of Vega tokens) OR is the denominator the total staked + delegated tokens?

Number of totally staked+delegated tokens.

**Comment by Vegaklaus** [comment]
I updated the code to get the adjustment right and get rid of  the floating sqrt calculation:
https://github.com/vegaprotocol/research-internal/blob/master/validator_rewards/val2.go

It should be functionally correct now, but can be simplified a bit if we treat the validators own stake as if they are also delegators that also delegate to them (i.e., from the point of view of the reward delegation there is no
own stake - all stake is given to delegators, and some delegators just happen to have the same account as the validators).
Note that we have a whale in the test data (with 37% of all stake), who ends up getting no reward at all.

**Comment by davidsiska-vega** [comment]
@Vegaklaus can you make a pull request and capture what's in `val2.go` in the actual simple-POS-rewards spec? You can put the go code in an "Appendix" of the spec and say: "see the go code below". But let's be clear about what's a fraction and what a total etc to avoid any confusion.
