### ISSUE TITLE
Jenkins on #protocol-design

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#660]
Can we please re-tune Jenkins on #protocol-design so that it only prints failed CI steps? Many thanks in advance!

**Comment by fkondej** [comment]
Please move the ticket to that repo.
The Slack messages can be configured in Jenkinsfile in that repo: https://github.com/vegaprotocol/specs-internal/blob/aff96fbbcf7581a0695fb881f71a7be124138a9e/Jenkinsfile#L67-L77
