### ISSUE TITLE
Additional test case coverage for delegation

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/specs#680]
Additional test case coverage for delegation and rewards suggested by Klaus

1. A validator gets past the maximum stake
- This can happen in several ways:
- Network parameters change (e.g., the competition factor)
- Estimation of delegated stake was wrong (we allow a slightly imprecise calculation for simplicity)
- Something somewhere else went wrong

2. The maximum allowed stake changes (Through parameter changes or a validator leaving)
- 2.1 someone delegates an amount that would fit the old max and not the new
- 2.2 someone delegates an amount that would fit the new max and not the old

3. Competition factor is changed
- 3.1 Increase (less critical)
- 3.2 Decrease (some validators might be thrown into case 1)
- 3.3 Massive decrease (the entire economics changes)

4. The number of validators becomes lower than minval [to be picked up later]

5. Every block in that epoch is full of delegation/undelegation commands
- This would essentially be a stress-test for the block evaluation
- 5.1 The same party delegates and undelegates a lot within one block

6. A delegator undelegates in the same epoch in which it unlocks tokens

7. A delegator delegates tokens in the same epoch in which it unlocks them
- 7.1 The deleggator first unlocks (thus auto-undelegating dome tokens, then tries to undelegate the oritinal amount

8. Validator drops below self owned threshold

9. Validator owns sufficient otkens, but delegted to soemone else.

10. A delegator owns less than the delegated stake (it sold of the rest0), and tries to redelegate

Genesis:
- 11.noone delegates in the first epoch
- 12.very few people delegate in the first epoch
- 13.All delegation in the first epoch goes to the same three validators

**Comment by witgaw** [comment]
Perfect, thanks for raising the issue @cpuja84.
