### ISSUE TITLE
Specify null blockchain with time fast forwarding

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#724]
Spec proposal: https://github.com/vegaprotocol/specs-internal/pull/713

**Comment by witgaw** [comment]
As far as the minimal scenario runner goes we'd probably want to be able to make arbitrary deposits & delegations so the bridge functionality would need to be mocked - might be that it's a separate ticket, not sure.

**Comment by jeremyletang** [comment]
> As far as the minimal scenario runner goes we'd probably want to be able to make arbitrary deposits & delegations so the bridge functionality would need to be mocked - might be that it's a separate ticket, not sure.

Indeed, the null blockchain as it used to be would not work anymore. We would need to get a bit more work done to mock the blockchain, and some external dependencies now.

**Comment by gordsport** [comment]
Updating this issue to be the protocol design 💦 task for creating this spec.

Further Issues and project boards to implement this will come when prioritised into a milestone
