### ISSUE TITLE
Clarify how core interacts with ERC20 bridge / multisig

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#727]
When a party wishes to withdraw Vega nodes create a signature bundle for Ethereum ERC20 bridge and decrements the general account balance accordingly. 

It is the responsibility of the party that requested the withdrawal to submit this transaction to Ethereum. If this transaction bundle is lost then the funds are lost.

We should update one of: 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0005-collateral.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0031-ethereum-bridge-spec.md 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0013-accounts.md

to make this clear and cross-ref with the other specs.

**Comment by gordsport** [comment]
https://vegaprotocol.slack.com/archives/CAHA5EX0F/p1635154144057300?thread_ts=1635153845.057200&cid=CAHA5EX0F
