### ISSUE TITLE
Assure qa-scenarios run in CI

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/specs#730]
Assure there's a CI step in this repo to run tests from `qa-scenarios` folder against a branch (latest tag?) in `vega` repo.

**Comment by cpuja84** [comment]
@witgaw to work on versioning and tagging so that features tests could be run on CI

**Comment by witgaw** [comment]
Closing this now:
* After chatting to @fkondej I can confirm that:
  * qa-scenarios are run on `vega` repo on every PR, see: https://github.com/vegaprotocol/vega/blob/5faa8ec5c1bbe0cfe4d03b57b01aa5993be51d6c/Jenkinsfile#L272-L280
  * qa-scenarios are run on `specs-internal repo on every PR, see: https://github.com/vegaprotocol/specs-internal/blob/bf3f430c5336c62870bb47b5254575802007e8c7/Jenkinsfile#L44-L53
  * Tags/versioning are a wider problem that needs to be addressed across all repos that depend on or are dependencies of `vega` so it will be addressed as part of that problem.
