### ISSUE TITLE
Coded features review: LP bond slashing & top-up

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/specs#731]
The scenario tests LP bond slashing and top-up.

So far this has identified a core bug in the slashing part, once it's fixed we'll progress on writing the top-up tests. See progress of vegaprotocol/vega#3632 .

# ToDo:
Penalties for LP providers (aka bond slashing) is detailed in https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0044-lp-mechanics.md#penalties . Other relevant specs are https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0042-setting-fees-and-rewarding-lps.md but note that other aspects (LP orders, equity like share, distribution of fees) has been covered by other feature tests. 

We need to test the situation where the LP doesn't have enough balance across margin and general accounts and the margin account balance gets topped up from their LP bond account. 
- [ ] Test this happens as expected (bond account balance down, margin balance topped up)
- [ ] Moreover at this point a penalty is applied and the penalty amount should go to the insurance pool of the market.

**Comment by cpuja84** [comment]
Hi @Jiajia-Cui - I put this ticket in progress this morning as was told that you are working on it. Please can you confirm if that indeed is the case ? Thanks !

**Comment by Jiajia-Cui** [comment]
Hi @cpuja84 , I am working on it, and I will tidy up and merge once its done :) Thanks ^.^
