### ISSUE TITLE
Spam protection doesn’t cover orders in Sweetwater, but users can place orders

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#737]
https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0062-spam-protection.md#spam-protection explicitly excludes order from the Spam Protection, and it is implemented this way. However I think this was written at a time where we thought Order transactions would be disabled. As a result, I think there’s a minor hole, that’s slightly patched up with Rate Limiting.

Rate limiting is currently set to restrict the same key from sending more than 500 txs within 10 blocks. As long as they stay below this number, they can send as many orders as they like to gum up some blocks. Orders will pass our basic `checkTX`, but then be rejected because there won’t be any markets in sweetwater.

Additionally, we’re considering removing rate limiting, which would leave this wide open. Should we start implementing more of spam protection before removing rate limiting?

**Comment by gordsport** [comment]
close as done
