### ISSUE TITLE
Whitelist large deposits on sweetwater++

### ISSUE THREAD

**Issue by C0deMunk33** [vegaprotocol/specs#738]
Rewards and liquidity providers need to be able to deposit more assets than the lifetime limit restrictions would allow. We either need to build a new mechanism or build a whitelist.

**Comment by davidsiska-vega** [comment]
Defining white-listed Ethereum addresses that are allowed bigger deposits seems technically fine. 

But I wonder if it looks bad from decentralisation point of view in the sense that there are privileged parties ... @barnabee

**Comment by davidsiska-vega** [comment]
Would another option be to have no limits on deposits of Vega? 

In practice no one should need to create markets that settle in Vega / or it can be discouraged via governance. 

If no markets settle in Vega then maybe it's ok to have a large Mac or no limit.

**Comment by barnabee** [comment]
@davidsiska-vega yes def. an option to do that, but that is an extra type of whitelist and it seems to me like we may well need a way to somehow allow community members who are going to create markets to deposit more, and the only option I can think of for that it an address whitelist. Are there any alternatives? Or maybe it's not a problem?

**Comment by davidsiska-vega** [comment]
I think an allow-list (white-list) of ethereum addresses exempted from limits is the best solution. This can be updated to add not just those would would add to the treasury but also those who would become LPs.

**Comment by davidsiska-vega** [comment]
Who would be allowed to add /remove addresses from the allow-list? The validators? An ethereum governance contract that would utilise Vega tokens? Or a single Ethereum key? 

If it's just a single key then it seems to contradict the principles we've set out for ourselves in the network limits:
```
- Must not introduce points of centralisation. They are therefore designed to be operated by decentralised governance protocols in keeping with the core Vega protocol.
``` 

I think potentially using the validator ethereum keys [multisig ones] would be the easiest solution.

**Comment by C0deMunk33** [comment]
@davidsiska-vega I like the idea of just leaving the whitelisting up to the validators using multisig. Some approved parties are not subject to the lifetime deposit limits for the purpose of liquidity or rewards.

**Comment by C0deMunk33** [comment]
if there are no objections, I will implement this

**Comment by barnabee** [comment]
The validator option may be a pain.

I wonder if we could use something like a Gnosis Safe multisig to implement a basic "DAO" in which some key team and community members control this, despite it being a single address that is allowed to change the whitelist?

**Comment by C0deMunk33** [comment]
I can make the function respond to a single address and then you provide the address

**Comment by barnabee** [comment]
Makes sense, I wonder if the address should be settable at deployment by us and then by the validators using multisig control so although we control the whitelisting (initially) the validators are in control of whether or not it remains in our hands so it's less of a centralisation point.

Would that make sense @C0deMunk33 @davidsiska-vega ?

**Comment by davidsiska-vega** [comment]
That makes sense, we initialise the white-list at contract launch. Then it's under control of the same keys as for the multisig contract. 

How will the controlling keys get updated when the validators want to rotate them? Would adding / removing a key on the multisig contract means it's also added / removed for the purpose of controlling the whitelist?

**Comment by C0deMunk33** [comment]
@barnabee so you're saying the validators control which wallet (Gnosis or otherwise) can whitelist liquidity/reward providers? but NOT the whitelisting itself?

@davidsiska-vega if it uses the same contract as multisigControl then it's auto-updated as validators swap in and out

**Comment by davidsiska-vega** [comment]
Okay so to summarise my understanding:
- whitelist is to be controlled by a single Ethereum address
- which address this is will be under control of the multiSig contract and hence under control of quorum of validators

1) Is this correct? 

2) does it mean the multiSig contract will need to change to support this functionality?

**Comment by C0deMunk33** [comment]
@davidsiska-vega that is my understanding as well. 

Multisig control doesn't need to change, just the "change whitelist address" function will need to implement it (just like all our validator-based functions)

**Comment by davidsiska-vega** [comment]
Cool!

**Comment by davidsiska-vega** [comment]
I think we've converged; would you like to do a PR on the spec @C0deMunk33 ?

**Comment by C0deMunk33** [comment]
like to? no. Will I? absolutely!

**Comment by C0deMunk33** [comment]
https://github.com/vegaprotocol/specs-internal/pull/741

**Comment by gordsport** [comment]
#741 merged so closing this issue
