### ISSUE TITLE
Create transfers spec

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#759]
Write spec allowing internal transfers among Vega assets:

It’s probably relatively straightforward
```
transfer(destination vega address, asset, amount)
```

Question: should be a small percentage fee (imagine a situation where nobody uses vega for trading but they keep assets on the bridge and transfer them around. Unlikely - but why would validators / token holders want run the chain in that case. @barnabee

**Comment by barnabee** [comment]
We probably/possibly need a fee, and we definitely need some other way to prevent spam.

**Comment by barnabee** [comment]
I would also like to have the ability to put a date/time in the txn so the funds leave the source account instantly but only enter the destination account when the date/time is reached. This would be simple to implement but allow us to have basic locked tokens in the Vega chain which could be used to distribute community rewards there and save on gas for community members.

**Comment by davidsiska-vega** [comment]
Okay we're converging on a spec:
```
transfer(destination vega address, asset, amount, deliverOn=now)
```
Avoiding spam:
- we could have a flat fee per transfer as a fraction of e.g. minimum LP stake; this will avoid spam
- we could have a proportional fee set at the infrastructure fee but a minimum transfer amount set as a fraction of minimum LP stake per asset. 
- we could have a proportional fee set at the infrastructure fee and client-side proof of work to avoid spam. This has the advantage that we can do the client-side-PoW spam protection and use it for orders too.

**Comment by edd** [comment]
~Note that there are already lots of transfers being done internally (see: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0005-collateral.md), so this spec needs to cover existing transfers, as well as user requested/created transfers.~

**Comment by jeremyletang** [comment]
> Note that there are already lots of transfers being done internally (see: https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0005-collateral.md), so this spec needs to cover existing transfers, as well as user requested/created transfers.

I think they are different things. This covers transfers initiated by a user at destination to another account. While the internal transfer are a different thing (they would still both produce transfer responses that can be seen through APIS.)

**Comment by edd** [comment]
@jeremyletang agreed - https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0005-COLL-collateral.md actually already covers internal transfers in sufficient detail
