### ISSUE TITLE
Write specification of the Vega matching engine

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#767]
We have 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0014-order-types.md
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0025-order-submission.md 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0026-auctions.md (matching happens in auctions)
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0033-cancel-orders.md 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0037-pegged-orders.md 
- https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0038-liquidity-provision-order-type.md 

*but* we don't have a spec for the matching engine. 

@barnabee would be the best person to quickly write something down; I am happy to add some acceptance criteria.

**Comment by gordsport** [comment]
Meeting notes: @vega-paul and @peterbarrow to focus on what acceptance criteria we need to QA this and get added to the spec.
