### ISSUE TITLE
Find what functionality we have that doesn't have a spec

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#768]
Find what functionality we have that doesn't have a spec. 

So far we have:

* https://github.com/vegaprotocol/specs-internal/issues/759 (user initiated transfers)
* https://github.com/vegaprotocol/specs-internal/issues/767  

@gordsport / @edd / @jeremyletang / @peterbarrow / @campbellssource any others you'd like to point us to?

**Comment by gordsport** [comment]
@vega-paul FYI 👆

**Comment by peterbarrow** [comment]
If @barnabee is busy I'm happy to turn the current matching engine logic into a spec.

**Comment by barnabee** [comment]
They would be great @peterbarrow! Happy to review or answer any questions

**Comment by campbellssource** [comment]
@peterbarrow I'd like more clarity on price time priority (not sure it's actual name, but how much volume in front of me at this price) I think it can be deduced from the `order.id` and I see `sequenceNumber` on the order book.

**Comment by edd** [comment]
This issue is where I'm going to keep 'scratch' notes, there's a meeting to get organised this week.

* [x] https://github.com/vegaprotocol/specs-internal/issues/854 
  > https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0013-accounts.md mentions staking accounts, but then in the details below does not mention stake accounts
* [x] https://github.com/vegaprotocol/specs-internal/issues/855
  > https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0017-party.md should probably go in to more detail about what a party is in relation to keys. It has one sentence
* [x] https://github.com/vegaprotocol/specs-internal/issues/856 
  > Transaction format
  > https://github.com/vegaprotocol/specs-internal/issues/768#issuecomment-1023546090
* [x] https://github.com/vegaprotocol/specs-internal/issues/857 
  > Transaction lifecycle
* ~Replay protection~
  > (added to #856)
* https://github.com/vegaprotocol/specs-internal/issues/737
* [x] https://github.com/vegaprotocol/specs-internal/issues/858
  > Parking isn't well covered. It is well covered for pegged orders, but needs to be more generic.

**Comment by gordsport** [comment]
@edd, are we able to turn the findings of this into tickets and close this or is there still more investigations underway?

**Comment by edd** [comment]
@gordsport this ticket is a bit of an inbetweeny one. I don't think anyone is currently *actively* looking for places we don't have specs, currently. So I think I'll turn what is here in to tickets, and then we can close this, but obviously that doesn't mean we're *done*. Hopefully the next iteration will come when we have the transaction lifecycle / system architecture mapped out and more unspecced stuff comes up.

**Comment by gordsport** [comment]
I will follow up on where we are with the system architecture diagram.

**Comment by peterbarrow** [comment]
The protobuf command validation code is currently covered with some unit tests but they are not mapped against any acceptance criteria or specs. Some differences between what orders we expect to be able to submit to the wallet and those which is actually can submit is causing a blocker to some matching engine system tests. I think we need to create a spec to cover the functionality in that validation to make sure it agrees with other parts of the system.

Example case: Trying to submit an IOC PEGGED order is rejected by the validation when it should be allowed.

**Comment by edd** [comment]
@peterbarrow ill ticket that one too when I get back to this ticket. Sounds like a job for https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0014-ORDT-order_types.md#valid-order-entry-combinations - the criteria there is pretty sparse, but the table exists (but could be outdated, needs checking, etc)
