### ISSUE TITLE
Replace asset parameter min_Lp_stake with quantum

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#797]
In many places we need to have information about what a minimum economically meaningful amount of an asset is. Often it's not 1 because for an asset with 18 decimals this would be 1e^{-18}. 

Thus we introduce "quantum" as "the minimum economically meaningful amount of an asset". Min_Lp_stake will be removed and replaced by `quantum x min_LP_stake_quantum_multiple`, where `min_LP_stake_quantum_multiple` is a new network parameter.

**Comment by gordsport** [comment]
Development task created: https://github.com/vegaprotocol/vega/issues/4621
