### ISSUE TITLE
Rewards and network treasury simplification

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/specs#800]
## Overview

To be ready for trading as quickly as possible we want to simplify the design of the reward system, and the network treasury accounts and transfers that support it. This ticket is for discussion of a proposed revised scope and also serves as the ticket to implement the agreed changes (once agreed) in the specs. 

It should only be closed when engineering (including @vegaprotocol/core and @vegaprotocol/qa) are happy with the updated specs. 

The below proposal affects/supersedes specs `0055-TREA`, `0056-REWA`, `0057-REWF`, and impacts WIP spec `0067-transfers` ([PR](https://github.com/vegaprotocol/specs-internal/pull/779)).

## Principles and approach

In order to simplify the design as far as possible, we have looked to drop entire features if possible and otherwise remove transactions, configurability, and a calculations. The following is a summary of the simplifications in this proposal:

- We no longer create or control rewards with transactions and there are no per-reward-scheme-instance parameters
- All rewards therefore now implicitly exist for all markets/assets
- We now only ever have one reward scheme per reward type + settlement asset + reward payout asset combination
- All rewards are now calculated once per epoch with the same epochs as validators / staking
- We always pay out the FULL reward pool each epoch
- All new rewards being added are now based on a simple sum of already available data
- We longer have governance controlled transfers in scope. It will therefore initially be impossible to pay out of network treasury accounts, and they exist ONLY as the place that the insurance pool balance goes to when a market closes). Note: this means we will no longer top up validator rewards to 0x0 network treasury but instead send them to a Vega pubkey and use transfer transactions to move from the pubkey to the validator reward pool

## Summary of new scope / requirements

- **Network treasury account** (per asset) exists and can be paid INTO by depositing the asset to 0x0 as well as via transfers and from insurance pools at market closing. At this point funds can’t be paid OUT of the network treasury for any asset.
- **Transfers** from a Vega pubkey general account ONLY
    - To: another (different) pubkey or the network treasury or any valid reward pool account
    - Created by transactions to the network going through consensus (in future governance proposals will be used to create transfers from network treasury or reward pool accounts to other accounts, for now that is not possible)
    - One-off transfers
        - Amount
        - From/to accounts
        - Date/time (amount is taken immediately and paid out on date)
    - Regular transfers (maximum of 1 per from and to account pair)
        - Start epoch
        - End epoch
        - Start amount
        - From/to accounts
        - Factor
        - Before start epoch, after end epoch 0 is transferred at beginning of epoch (cancelled after end epoch)
        - In between, amount is paid at the start of each epoch where: amount = start amount * factor ^ (current epoch - start epoch)
        - Change by sending a new regular transfer for same from and to accounts
        - Cancel by sending one that sets the amount to 0
    - Transaction initiated/controlled (from = pubkey)
- **Rewards general framework**
    - Reward fund account (per reward + settlement asset + reward payout asset combo except for validator rewards which is just one per reward payout asset)
    - Count metric:
        - value of X at end of period (e.g. validator score)
        - sum of X over period (i.e. fees)
    - Period = 1 epoch
    - Distribute full reward pool account per 1 epoch pro rata 
- **Rewards needed for MVP**
    - Value of validator score (already exists)
    - Sum of fees paid (accross all markets for an asset)
    - Sum of maker/taker fees received (accross all markets for an asset)
    - Sum of LP fees received (accross all markets for an asset)
    - For any epoch if lifetime sum of trade value for fee purposes for any markets goes over network_param * quantum FOR THE FIRST TIME, the original proposers of those markets share the reward pool equally (if none, no payout). No market ever gets paid out more than once. (Across all markets for an asset.)

## Next steps

We need to validate these requirements, assess the complexity and impact to build and QA them, and then get specs updated (including acceptance criteria) and review by @vegaprotocol/qa and @vegaprotocol/core.

**Comment by ze97286** [comment]
Focusing on rewards (as opposed to transfers), it's a bit more complicated than what is described here. For each reward type we need to know:
- how the fraction each participant gets is calculated - it may be trivial for some of those, it's not trivial for staking rewards (val score is only part of the calculation, it's not all of it)
- who qualifies for the reward (e.g. all parties that traded in an asset? etc.) 
(there are some more details around these but generally if we're able for each of those to specify a function that returns for each participant their payout then it could all be plugged into a framework that at the end of the epoch checks for all assets if there are funded reward accounts for each of the reward types and just calculates.   

But bottom line I think it's doable.

**Comment by ze97286** [comment]
1. we are removing the option of delayed payouts - payouts are made at the end of the epoch at the same time they are calculated
2. we are removing the option of fractional rewards, i.e. we are always paying out the whole balance of the reward account at the time of the reward calculation
3. when a market is closed the market insurance account is still split between the asset global insurance and the other market’s of the asset insurance accounts
4. transfers are added to the checkpoint and snapshot
5. intermediate data of tracking market fees is not added to the checkpoint - therefore any fees paid before the checkpoint was taken during the epoch doמ’t count for rewards - maybe we should take a checkpoint of that actually.
6. as payouts are made immediately at the end of the epoch (if there is balance in the reward account) there is no need for snapshot of reward engine
7. the net params for fraction, delay, and asset for staking and delegation can be removed
8. data tracking the volume of the market that goes toward the proposer reward must be kept in CP and snapshot to avoid double (or no) payment

----- questions -----
for any reward type - do we still apply the max per epoch reward (total)?
for the new reward types, do we apply max per participant or there’s no need/point?
for the market proposers reward, 2 questions:
suppose in the same epoch 2 markets reached the point of eligibility to the bonus, how is it split between their proposers? suppose one market has 2 and the other has 5, if the bonus divided into markets first and then between proposers?
suppose in an epoch a market reached the point of eligibility but there’s no balance in the corresponding reward account, do they stay eligible in the next epoch until a balance exists and bonus is received?

**Comment by davidsiska-vega** [comment]
1. @Vegaklaus argues that we want, in the future, to be able to punish the validators if the protocol finds retrospectively that the validators misbehaved. I would be ok with the "additional" rewards (not staking and delegation) being paid immediately. 

@witgaw argues that having the functionality now adds complexity and doesn't bring much. It may be better to re-introduce once we have validators punishments implemented. @ze97286 agrees.

**Comment by davidsiska-vega** [comment]
2. I agree, the period transfers take care of this. @barnabee

**Comment by davidsiska-vega** [comment]
3. In LNL we don't keep anything market related, in particular the insurance pool. My suggestion would be that it's easier to implement reward pools for each asset and transfer the insurance pool of any market that has settled into the reward pool account for the asset. The reward pool accounts then get stored in LNL checkpoint. Note that at the moment there is no mechanism to move the money out. That's fine. We'll add governance-initiated transfers later.

**Comment by davidsiska-vega** [comment]
4. yes.

**Comment by davidsiska-vega** [comment]
I think 5. makes sense: if it's an orderly checkpoint restart then all markets should have settled and rewards would have been paid. If it's a restart after a crash we don't have the corresponding markets because we don't save those, so there is no sensible way to restore

**Comment by davidsiska-vega** [comment]
6. yes, pending 1.

**Comment by davidsiska-vega** [comment]
7. yes, pending 1. 
8. yes.

**Comment by davidsiska-vega** [comment]
> for any reward type - do we still apply the max per epoch reward (total)?

We can get rid of this as the recurring transfers can cover this.

**Comment by davidsiska-vega** [comment]
> for the new reward types, do we apply max per participant or there’s no need/point?

Let's not bother and keep it simple.

**Comment by davidsiska-vega** [comment]
> suppose in the same epoch 2 markets reached the point of eligibility to the bonus, how is it split between their proposers? suppose one market has 2 and the other has 5, if the bonus divided into markets first and then between proposers?

There is only ever one proposer per market; split it equally between all eligible.

**Comment by davidsiska-vega** [comment]
> suppose in an epoch a market reached the point of eligibility but there’s no balance in the corresponding reward account, do they stay eligible in the next epoch until a balance exists and bonus is received? 

No. Tough.

**Comment by ze97286** [comment]
> In LNL we don't keep anything market related, in particular the insurance pool. My suggestion would be that it's easier to implement reward pools for each asset and transfer the insurance pool of any market that has settled into the reward pool account for the asset. The reward pool accounts then get stored in LNL checkpoint. Note that at the moment there is no mechanism to move the money out. That's fine. We'll add governance-initiated transfers later.

actually we are keeping the total insurance pools of the asset (across all of its markets) in the checkpoint, so that would be equivalent I guess and we don't need this change. @davidsiska-vega @jeremyletang

**Comment by davidsiska-vega** [comment]
> actually we are keeping the total insurance pools of the asset (across all of its markets) in the checkpoint, so that would be equivalent I guess and we don't need this change. @davidsiska-vega @jeremyletang

But where is the total insurance pool of the asset restored after a LNL restore? Since no markets exist after a LNL restore the only place I can think of would be the treasury account for the asset.

**Comment by ze97286** [comment]
@davidsiska-vega it's restored into the global asset insurance account.

**Comment by davidsiska-vega** [comment]
I feel like this is the first time I hear about "global asset insurance account". 🤣 So I hope it wasn't me who introduced the term.

I don't think the global asset insurance account is accessed anywhere (it's only the market insurance pool that helps pay for closeouts). 

So I'd suggest:
1) after market settlement the balance in the insurance account for the market gets transferred to this "global asset insurance account". 
2) we stop calling it "global asset insurance account" and start calling it network treasury account for the asset.

**Comment by ze97286** [comment]
it can't be the first time @davidsiska-vega. We have logic that at the closing of market we split the funds of the insurance of the market with the other open markets and the *asset* insurance pool - so it must be in some spec I hope :) 

It's a good point though that this is never used for anything.

**Comment by ze97286** [comment]
separate question re proposers reward & LNL:

suppose at the point of checkpoint a market has reached 50% of the required threshold of trading volume for the reward. should this count resume from that point after the restore or should it restart from 0? and then the only thing we need to keep in the checkpoint is the list of already paid markets. 

Also, do we need to keep closed market data in the checkpoint forever or can we only keep open market payment information (i.e. only keep markets that already paid the proposers the reward)?

**Comment by davidsiska-vega** [comment]
I don't think there is a way to make market creation rewards work across LNL checkpoints. I would do the following. If there are funds in market creation reward account then they get bundled into the "network treasury account for the asset" in each LNL checkpoint. If the network is shutdown before criteria for paying the reward is met / reward paid then the market proposer is out of luck(*). 

(*) Once we have transfers by governance and they didn't get paid then we can always do an ad-hoc governance-induced transfer to their vega key from the network treasury account.

**Comment by davidsiska-vega** [comment]
> suppose at the point of checkpoint a market has reached 50% of the required threshold of trading volume for the reward. 

Markets aren't stored so any markets after LNL restore will need to be proposed and will have a new ID, so I really don't see how to get it working.

**Comment by ze97286** [comment]
> I don't think there is a way to make market creation rewards work across LNL checkpoints. I would do the following. If there are funds in market creation reward account then they get bundled into the "network treasury account for the asset" in each LNL checkpoint. If the network is shutdown before criteria for paying the reward is met / reward paid then the market proposer is out of luck(*).

So basically you're saying that since LNL resets the market, if they got paid before the LNL, they still have a chance to get paid again when the market is restored from proposal. if that's cool then we don't need to worry about it. 

We're actually saving and restoring all reward account balances so I don't think there's a need to transfer back to the asset reward account.

**Comment by gordsport** [comment]
Details captured in this issue + conversations are to be collated and added to the relevant specs

**Comment by ze97286** [comment]
Re insurance pool for the asset - the fix for that is captured in https://github.com/vegaprotocol/vega/issues/4653
