### ISSUE TITLE
Chore: Optimal stake multiplier missing from network parameters spec

### ISSUE THREAD

**Issue by candida-d** [vegaprotocol/specs#815]
'reward.staking.delegation.optimalStakeMultiplier' [as referenced here](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0061-REWP-simple_pos_rewards_sweetwater.md) is not described in the [network parameters spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0054-NETP-network_parameters.md), but should be.

**Comment by gordsport** [comment]
Deciding if net params spec should be maintained for all changes to params - `parked` for now

**Comment by davidsiska-vega** [comment]
https://github.com/vegaprotocol/specs/blob/master/protocol/0054-NETP-network_parameters.md has been updated and points to core code for valid netparams and ranges.
