### ISSUE TITLE
0001-MKTF-market framework spec needs acceptance criteria, or an agreement that it doesn't need any

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#824]
In order to get QA test coverage [this spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0001-MKTF-market_framework.md) needs to have clear acceptance criteria defines with acceptance IDs.

**Comment by cpuja84** [comment]
Closing this ticket as relevant PR has been merged
