### ISSUE TITLE
Move the LNL spec from non-protocol to protocol specs directory 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#834]
The [LNL spec](https://github.com/vegaprotocol/specs-internal/blob/master/non-protocol-specs/0005-limited-network-life.md) currently resides in the non-protocol directory of the specs repo.

As this feature is used as part of the protocol more so than first expected we should move this into the protocol directory.

- [ ] Move this spec to the protocol directory
- [x] Update any known links in other specs to pint to the new location
- [x] Give the spec a unique CODE as per the other specs
- [x] Capture acceptance criteria for this feature and give unique IDs so that coverage can be measured

**Comment by edd** [comment]
**Spec moved**: https://github.com/vegaprotocol/specs-internal/blob/master/non-protocol-specs/0005-NP-LIMN-limited_network_life.md

Me and @cpuja84 decided *not* to move this in to the `/protocol/` folder, but instead give codes to Non Protocol specs as well, with a format that indicates that. See #848
