### ISSUE TITLE
De-duplicate feature file tests cross specs-internal and vega repos

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#851]
In order to remove the duplicated feature files across specs-internal and vega repos we will de-duplicate based on the following rules:

- [ ] Feature files that are in specs-internal and need research review will remain in specs-internal repo, any duplicates in the vega repo will be removed
- [ ] Feature files that are NOT in specs-internal and need research review will be moved in specs-internal repo, any duplicates must be removed
- [ ] All others that do not need research review will remain in the Vega repo, and any duplicates removed from specs-internal.

**Comment by cpuja84** [comment]
I think this issue can be closed now and we are all in agreement of the new workflow.
FYI - @gordsport @edd @davidsiska-vega
