### ISSUE TITLE
Party spec should talk about keys more

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#855]
Party / public key are used relatively interchangeably in general. https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0017-party.md Should make it clear how these things relate.

Target audience: end users

**Comment by davidsiska-vega** [comment]
I don't see what more we want:
```
A party is any entity participating on Vega blockchain with one-to-one mapping between a Vega wallet public key and “party”. Also known as user / trader / participant / voter.
```

**Comment by edd** [comment]
I think it does.
