### ISSUE TITLE
Transaction lifecycle spec

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#857]
There’s not spec covering how a [transaction](#856) moves through the system.

I’ve marked this one as ‘Gold plating’ because it’s not required to verify our system is working end to end, but it is good extra context for how the system should work.

**Comment by davidsiska-vega** [comment]
We should probably have a spec which says:
- transaction submitted to mempool
- transaction included in a block after it passed checkTx and subject to priority / gas costs 
- transaction processed, updating core state and producing events. 

Anything else?
