### ISSUE TITLE
Update checkpoint spec

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#859]
# Spec is out of date
- Lots of things are missing from the checkpoint

# New things to add
- Checkpoint should include the last (ETH/other network) block seen so that the EEF knows where to restart playing 
- Also the staking balances of all the bridges
  - Note for @edd who missed the subtlety: The latter works because the former means we won’t replay duplicates
    - Note for everyone: we replay from `latest block seen - state.confirmations` So that things that were seen but not confirmed are not double counted

**Comment by gordsport** [comment]
Possibly related to: https://github.com/vegaprotocol/specs-internal/issues/834

**Comment by edd** [comment]
It's not, but I feel like what I was originally requesting here is covered in the current spec (The 'creating a checkpoint' is clear enough)
