### ISSUE TITLE
Pegged Order spec mentions negative offset, which is no longer supported

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#861]
https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0037-OPEG-pegged_orders.md#guide-level-explanation

This *was* supported, but isn’t any more. Let’s make the spec match reality

**Comment by gordsport** [comment]
Please can you clarify if this issue is resolved or still needs action?

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/specs/pull/1268
