### ISSUE TITLE
Orphaned specs 

### ISSUE THREAD

**Issue by edd** [vegaprotocol/specs#864]
![image](https://user-images.githubusercontent.com/6678/153583426-4b6a2ba4-b5b0-4f6c-bc91-9746edf60493.png)

There are quite a few specs that aren't linked from any other spec. Let's do a sweep and review each unlinked spec. While it's valid, I have a suspicion that some might contain things that aren't well represented in places that they should be.

# 0 links (excluding milestones, readmes)
- 0060-WEND-wendy
- 0065-FTCO-floating_point_consensus
- 4-cosmic-elevator
- 999999-maybe-one-day
- 0063-VALK-validator_vega_master_keys
- 0023-CALI-calibrators
- 0022-AUTH-auth
- 
# 1 link
- 0011-MARA-check_order_allocate_margin
- 0067-KEYS-key_management
- staking-and-governance (glossary)
- 0066-VALW-validator_tendermint_weights
- 0039-MKTD-market_depth_calculation

# 2 links
- 0030-ETHM-multisig_control_spec

**Comment by davidsiska-vega** [comment]
As a first step - we should re-run the tool again to see what's "orphaned" and then proceed to improve.

**Comment by edd** [comment]
![image](https://user-images.githubusercontent.com/6678/209948871-cf15b77c-077d-4b7f-83cc-0d4e51c5b4e9.png)
