### ISSUE TITLE
Allow multiple changes in a single governance proposal (network params first)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#870]
In order to be ready for Q2 2022 development we need to agree upon the scope for the engineering team to deliver in this time period.

Update [0028-GOVE-governance.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0028-GOVE-governance.md)? with details of how to allow multiple changes to be in a single proposal to enable the expected work related to the prioritisation meeting held on the [Notion Board](https://www.notion.so/vegaprotocol/Proposals-can-change-multiple-parameters-c890a2397d69484a961cbbb4f1d38e65)

How do we know when we are done:

 - [ ] The spec has been updated to indicate what are the requirements for allowing multiple changes in a single proposal
 - [ ] The specification contains acceptance criteria with IDs that reflect the scope of the work required for Q2 2022
 - [ ] The engineering team has reviewed the specifications and understand the scope
 - [ ] The spec is merged into the specs repo before engineering start development/test work

**Comment by gordsport** [comment]
split this to :

- multiple net params changes (cosmic)

- wider changes (net params + markets + other etc...) (AFTER cosmic)

**Comment by davidsiska-vega** [comment]
Closed by https://github.com/vegaprotocol/specs/pull/1782 .
