### ISSUE TITLE
Vega reward staking from asset bridge side + automatic staking of locked rewards

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#873]
Update [0059-STKG-simple_staking_and_delegating.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0059-STKG-simple_staking_and_delegating.md)? with details of how to allow staking from general account to enable the expected work related to the prioritisation meeting held on the [Notion Board](https://www.notion.so/vegaprotocol/Proposals-can-change-multiple-parameters-c890a2397d69484a961cbbb4f1d38e65)

Currently the spec details that the user "MUST have some balance of vested or unvested governance asset in an Ethereum wallet" to be able to stake for the first time. 

How do we know when we are done:

 - [ ] The spec has been updated to indicate what are the requirements for allow staking from general account
 - [ ] The specification contains acceptance criteria with IDs that reflect the scope of the work required for Q2 2022
 - [ ] The engineering team has reviewed the specifications and understand the scope
 - [ ] The spec is merged into the specs repo before engineering start development/test work

**Comment by davidsiska-vega** [comment]
Closed by #2347 .
