### ISSUE TITLE
New order types (such as pegged non-persist, take profit)

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#875]
Lack of order types/flags such as pegged non-persist, post only, reduce only, stop loss, take profit prevent makes some actions impossible (such as definitively closing all positions) and makes risk and position management harder. Adding these order types would give traders more control, potentially reduce load on the system, and likely reduce risk and spreads overall.

Updated to [0014-ORDT-order_types.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0014-ORDT-order_types.md) and other specs? to add the new order types

How do we know when we are done:

- [ ] The spec has been updated to indicate the requirements
- [ ] The specification contains acceptance criteria with IDs that reflect the scope of the work required for Q2 2022
- [ ] The engineering team has reviewed the specifications and understand the scope
- [ ] The spec is merged into the specs repo before engineering start development/test work

**Comment by davidsiska-vega** [comment]
Closing, if we want any new order functionality it should be business driven in a new ticket.
