### ISSUE TITLE
Specification for a two-way Ethereum bridge

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#878]
In order to be ready for Q2 2022 development we need to agree upon the scope for the engineering team to deliver in this time period.

We need a specification for a two-way Ethereum bridge. Further details  related to the prioritisation meeting can be seen on the [Notion Board](https://www.notion.so/vegaprotocol/Turning-Ethereum-bridge-into-two-way-bridge-6fd2564d6213433c92d48020cd602b29)

Can this be an extension to [0031-ETHB-ethereum_bridge_spec.md](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0031-ETHB-ethereum_bridge_spec.md) or should it be a new spec. I think @C0deMunk33 suggested this would be a new smart contract and not an update to the existing bridge.

How do we know when we are done:

- [ ] The spec has been updated to indicate what are the requirements for flexible oracles and basic combinators
- [ ] The specification contains acceptance criteria with IDs that reflect the scope of the work required for Q2 2022
- [ ] The engineering team has reviewed the specifications and understand the scope
- [ ] The spec is merged into the specs repo before engineering start development/test work

**Comment by davidsiska-vega** [comment]
Closing as duplicated by #1132
