### ISSUE TITLE
Update 0062-SPAM-spam_protection - post Oregon Trail

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#905]
```
0062-SPAM-spam_protection.md
  Criteria:      0
  Referenced by: 0
```

**Comment by davidsiska-vega** [comment]
@Vegaklaus These should come in the form of testable stories / scenarios. See e.g. 0066-VALW for a plausible way of doing them (at least no-one complained yet). 

They don't have to be exhaustive (though ideally they of course would be) and should cover at least some of the basics.

**Comment by gordsport** [comment]
reopening as one open PR remains
