### ISSUE TITLE
Validator leaving transaction

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#922]
At the moment 0069-VCBS talks about validators joining. 

If a validator wishes to leave they can "switch off" the node but that's suboptimal for the protocol (might increase a chance that consensus won't happen) and it's suboptimal for those who delegated to the validator. 

A ~~better~~ way would be that we have a `validator_leaving` transaction which the validator can submit anytime. When this happens all the delegated stake will be distributed pro-rate among other validators. When epoch ends this validator will automatically be removed from the list of consensus-forming validators and afterwards they can switch off without impacting anyone.

**Comment by gordsport** [comment]
Moving out of 🤠 as initially we wont have validators joining/leaving

**Comment by davidsiska-vega** [comment]
Might actually make more sense as a validator-governance action (voting weight equal to tendermint weight, when we think this through) to remove a non-performing validator.

**Comment by barnabee** [comment]
Why don’t we just do these actions when the validator no longer self stakes. Self staking IMO is the indication of intent to be a validator, and stopping doing so = leaving.

**Comment by barnabee** [comment]
Whatever happens, when a validator leaves I’m not sure if the stake should be distributed pro-rata, it may be better to have people lose rewards and potentially choose to delegate or all to a new validator or one with lower delegation.

In any case it’s not like when adding stake where there’s already an unambiguous choice how the user chose to delegate.

**Comment by davidsiska-vega** [comment]
This probably works best - if you remove self stake then you're signalling you want to stop validating. 

At this point the network should emit the ethereum transaction that would allow you to be removed from the bridge and unstake all that's been delegated to you. We could automatically re-stake pro-rata etc. but perhaps best to leave unstaked so you're forced to re-delegate manually and think about who should get your delegation.
