### ISSUE TITLE
Coded features review: List of existing mock feature tests

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/specs#923]
Below is the list of few existing mock feature tests which Puja thinks would bring value if picked up next. Discuss with team and finalise the priority or selection order for next deliverable.

https://github.com/vegaprotocol/specs-internal/blob/master/qa-scenarios/0003-mark-to-market-settlement.feature.mock
https://github.com/vegaprotocol/specs-internal/blob/master/qa-scenarios/0012-position-resolution.feature.mock
https://github.com/vegaprotocol/specs-internal/blob/master/qa-scenarios/0019-margin-calculator.feature.mock
https://github.com/vegaprotocol/specs-internal/blob/master/qa-scenarios/loss-socialization.feature.mock

**Comment by edd** [comment]
My total guess at a priority order of those 4:
- Position resolution
- Margin calculator
- Settlement
- Loss socialisation

Justification: The frequency they happen
What would make me change my order: If one was already well testing in unit tests or core integration tests, it would have it's priority lowered
