### ISSUE TITLE
Measuring liquidity

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/specs#93]
In GitLab by @davidsiska-vega on Mar 3, 2019, 10:18

# Outline
We need to have a workable definition of liquidity provision both at one instant of time and also as times goes by. 

This needs to be attributed to market makers for a book so that they can be rewarded for providing liquidity. 

# Requirements

A formula that can be implemented in core vega engine. 

## Notes
- See https://drive.google.com/open?id=1MIJX6fxnfQXOmW9DGj8UxTpyT-VhEnkT 

# Relevant whiteboard section

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:06

assigned to @tamlyn10

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:06

assigned to @davidsiska-vega

**Comment by ashleyvega** [comment]
In GitLab by @tamlyn10 on Oct 10, 2019, 17:06

assigned to @barnabee

**Comment by barnabee** [comment]
Closing because we have a whole paper on this now cc @davidsiska-vega @tamlyn10 @witgaw 

Please reopen and comment if you disagree!
