### ISSUE TITLE
0011-MARA-check_order_allocate_margin needs more acceptance criteria

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/specs#930]
Add more acceptance criteria to margin [spec](https://github.com/vegaprotocol/specs-internal/blob/master/protocol/0011-MARA-check_order_allocate_margin.md) by linking feature test scenarios around testing margin allocation with lognormal risk model for orders as suggested by @davidsiska-vega [here](https://github.com/vegaprotocol/specs-internal/pull/919#pullrequestreview-890843961)

**Comment by davidsiska-vega** [comment]
I think this is good enough(tm) for now. We will worry about log-normal tests later (it's being tested elsewhere).
