### ISSUE TITLE
We need ACs for effects of changing all network parameters we have

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/specs#954]
The task: 
1. Make sure all network or market parameters are covered in `0054-NETP-network_parameters.md`. 
2. For each network or market parameter create and acceptance criteria story that goes like:
- parameter changes
- system behaves in a new and appropriate way reflecting the change. 

Example:
1. Network is running with `validators.epoch.length` = `5 mins`. 
2. Epoch 1 starts.
3. There are 3 validators with equal stake and the validator reward scheme has 90 VEGA tokens in it.
4. Epoch 1 ends 5 minutes from Epoch 1 start and each validator gets a reward of 30 VEGA.
5. Epoch 2 starts. 
6. `validators.epoch.length` is changed to `1 mins` via governance. 
7. Validator reward scheme receives 18 VEGA token deposit.
8. Epoch 2 ends 1 minute after Epoch 2 started. 
9. Each validator gets 6 VEGA. 

Maybe treat this as a "meta-issue" and create new issue for a couple of parameters at a time to be dealt with. Otherwise it's a mammoth task. 
 

- [x] #1016
- [x] #1018
- [x] #1017
- [x] #1019
- [x] #1020
- [x] #1021
- [x] #1022
- [x] #1023
- [x] #1024
- [x] #1025
- [x] #1026
- [x] #1027
- [x] #1028
- [x] #1029
- [x] #1030
- [x] #1031

**Comment by gordsport** [comment]
- https://github.com/vegaprotocol/system-tests/issues/539

**Comment by gordsport** [comment]
Closing as all checklist items are complete.

Further tickets to be opened should/when we want to expand this to all net params
