### ISSUE TITLE
0026-AUCT `003` and `004` AC codes look to be invalid

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#960]
The AC codes 0026-AUCT-003 and 0026-AUCT-004 seem to be invalid 

Can we get these updated/corrected and feedback to @MuthuVega  

This spec also has content in that does not exist, should we:

- make explicit that its not implemented (yet?)
- remove and add in in/when we decide that there is a need for this functionality

**Comment by edd** [comment]
@MuthuVega you are correct, these can't be tested at the moment. I'll remove them for now
