### ISSUE TITLE
Update ACs for 0066-VALW-validator_tendermint_weights.md to include Ersatz validators etc..

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/specs#966]
During the spec review meeting to ensure that the specs were in order for test-coverage work in readiness for enabling trading it has been identified that this spec needs the ACs updating to include Ersatz validators etc..

Without this the following system-test issue is blocked from completion 
- https://github.com/vegaprotocol/system-tests/issues/534

**Comment by davidsiska-vega** [comment]
Tendermint weights only play a role for tendermint validators. 

For ersatz validators we calculate validator score and it is taken into account in calculating rewards (and should be tested there). 

So the acceptance criteria are deemed sufficient.
